### ISSUE TITLE
slash in secret-key causes aws-sdk-java-s3 403 when putObject

### ISSUE THREAD

**Issue by wingice** [aws/aws-sdk-java#1425] opened 2017-12-26 08:48 UTC
I encountered the same issue again.  Getting a new secret-key without forward slash made the 403 go away.
Please reference :
https://forums.aws.amazon.com/thread.jspa?threadID=134011

aws-java-sdk-s3: 1.11.255

**Comment by dagnir** [comment] 2017-12-27 17:45
Looks like the issue is that having a `/` in the access key ID messes with the formatting of the `Authorization` header for SigV4: https://github.com/aws/aws-sdk-java/blob/4cd41a6ca7e0e6cf0670cd125741fd958d06084c/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L437-L438

**Comment by wingice** [comment] 2017-12-29 00:45
Good to hear,  hoping it would be fixed soon.

**Comment by shorea** [comment] 2018-01-25 00:05
@wingice I don't believe the slash is your problem. I have credentials that have a forward slash and have no issue, and you note in the forums that it works for some APIs but not PutObject. I would suggest checking the policies on your role to make sure they grant you the appropriate permissions to call PutObject in your bucket. Closing this since it sounds like you are unblocked.

**Closed by shorea** 2018-01-25 00:05 UTC
Labels: Investigating
