### ISSUE TITLE
Special Characters problem when using httpclient 4.5.7

### ISSUE THREAD

**Issue by twoodhouse** [aws/aws-sdk-java#1968] opened 2019-04-09 20:31 UTC
I am using aws-java-sdk 1.11.534
A different portion of my project imports apache httpclient 4.5.7, so this sdk was using 4.5.7 rather than the default 4.5.5.

At the top level, I am seeing that with httpclient 4.5.7, this s3 sdk fails to write files with keys containing certain approved special characters (such as "(", "!", or ")") when using the client.putObject(...) method

I have isolated this to httpclient 4.5.7. Using the same code with httpclient 4.5.5 works correctly.

It is possible that this is an issue with httpclient, but it is more likely an issue with how this sdk encodes (or does not encode) these approved characters before making a request

**Comment by debora-ito** [comment] 2019-04-09 23:56
Hi @twoodhouse, thank you for reporting this issue. 

We are aware of the problem, and it is in fact caused by changes in `httpclient 4.5.7`. We are tracking the issue in #1919 and the team is analyzing a possible solution.

I'll go ahead and close this, but feel free to reopen if you have any other question.

**Closed by debora-ito** 2019-04-09 23:56 UTC
