### ISSUE TITLE
SDK is retrying under `401` error codes

### ISSUE THREAD

**Issue by evanye** [aws/aws-sdk-java#2204] opened 2020-01-25 00:43 UTC
When the SDK is configured with invalid access credentials, it returns 401 Unauthorized, which is expected.
However, when the SDK is configured with invalid credentials AND a larger maxRetry value, then it takes a while for a SDK request to fail. This behavior is unexpected - according to the docs https://docs.aws.amazon.com/general/latest/gr/api-retries.html, I expect `401` error codes not to retry.

Here is a code snippet:
```scala
import com.amazonaws.internal._; import com.amazonaws.auth._; import com.amazonaws._; import com.amazonaws.retry._; import com.amazonaws.services.ec2._ 

val cred = new StaticCredentialsProvider(new BasicAWSCredentials("key", "secret")) 
val clientConf = new ClientConfiguration()
val policy = new RetryPolicy(PredefinedRetryPolicies.getDefaultRetryPolicy.getRetryCondition, PredefinedRetryPolicies.getDefaultRetryPolicy.getBackoffStrategy, 16 /* THIS IS NON DEFAULT */, true)
clientConf.setRetryPolicy(policy)
val client = new AmazonEC2Client(cred, clientConf) 
// this request takes a long time to fail
client.describeInstances(new com.amazonaws.services.ec2.model.DescribeInstancesRequest())
```

**Comment by debora-ito** [comment] 2020-02-14 21:38
Hi @evanye I can reproduce the 401 Unauthorized being retried locally. Will investigate the cause and discuss a solution with the team.

**Comment by evanye** [comment] 2020-02-25 23:02
@debora-ito thanks for confirming with a repro. What are the next steps here? Any update on when this could be fixed?

**Comment by debora-ito** [comment] 2020-02-27 19:23
The task is in our backlog, we will discuss the solution when it gets prioritized.

**Comment by dagnir** [comment] 2020-03-05 19:23
Hi, the reason the request is being retried is because of the SDK's automatic [clock skew management](https://github.com/aws/aws-sdk-java/blob/bb58a83b825f4681ec478e850981ac17c4d96807/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L197), where the SDK retries the request with an adjusted clock if it thinks an error is caused by clock skew.

https://github.com/aws/aws-sdk-java/blob/bb58a83b825f4681ec478e850981ac17c4d96807/aws-java-sdk-core/src/main/java/com/amazonaws/retry/RetryUtils.java#L45-L50

Since time is a component of the SigV4 process, it's possible that the signature did not match because the clock was too skewed from server time rather than invalid credentials. Unfortunately there are no other details provided with signing errors to determine what the exact cause was so all signing errors are treated as possible clock skew and are retried.

Going to go ahead and close this. Please feel free to reopen if you have further questions or require further assistance.

**Closed by dagnir** 2020-03-05 19:23 UTC
Labels: feature-request, needs-discussion

**Comment by evanye** [comment] 2020-03-05 19:51
It sounds like the aws backend should return a better error code when there's clock skew instead of just AuthFailure, and the SDK should use that to more intelligently retry.
