### ISSUE TITLE
SQS: ReceiveMessageRequest with invalid kind of attributes

### ISSUE THREAD

**Issue by janjaali** [aws/aws-sdk-java#2061] opened 2019-07-24 20:39 UTC
Creating a ReceiveMessageRequest with QueueAttributeNames makes no sense and is not documented as such as well:
https://github.com/aws/aws-sdk-java/blob/042fa6c1727e52328a9dfd1684f9d46dbb98e39b/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/ReceiveMessageRequest.java#L1008

Looking at the documentation it states that valid attributes name are: *ApproximateFirstReceiveTimestamp*, *ApproximateReceiveCount*, *SenderId*, *SentTimestamp* and etc. while the `QueueAttributeNames` consists of queue related attributes like *Policy*, *ApproximateNumberOfMessages*, *KmsMasterKeyId*.

Knowing that this sdk is already in production usage all over the globe it would be nice to have at least a deprecation warning on top of this method to avoid libraries to rely on this method in future e.g. akka/alpakka#1838.

**Comment by debora-ito** [comment] 2019-07-26 16:57
Hi @janjaali thank you for reporting this. The `ReceiveMessageRequest` is a auto-generated class based on internal service models, so the problem is the SQS model is mapping its attributes to the wrong data type, the correct one should probably be [`MessageSystemAttributeName`](https://github.com/aws/aws-sdk-java/blob/042fa6c1727e52328a9dfd1684f9d46dbb98e39b/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/MessageSystemAttributeName.java).

I'll forward this issue to the SQS team and will update here when they reply.

**Comment by avdv** [comment] 2020-02-28 12:28
Hi. Any updates here?

**Comment by debora-ito** [comment] 2023-03-21 01:31
No updates here, other than the SQS team is aware of the issue.
I'll go ahead and close this issue, please track updates here: https://github.com/aws/aws-sdk/issues/233.

**Closed** 2023-03-21 01:49 UTC
Labels: bug, service-api

**Comment by rawpixel-vincent** [comment] 2024-01-16 09:11
<img width="793" alt="Screenshot 2024-01-16 at 16 09 59" src="https://github.com/aws/aws-sdk-java/assets/22284209/92020877-1017-4a70-8d68-2fceb6bd27b3">

But it works, receiving a message with
`message.Attributes.ApproximateReceiveCount === '1'`

the type should not be `AttributeNames?: QueueAttributeName[];` but `AttributeNames?: MessageSystemAttributeName[];`

in `@aws-sdk/client-sqs/dist-types/models/models_0.d.ts`

thank you
