### ISSUE TITLE
Need Subscription or Observer Class or method in aws-java-sdk-appsync.

### ISSUE THREAD

**Issue by Ujjwal9235** [aws/aws-sdk-java#2848] opened 2022-09-16 08:48 UTC
### Describe the issue

Not enough documentation for Appsync in aws java sdk,
I need to implement Subscription or observer to Appsync api to push message to all the subscribers whenever there will be some message get pushed in Appsync api in JAVA. But i can't find any class or method in aws-java-sdk-appsync for subscription.

### Links

[https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/appsync/AWSAppSync.html](url)

**Comment by debora-ito** [comment] 2022-09-16 16:38
Closing as duplicate of https://github.com/aws/aws-sdk-java/discussions/2847.

**Closed by debora-ito** 2022-09-16 16:38 UTC
Labels: documentation, needs-triage
