### ISSUE TITLE
NPE in XmlResponsesSaxParser$AccessControlListHandler

### ISSUE THREAD

**Issue by meshcow** [aws/aws-sdk-java#2620] opened 2021-07-30 11:29 UTC
## Describe the bug
NPE in XmlResponsesSaxParser$AccessControlListHandler with input like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<AccessControlPolicy>
    <Owner><ID></ID>
        <DisplayName></DisplayName>
    </Owner>
    <AccessControlList>
        <Grant>
            <Grantee><ID></ID><DisplayName></DisplayName></Grantee>
            <Permission>FULL_CONTROL</Permission></Grant>
    </AccessControlList>
</AccessControlPolicy>
```

## Expected Behavior
No NPE

## Current Behavior
```
com.amazonaws.SdkClientException: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$AccessControlListHandler
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:177)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseAccessControlListResponse(XmlResponsesSaxParser.java:402)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$AccessControlListUnmarshaller.unmarshall(Unmarshallers.java:165)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$AccessControlListUnmarshaller.unmarshall(Unmarshallers.java:161)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44)
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1777)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1474)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1381)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
	at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:4050)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1273)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1263)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1401)
Caused by: java.lang.NullPointerException
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$AccessControlListHandler.doEndElement(XmlResponsesSaxParser.java:1118)
	at com.amazonaws.services.s3.model.transform.AbstractHandler.endElement(AbstractHandler.java:52)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:163)
	... 37 more
```
## Your Environment

* AWS Java SDK version used: 1.12.35
* JDK version used: 1.8
* Operating System and version: OSX

**Comment by debora-ito** [comment] 2021-08-02 18:07
@meshcow can you provide a code snippet we can use to reproduce the issue?

**Comment by meshcow** [comment] 2021-08-03 08:44
Just feed the XML above to your parser:

```java
import com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public class Aws2620Test {

    @Test
    public void test2620() throws Exception {

        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
            "<AccessControlPolicy>" +
            "    <Owner><ID></ID>" +
            "        <DisplayName></DisplayName>" +
            "    </Owner>" +
            "    <AccessControlList>" +
            "        <Grant>" +
            "            <Grantee><ID></ID><DisplayName></DisplayName></Grantee>" +
            "            <Permission>FULL_CONTROL</Permission></Grant>" +
            "    </AccessControlList>" +
            "</AccessControlPolicy>";

        byte[] bytes = xml.getBytes(StandardCharsets.UTF_8);

        try (InputStream is = new ByteArrayInputStream(bytes)) {
            new XmlResponsesSaxParser().
                parseAccessControlListResponse(is);
        }
    }
}
```

**Comment by debora-ito** [comment] 2022-02-15 02:51
Hi @meshcow, thank you for providing the sample, and apologies for the lack of response.

I compared the xml you provided in the sample code with a xml returned by S3 as part of `s3Cient.doesBucketExistV2()`:
```
<?xml version="1.0" encoding="UTF-8"?>\n
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Owner>
        <ID>xxx</ID>                
        <DisplayName>username</DisplayName>
    </Owner>
    <AccessControlList>
        <Grant>
            <Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">        
                <ID>xxx</ID>                
                <DisplayName>username</DisplayName>
            </Grantee>
            <Permission>FULL_CONTROL</Permission>
        </Grant>    
    </AccessControlList>
</AccessControlPolicy>
```

The NPE you are seeing is because the `<Grantee>` in your example is missing the xmlns:xsi and xsi:type values.

Is the ACL in your example a real-world s3 example, or just a hypothetical one? Wondering how you are seeing this as a getBucketAcl response and how I can replicate.

**Comment by meshcow** [comment] 2022-02-15 08:08
Hi, it came out while I was testing a product with S3-compatible interface by one of our partners. Unfortunately I am not allowed to disclose any details regarding the product. Also, as I don't work for the company anymore, I have no info on how far their partner is with the product.

**Comment by debora-ito** [comment] 2022-02-15 20:01
Got it, thank you for the follow-up.

Since it's a S3-compatible interface they are probably simulating the response, and we don't guarantee that the SDK works with third-party applications.

I'll go ahead and close this, feel free to reach out if you have any other question.

**Closed by debora-ito** 2022-02-15 20:01 UTC
Labels: guidance, third-party
