### ISSUE TITLE
S3 Client / PutObject closes InputStream - violation of RAII

### ISSUE THREAD

**Issue by stanislav-dvorscak** [aws/aws-sdk-java#1594] opened 2018-05-21 19:48 UTC
E.g.:
com.amazonaws.services.s3.AmazonS3.putObject(PutObjectRequest)
com.amazonaws.services.s3.model.PutObjectRequest.PutObjectRequest(String, String, InputStream, ObjectMetadata)

will closes InputStream, which is not supposed to do. See stack trace as example:

```
	ZipInputStream.close() line: 266	
	ReleasableInputStream.doRelease() line: 85	
	ReleasableInputStream.close() line: 69	
	LengthCheckInputStream(SdkFilterInputStream).close() line: 99	
	MD5DigestCalculatingInputStream(SdkFilterInputStream).close() line: 99	
	SdkBufferedInputStream(BufferedInputStream).close() line: 483	
	SdkBufferedInputStream.close() line: 93	
	RequestProgressInputStream(SdkFilterInputStream).close() line: 99	
	RequestProgressInputStream(ProgressInputStream).close() line: 211	
	IOUtils.closeQuietly(Closeable, Log) line: 70	
	AmazonHttpClient$RequestExecutor<Output>.doExecute() line: 756	
	AmazonHttpClient$RequestExecutor<Output>.executeWithTimer() line: 717	
	AmazonHttpClient$RequestExecutor<Output>.execute() line: 699	
	AmazonHttpClient$RequestExecutor<Output>.access$500(AmazonHttpClient$RequestExecutor) line: 667	
	AmazonHttpClient$RequestExecutionBuilderImpl.execute(HttpResponseHandler<Output>) line: 649	
	AmazonHttpClient.execute(Request<?>, HttpResponseHandler<AmazonWebServiceResponse<T>>, HttpResponseHandler<AmazonServiceException>, ExecutionContext) line: 513	
	AmazonS3Client.invoke(Request<Y>, HttpResponseHandler<AmazonWebServiceResponse<X>>, String, String, boolean) line: 4365	
	AmazonS3Client.invoke(Request<Y>, HttpResponseHandler<AmazonWebServiceResponse<X>>, String, String) line: 4312	
	AmazonS3Client.putObject(PutObjectRequest) line: 1755	
```

**Comment by shorea** [comment] 2018-05-22 00:12
@stanislav-dvorscak we can't really change this for V1 since some customers may be relying on the SDK closing the input stream. As a workaround you can wrap your stream in an implementation that just ignores close and pass that to the SDK. We will make this more consistent in V2 of the SDK and put the responsibility of closing the stream on the owner of it.

**Closed by shorea** 2018-05-22 00:12 UTC
Labels: Investigating

**Comment by romankh3** [comment] 2020-05-04 06:32
unexpected behavior.

**Comment by romankh3** [comment] 2020-05-11 07:30
@shorea, hi!
I faced the same issue, as @stanislav-dvorscak mentioned. 
I tried to use your advice with a wrapper for ZipInputStream with an empty implementation for `close()` method. 
I successfully extracted `.txt` files, `.jpg` files. With `.pdf` files I've got unexpected behavior: all were completed without errors, but all `.pdf` files were zero size(0KB).

I also tested case, when I have one pdf file in zip archive and save without wrapper: 
```
ZipInputStream zis = new ZipInputStream(is);
ZipEntry ze = zis.getNextEntry();

amazonS3Client.putObject(bucketName, fileName, zis, null);
```
It was saved properly. I think that it's an issue with saving `pdf` files with empty `close()` method.

Do you know why it was?

Best regards,
Roman.
