### ISSUE TITLE
 Unable to execute HTTP request: Connection reset

### ISSUE THREAD

**Issue by nashid** [aws/aws-sdk-java#1544] opened 2018-04-06 13:09 UTC
Recently, we are plagued with the following error which is happening once we make a call to `putObject`. 

`com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset`

This is an intermittent error which we are observing very frequently and it's making our `aws batch jobs` error-prone and not reliable.

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
```

And this is how are invoking the service:

```
val amazonS3Client = new AmazonS3Client(credentials)
val objectRequest = new PutObjectRequest(s3Bucket, path, file)
objectRequest.setCannedAcl(cannedAcl)
amazonS3Client.putObject(objectRequest)
```

**Comment by spfink** [comment] 2018-04-06 22:56
Can you provide a wire log for when this occurs? Or SDK metrics? What's your request rate?

Connection resets aren't unheard of and can be caused by a number of issues. We'd need additional details to help tune your SDK.

**Comment by nashid** [comment] 2018-04-09 15:42
@spfink our request rate is negligible. And here is the wire log:

```
[main] [39mDEBUG[0;39m [36mc.a.t.a.h.wire[0;39m - http-outgoing-287 >> "[write] I/O error: Broken pipe (Write failed)"
[main] [39mDEBUG[0;39m [36mc.a.t.a.h.i.c.DefaultManagedHttpClientConnection[0;39m - http-outgoing-287: Close connection
[main] [39mDEBUG[0;39m [36mc.a.t.a.h.i.c.DefaultManagedHttpClientConnection[0;39m - http-outgoing-287: Shutdown connection
[main] [39mDEBUG[0;39m [36mc.a.t.a.h.i.e.MainClientExec[0;39m - Connection discarded
[main] [39mDEBUG[0;39m [36mc.a.t.a.h.i.c.PoolingHttpClientConnectionManager[0;39m - Connection released: [id: 287][route: {s}->https://XXXXXXXX.s3.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed)
com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
```

**Comment by shorea** [comment] 2018-04-16 18:34
Please see comments in other issue. This is likely a networking or service issue.

Closing issue, feel free to reopen if you need further assistance from the SDK team.

**Closed by shorea** 2018-04-16 18:34 UTC
Labels: Question, waiting-reply
