### ISSUE TITLE
PKIX SSL error while connecting to SQS 

### ISSUE THREAD

**Issue by mukteshkrmishra** [aws/aws-sdk-java#823] opened 2016-08-24 02:02 UTC
HI,

I have a queue in AWS and while trying to connect it and pushing some message programmatically (using Java SDK) I am getting following error:

NEGOTIATE authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)

[INFO] [talledLocalContainer] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I tried adding AWS public certificate also in JDK keystore's cacaerts using Keystore import command. But still same exception. Can you please help.
keytool -import -alias awscert -keystore /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/lib/security/cacerts -file /path/awspubliccert.pem

[INFO] [talledLocalContainer] com.amazonaws.AmazonClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] [talledLocalContainer] 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:723) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:465) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1750) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1720) ~[aws-java-sdk-1.11.27.jar:?]
[INFO] [talledLocalContainer] 	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessageBatch(AmazonSQSClient.java:1598) ~[aws-java-sdk-1.11.27.jar:?]

[INFO] [talledLocalContainer] Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[INFO] [talledLocalContainer] 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_74]
[INFO] [talledLocalContainer] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394) ~[httpclient-4.5.1.jar:4.5.1]
[INFO] [talledLocalContainer] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:185) ~[httpclient-4.5.1.jar:4.5.1]

**Comment by shorea** [comment] 2016-08-26 04:43
Sounds like your Java installation is corrupt or misconfigured. You shouldn't need to import Amazon's certs. It's signed by a trusted CA which should be in the default trust store. Can you try with a fresh Java installation?

**Comment by shorea** [comment] 2016-08-30 15:02
Closing issue. Feel free to reopen if problem persists.

**Closed by shorea** 2016-08-30 15:02 UTC
Labels: waiting-reply

**Comment by akkemgari** [comment] 2016-09-23 02:48
I have same issue while trying to upload data to S3 bucket and we are using Java-1.8.0_91 version. Please let me what is the work around to resolve the issue?

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        ... 28 more

**Comment by mukteshkrmishra** [comment] 2017-01-10 04:26
@akkemgari : remove jdk and install again. In my case it was permissions which got messed up.

**Comment by gdevapitchai** [comment] 2019-08-06 17:52
Setting the DISABLE_CERT_CHECKING_SYSTEM_PROPERTY to true will solve this issue.

System.setProperty(SDKGlobalConfiguration.DISABLE_CERT_CHECKING_SYSTEM_PROPERTY, "true");
