### ISSUE TITLE
DynamoDBMapperConfig.TableNameResolver disappeared without warning :-(

### ISSUE THREAD

**Issue by mwnorman** [aws/aws-sdk-java#337] opened 2015-01-05 19:19 UTC
Between 1.8.11 and 1.9.0, the interface DynamoDBMapperConfig.TableNameResolver disappeared
without (as far as I can see) any deprecation warnings or hints as to what to do to replace
its use. We are using it to override the @DynamoDBTable annotation with external metadata
so that we can have dev_TBLNAME_XYZ and prod_TBLNAME_XYZ

ref: https://forums.aws.amazon.com/message.jspa?messageID=590876#590876

**Comment by Raniz-at-Sony** [comment] 2015-01-06 07:05
Related/duplicate of: #305

**Comment by hanshuo-aws** [comment] 2015-01-08 21:01
See #305

**Closed by hanshuo-aws** 2015-01-08 21:01 UTC
