### ISSUE TITLE
Conflicting setter definitions for property "networkMode"

### ISSUE THREAD

**Issue by siddheshswnt** [aws/aws-sdk-java#1661] opened 2018-07-05 19:24 UTC
**Summary**
Not being able to deserialize RegisterTaskDefinitionRequest using jackson. 

**Expected Behavior**
I should be able to get RegisterTaskDefinitionRequest from its string input.

## Current Behavior
I am getting following error:
Exception in thread "main" org.codehaus.jackson.map.JsonMappingException: Conflicting setter definitions for property "networkMode": com.amazonaws.services.ecs.model.RegisterTaskDefinitionRequest#setNetworkMode(1 params) vs com.amazonaws.services.ecs.model.RegisterTaskDefinitionRequest#setNetworkMode(1 params)

Here is my code : 
```
ObjectMapper mapper = new ObjectMapper();
mapper.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true);
RegisterTaskDefinitionRequest ronaldo = mapper.readValue(taskDefStr, RegisterTaskDefinitionRequest.class);
```

Also, the versions of Jackson I am using are as follows:
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.8.5</version>
        </dependency>

Java ecs SDK : 1.11.228

**Comment by shorea** [comment] 2018-07-05 19:52
Can you try with the latest version of Jackson? I believe they made some improvements to handling overloaded setters.

**Comment by siddheshswnt** [comment] 2018-07-09 02:47
@shorea even after using their latest 2.9.6 version I am getting the same error.

**Comment by shorea** [comment] 2018-07-17 01:02
@siddheshswnt are you sure 2.9.6 is being used at runtime? I was not able to reproduce this with the latest version of jackson. My code is below

```java
    public static void main(String[] args) throws IOException {
        RegisterTaskDefinitionRequest request = new RegisterTaskDefinitionRequest()
            .withNetworkMode(NetworkMode.Bridge);
        ObjectMapper objectMapper = new ObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            .addMixIn(RegisterTaskDefinitionRequest.class, Mixin.class);
        String serialized = objectMapper.writeValueAsString(request);
        System.out.println(serialized);
        RegisterTaskDefinitionRequest roundTripped = objectMapper.readValue(serialized, RegisterTaskDefinitionRequest.class);
        System.out.println(roundTripped);
    }

    public interface Mixin {
        @JsonIgnore
        ProgressListener getGeneralProgressListener();
    }
```

**Comment by shorea** [comment] 2018-07-18 22:57
@siddheshswnt are you still having this problem?

**Comment by shorea** [comment] 2018-07-20 22:39
@siddheshswnt did you get a chance to try with the code above?

**Comment by shorea** [comment] 2018-07-23 05:52
Closing issue, feel free to reopen if code above does not work for you.

**Closed by shorea** 2018-07-23 05:52 UTC
Labels: Investigating
