### ISSUE TITLE
version 1.11.480 of sdk throws InternalServerError exception when using DynamoDB transactions

### ISSUE THREAD

**Issue by dragan-stepanovic** [aws/aws-sdk-java#1881] opened 2019-01-15 23:23 UTC
AmazonDynamoDB::transactWriteItems throws InternalServerError exception when trying to save two items in transaction.

```
com.amazonaws.services.dynamodbv2.model.InternalServerErrorException: Internal server error (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalServerError; Request ID: P31I9HLBT0FT3LEP9QUP178LJJVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4192)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4159)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeTransactWriteItems(AmazonDynamoDBClient.java:3438)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.transactWriteItems(AmazonDynamoDBClient.java:3405)
```

**Comment by debora-ito** [comment] 2019-01-16 23:56
Hi @dragan-stepanovic, could you please provide some details, to try isolating the problem:
- A code snippet to reproduce the issue
- What region is your client configured in?
- Did you start seeing the issue after a version upgrade?
- Are you still experiencing the issue, or was it temporary?

**Comment by dragan-stepanovic** [comment] 2019-01-18 20:59
Code snippet is just a `AmazonDynamoDB::transactWriteItems` method call with two `TransactWriteItemsRequest` as arguments.
Region is "eu-west-1"
This has happened several times (not sure of the failure percentage yet). Not sure, but might be that it happened with the previous version as well.
You have a request ID in the stack trace stated above, so you can check what were the call arguments.

**Comment by debora-ito** [comment] 2019-01-18 22:10
Thank you for the additional info. I opened an internal ticket with the service team and will update here when they respond.

**Comment by dragan-stepanovic** [comment] 2019-01-26 19:02
one more for Request ID: P5FIHMFCH35JE3ATML9CRMHCCNVV4KQNSO5AEMVJF66Q9ASUAAJG
happened at: January 25th 2019, 02:57:21.424 UTC time
```
com.amazonaws.services.dynamodbv2.model.InternalServerErrorException: Internal server error (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalServerError; Request ID: P5FIHMFCH35JE3ATML9CRMHCCNVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4192)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4159)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeTransactWriteItems(AmazonDynamoDBClient.java:3438)
```

**Comment by debora-ito** [comment] 2019-02-07 18:37
The DynamoDB team is asking: what's the failure rate?

**Comment by dragan-stepanovic** [comment] 2019-02-08 11:26
once per week; in terms of number of requests, don't know, perhaps 1 in 1000

**Comment by debora-ito** [comment] 2019-03-18 23:19
@dragan-stepanovic, 

the DynamoDB team was not able to pinpoint the specific cause of your exceptions, but this week they pushed a new change that will help fix significant amount of InternalServerErrors. 

Could you monitor and say if you're seeing less of these errors?

**Comment by debora-ito** [comment] 2019-03-28 19:13
@dragan-stepanovic any updates after 10 days? Waited a little longer since the rate was once a week.

**Comment by dragan-stepanovic** [comment] 2019-03-29 07:39
I haven't notice the given error in last 10 days. Was there any update to the library since version 1.11.480?

**Comment by debora-ito** [comment] 2019-03-29 18:58
The latest version is `1.11.528` so probably yes. You can check the changelog if you're looking for specific changes: https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md

Glad you are not seeing the issue anymore, thanks for the update. I'll go ahead and close this, feel free to reopen if you have any further questions.

**Closed by debora-ito** 2019-03-29 18:58 UTC
Labels: waiting-service-reply
