### ISSUE TITLE
Reserved Instances

### ISSUE THREAD

**Issue by gurusreekanth** [aws/aws-sdk-java#1080] opened 2017-03-23 13:59 UTC
Hi,

I am using java SDK, and while querying for the reserved instances with the following code
AmazonEC2AsyncClient.describeReservedInstancesAsync() I am not seeing the Reserved instances whose scope is Region.

I tried with no filters as well as setting scope filter to Region.

**Comment by gurusreekanth** [comment] 2017-03-23 14:04
just coincidence I am having only one active Reserved Instance and that is not shown. All other (expired ones) I can see (these have scope "Availability zone") .

**Comment by gurusreekanth** [comment] 2017-03-23 14:05
JDK version - aws-java-sdk-ec2-1.11.36.jar

**Comment by gurusreekanth** [comment] 2017-03-23 14:23
More Info: Reserved instance was purchased in January 2017 so around 2months old and have validity for more than a year. In bill I see a vm runing as a reserved instance since it's creation.

**Comment by gurusreekanth** [comment] 2017-03-27 08:56
Hi, Any update on fetching Reserved Instances whose scope is Region?. Thanks.

**Comment by kiiadi** [comment] 2017-03-27 15:52
@gurusreekanth most likely an issue with the service not sending it back in the response rather than an issue with the SDK. Can you enable wire-logging and post the response to your call and we can take it from there? See here for enabling logging: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

**Comment by gurusreekanth** [comment] 2017-03-28 10:44
Thank you Kyle (@kiiadi) for your response.

I have attached wire logs which were captured when querying for Reserved instances. Also, I have attached an image which shows the Reserved Instances present for my account. 

[aws-log.txt](https://github.com/aws/aws-sdk-java/files/875340/aws-log.txt)
![reservedinstances](https://cloud.githubusercontent.com/assets/5106461/24401202/0dab0920-13d1-11e7-8f7a-3657e04465ea.png)

**Comment by kiiadi** [comment] 2017-03-29 01:00
Looks like the `Region` scoped instance is not coming back from EC2 on the wire - so as I suspected this isn't an SDK issue. However it is quite odd, I've had a bit of a play around and wasn't able to reproduce. 

Is your EC2 client configured to point to the same region as those instances? I assume so but just figured I'd ask. Looks like a service issue and we'll have to reach out to them. Couple of avenues open for you to do that:

- Open a support case via the AWS console
- Post question on Stack-Overflow using the EC2 tag : http://stackoverflow.com/questions/tagged/amazon-ec2

Good luck!

**Comment by gurusreekanth** [comment] 2017-03-30 16:55
@kiiadi Yes client is point to the region of those instances. Again, thanks for the quick response. I have posted the below question on Stack-Overflow.
http://stackoverflow.com/questions/43123934/reserved-instances-with-scope-region

**Comment by kiiadi** [comment] 2017-04-18 20:55
@gurusreekanth the other option if you don't get any progress via stack-overflow (I've seen a few comments) - is to open a support case with the service team. You can do this inside the console.

As I said above, looking at the wire-logs you send the data isn't coming back from the service so it doesn't appear to be an SDK issue. I'm going to close this for now, please feel free to re-open if you feel this is a problem with the SDK itself.

**Closed by kiiadi** 2017-04-18 20:55 UTC
Labels: waiting-reply
