### ISSUE TITLE
DynamoDB Mapper wrongfully not persisting fields marked with JsonIgnore annotation

### ISSUE THREAD

**Issue by xoraes** [aws/aws-sdk-java#1253] opened 2017-07-26 03:31 UTC
We had a couple of fields marked with "@JsonIgnore" annotations and we were using version 1.11.5. DynamoMapper was successfully persisting those fields with mapper.save function - no issues. 

I upgraded to 1.11.166 and now the mapper doesn't save fields that are marked with "@JsonIgnore". We want dynamodb to only ignore fields we specifically annotate with "DynamoDBIgnore" annotation.

**Comment by shorea** [comment] 2017-07-26 14:38
Can you provide some sample code. The mapper shouldn't be looking at Jackson annotations at all unless you are using DynamoDBTypeConvertedJson.

**Comment by xoraes** [comment] 2017-07-26 15:55
`
import com.amazonaws.ClientConfiguration;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig.Builder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException;


public class DynamoDBDao {
    private static final Logger logger = LoggerFactory.getLogger(DynamoDBDao.class);
    private AmazonDynamoDB client = null;
    private DynamoDBMapper mapper = null;

    class Item {
        @DynamoDBHashKey(attributeName = "id")
        private String id;
        private String desc;
        @JsonIgnore
        public String getDesc() {
            return desc;
         }
        public void setDesc(String  desc) {
            this.desc = desc;
         }
    public DynamoDBDao(ApiConfig config) {
        client = AmazonDynamoDBClientBuilder.standard().build();
        DynamoDBMapperConfig mapperConfig = buildMapper().build();
        mapper = new DynamoDBMapper(client, mapperConfig);
    }

    public void upsertItem(Item item) {
        Optional<Item> existingItem = getItem(item.getId());
        if (existingItem.isPresent()) {
            item.setVersion(existingItem.get().getVersion());
        }
        try {
            mapper.save(item);
        } catch (ConditionalCheckFailedException e) {
            throw new ItemApiException(Response.Status.CONFLICT, ItemErrorCodes.internalError("multiple updates to same record at the same time"));
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
     protected Builder buildMapper() {
        return new DynamoDBMapperConfig.Builder()
                .withConsistentReads(DynamoDBMapperConfig.ConsistentReads.CONSISTENT)
                .withSaveBehavior(DynamoDBMapperConfig.SaveBehavior.UPDATE);
    }

}
`

**Comment by xoraes** [comment] 2017-07-26 16:04
@shorea the above is sample code - i removed things that cannot be public. Note we use lombok's @Getter{onMethod={@JsonIgnore}} annotation. This will put @JsonIgnore on the getter method of the field. When I have this annotation, dynamodb is not persisting the desc field.

**Comment by shorea** [comment] 2017-07-26 16:44
Hmm strange. Have you tried with a de-lomboked class?

**Comment by xoraes** [comment] 2017-07-26 18:11
I have not, but why would a lombok annotation that is used to annotate its generated getters with @jsonignore mess with dynamodb functionality?

**Comment by shorea** [comment] 2017-07-27 15:08
@xoraes I'm not sure but I was not able to reproduce this with a handwritten class. I suspect Lombok something is going on in the Lombok layer, can you de-lombok the class and paste it here?

**Comment by shorea** [comment] 2017-07-31 15:18
@xoraes Have you had a chance to try with a de-lomboked class?

**Comment by xoraes** [comment] 2017-08-01 23:11
No I have not. But I don't think there is any reason lombok could be affecting this.

**Comment by shorea** [comment] 2017-09-19 14:53
@xoraes are you still having problems with this?

**Comment by shorea** [comment] 2017-09-25 14:58
Closing issue, feel free to reopen if problem persists.

**Closed by shorea** 2017-09-25 14:58 UTC
Labels: Question
