### ISSUE TITLE
iam deleteRole not working

### ISSUE THREAD

**Issue by JavaTec** [aws/aws-sdk-java#2155] opened 2019-11-20 23:16 UTC
When com.amazonaws.services.identitymanagement.deleteRole(DeleteROleRequest) is invoked, it keeps complaining that all policies must be detached from the role before deletion. Whereas in reality, the policy has been detached. Its ocnfirmed by looking at console and by querying using cli. CLI also allows to delete the role, but not possible via java sdk: ttps://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iam/src/main/java/com/amazonaws/services/identitymanagement/AmazonIdentityManagement.java 
Exact error message:
[Request processing failed; nested exception is com.amazonaws.services.identitymanagement.m
odel.DeleteConflictException: Cannot delete entity, must detach all policies first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; Request ID: c6f1ea52-c480-4a66-bc02-c50c0b71ee84)] with root cause
com.amazonaws.services.identitymanagement.model.DeleteConflictException: Cannot delete entity, must detach all policies first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; Request ID: c6f1ea52-c480-4a66-bc02-c50c0b71ee84)

**Comment by JavaTec** [comment] 2019-11-21 16:53
Hi, is it possible to get an idea by when can someone from AWS SDK development team start to look into this issue? Thank you.

**Comment by KaibaLopez** [comment] 2019-11-22 00:34
Hi @JavaTec , sorry for the delayed response, I'm currently looking into this, will try and give you a solution, or work around, as soon as possible.

**Comment by JavaTec** [comment] 2019-11-22 21:33
Thank you KaibaLopez

**Comment by klaytaybai** [comment] 2019-11-25 22:01
Hi @JavaTec, we haven't been able to reproduce this problem once all policies have been detached.  How are you detaching the policies?  It sounds like you are verifying that they have been detached before trying to delete the role with the SDK:  is that right?  If you continue to have issues with this, please consider opening a case with Premium Support if you have it.  I don't think there is much the SDK team is going to be able to do to solve this problem.

**Comment by JavaTec** [comment] 2019-11-27 17:15
Sorry for the delayed reply. I was trying to detach the policy using the following code:
`
DetachRolePolicyRequest request = new DetachRolePolicyRequest().withRoleName("myRole").withPolicyArn("myPolicyArn");
DetachRolePolicyResult result = iamClient.detachRolePolicy(request);
`
To your question, yes i was detaching the policy first and then trying to delete the role. I had chatted with premium support and they tended to agree that this is a possible issue with SDK

**Comment by JavaTec** [comment] 2019-11-27 17:17
We found a workaround though - now we are no more using a managed policy, instead an inline policy and in that case we don't have to detach - it gets deleted as soon as role is deleted. But it would be nice to have the issue fixed with managed policy as well.

**Comment by JavaTec** [comment] 2019-11-27 17:18
I can provide case number if you need

**Comment by debora-ito** [comment] 2020-01-02 20:30
Glad you found a workaround and are not blocked anymore. 
I'll go ahead and close this, since you have a case opened with Premium Support. Feel free to reopen this if any other question come up.

**Closed by debora-ito** 2020-01-02 20:30 UTC
Labels: guidance, needs-repro
