### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset

### ISSUE THREAD

**Issue by akavijay** [aws/aws-sdk-java#2064] opened 2019-07-30 07:04 UTC
I am having an issue, we are using the same s3client object for delete and in TransferManager also to upload, I am not closing either of them. Is it good a practice to reuse the same s3client object, or need to create for each request and close when done?

**Comment by akavijay** [comment] 2019-07-30 07:04
aused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1807) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48) [aws-java-sdk-s3-1.11.475.jar:]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_181]

**Comment by debora-ito** [comment] 2019-07-31 21:44
Hi @akavijay yes, it is recommended to reuse the same client. 

Connection resets are likely due to networking issues. Are you seeing the error intermittently? Are you behind a proxy?

**Comment by akavijay** [comment] 2019-08-01 05:16
Hi @debora-ito 

Thank you for your reply.

Indeed we are behind the proxy, and we getting this error continuously even restarting the servers.
Let me give you the context what we trying to do. We have a highly transactional application, having two major operation upload and delete content from the AWS S3 bucket. 

We had a performance issue with single TransferManager and single s3Client. To fix that we created limited TransferManager object and associate with the same s3Client.

After some time we got the error  "Connection pool shut down".  Since then we are getting the error "Unable to execute HTTP request: Connection reset"

**Comment by debora-ito** [comment] 2019-08-05 23:25
So you may be seeing "Connection pool shut down" because something is closing the S3 client or shutting down your TransferManager before it finishes its work.

Could you share a code snippet showing how you're creating the s3 client and the TransferManager?

**Comment by debora-ito** [comment] 2019-08-13 17:06
Closing due to inactivity, feel free to reopen if you're still experiencing this issue.

**Closed by debora-ito** 2019-08-13 17:06 UTC
Labels: guidance, response-requested

**Comment by webartoli** [comment] 2020-02-13 11:39
Hi,
I'm hitting the same issue described on my laptop.

- When I'm on a connection whithout proxy there is all ok.
- When I'm behind a corporate HTTP gateway that rewrite the SSL chain (no proxy configured client side) I have the following error.

```
Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1134)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1080)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4384)
	at com.amazonaws.services.s3.AmazonS3Client.getS3AccountOwner(AmazonS3Client.java:932)
	at com.amazonaws.services.s3.AmazonS3Client.getS3AccountOwner(AmazonS3Client.java:922)
```

Obviously I have the same issue on `awscli` and python `boto3`, but I can configure the expected CA via environment variable `AWS_CA_BUNDLE` as described in the [official documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).

Is there any way to configure the same behaviour configured on `aws-sdk-java` ?

**Comment by srikanth550** [comment] 2020-05-26 13:10
Hi, I am having same as above. I am trying to load spring application config from s3. I am using Spring cloud config server and S3 as backend. Using proxy and ProfileCredentialsProvider. When it tries to connect to AWS S3, getting below exception.
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset
Please reopen this issue.

**Comment by debora-ito** [comment] 2020-05-26 22:33
@srikanth550 please open a new issue providing all the info about your use case, including reproducible code sample and stacktrace of the error.
