### ISSUE TITLE
Memory Leak with Tomcat undeploy/deploy

### ISSUE THREAD

**Issue by apptaro** [aws/aws-sdk-java#918] opened 2016-11-10 04:25 UTC
When Tomcat undeploys and deploys an application using aws-sdk-java, the following error appears:

```
catalina.log-20161110:09-Nov-2016 15:18:40.178 SEVERE [ajp-nio-8009-exec-14] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [com.amazonaws.auth SigningAlgorithm$1] (value [com.amazonaws.auth.SigningAlgorithm$1@4f7e1158]) and a value of type [javax.crypto.Mac] (value [javax.crypto.Mac@643f834a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
catalina.log-20161110:09-Nov-2016 15:18:40.178 SEVERE [ajp-nio-8009-exec-14] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [com.amazonaws.auth AbstractAWSSigner$1] (value [com.amazonaws.auth.AbstractAWSSigner$1@7bbd0de4]) and a value of type [java.security.MessageDigest.Delegate] (value [SHA-256 Message Digest from SUN, <initialized>

```
This is cased by ThreadLocal in com.amazonaws.auth.SigningAlgorithm and com.amazonaws.auth.AbstractAWSSigner.

**Comment by dagnir** [comment] 2016-11-11 21:28
Thank you for bringing this to our attention. We will look into it.

**Comment by shorea** [comment] 2016-11-12 02:38
From what I'm reading I don't think this is an issue. The problem with ThreadLocal only occurs when used with a class loaded by the web apps classloader which prevents the webapp classloader from being garbage collected when the app is unloaded. Since our use of ThreadLocal is confined to JVM classes which are loaded by the boot classloader it shouldn't be a problem. I'm going to close this issue but if you see evidence that we are preventing the web app classloader from being garbage collected feel free to reopen.

https://neilmadden.wordpress.com/2014/07/21/threadlocal-variables-and-permgen-memory-leaks-not-always-a-leak/

**Closed by shorea** 2016-11-12 02:38 UTC
Labels: Bug

**Comment by wilkowski** [comment] 2019-05-11 00:15
I've been trying to track down a memory leak on our tomcat system when deploying/undeploying servlets and it seems to be caused by building the AmazonDynamoDB client. I built a small test console and have been seeing a memory leak with every undeployment. On my http://localhost:8080/manager/html page, the 'Find leaks' button says that there is a memory leak with the servlet and I see a bunch of com.amazonaws classes sticking around in VisualVM after a deploy+undeploy. Though I'm not seeing the error message mentioned by apptaro.

The contextInitialized method of my ServletContextListener is:
`@Override`
`	public void contextInitialized(ServletContextEvent arg0) {`
`		// Using AmazonDynamoDBClientBuilder.defaultClient() doesn't seem to have any problems.`
`		AmazonDynamoDBClientBuilder clientBuilder = AmazonDynamoDBClientBuilder.standard().withRegion(Regions.US_WEST_2);`
`		AmazonDynamoDB client = clientBuilder.build(); // Everything is fine until this line`
`		// It doesn't seem to matter whether or not client.shutdown() is called`
`		client.shutdown();`
`	}`

My project is using maven with version 1.11.549 of aws-java-sdk-dynamodb and version 4.0.1 of javax.servlet-api.
