### ISSUE TITLE
Transfer manager throwing exeception before default connection timeout - 50 second

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java#1667] opened 2018-07-10 06:15 UTC
When application run, there is no n/w available and hence it should throw exception only after 50 sec.
It doesn't seem to honor that. 

>>>> I have two requirements: 
1. configure the amount of time client will wait for before initiating any upload(no network while starting app) 
If no n/w , client should come out of upload method.

2. when upload is under progress (25% completed), meantime n/w goes down , i want to configure the maximum time client will wait to comeout of upload method. 

Currently , i am unable to figure out, when n/w resumes, the upload also resumes. I want to get control over it to disrupt this after waiting for certain amount of time.

Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: myxyzbucket.s3-us-west-2.amazonaws.com
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3184)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.initiateMultipartUpload(UploadCallable.java:360)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInParts(UploadCallable.java:180)
        at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
        at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
        ... 4 more
Caused by: java.net.UnknownHostException: myxyzbucket.s3-us-west-2.amazonaws.com
        at java.net.InetAddress.getAllByName0(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
        at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy3.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1238)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
        ... 18 more

**Comment by MkJha** [comment] 2018-07-13 19:19
Any update on this? Really in need of this info!!

**Comment by zoewangg** [comment] 2018-07-13 19:42
Could you post a sample code of how you construct and use `TransferManager`?

Which version of SDK are you using?

**Comment by MkJha** [comment] 2018-07-13 19:57
AmazonS3Client s3Client = AmazonS3ClientBuilder.standard()
						.withEndpointConfiguration(new EndpointConfiguration(s3.us-west2.amazonws.com, us-west-2))
						.withCredentials(XXXXXXXXxx).withClientConfiguration(new ClientConfiguration).build();
						
						TransferManager transferManager = null;
		// build transfer manager to perform file upload
		transferManager = TransferManagerBuilder.standard().withS3Client(s3Client).build();
		if (transferManager != null) {
			try {
				upload = transferManager.upload(bucketName, objectName, localFile);
				if (upload != null) {
					txState = upload.getState().name();
					logger.info(TRANSFER_STATUS, pRemoteFileName, ARROW_SEPARATOR, txState);
					//show progress
						if (transfer != null) {
			                 TransferProgress progress = transfer.getProgress();
			               long total = progress.getTotalBytesToTransfer();
			            do {

							long transferred = progress.getBytesTransferred();
							double transferredPercentage = progress.getPercentTransferred();
							StringBuilder sb = new StringBuilder();
							if (transfer instanceof Upload) {
						sb.append("\r")
							.append(String.format(UPLOAD_DISPLAY_FORMAT, total, transferred, transferredPercentage));
						} else {
					sb.append("\r")
							.append(String.format(DOWNLOAD_DISPLAY_FORMAT, total, transferred, transferredPercentage));
					}
				System.out.print(sb.toString());
			} while (!transfer.isDone());
			System.out.println();
		   }
					//end of show progress
					upload.waitForCompletion();
					txState = upload.getState().name();
					logger.info(TRANSFER_STATUS, pRemoteFileName, ARROW_SEPARATOR, txState);
					if (TRANSFER_STATE_FAILED.equals(txState)) {
						throw new FileTransferException("File upload failed", null);
					}
				}
			} catch (AmazonClientException ex) {
				throw new FileTransferException("File upload failed", ex);
			} catch (InterruptedException ex) {
				logger.warn("Interrupted {}", ex);
				Thread.currentThread().interrupt();
			} finally {
				transferManager.shutdownNow(false);
			}

		}

**Comment by MkJha** [comment] 2018-07-13 19:58
<dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.347</version>
      <scope>compile</scope>
    </dependency>

**Comment by MkJha** [comment] 2018-07-13 20:01
I hope you are clear with my requirement: 

1. The most important one is : The upload process doesn't seem to aborted even though n/w is down for long time. I mean it should not be on infinitely.

2. In case no n/w from the begining , it should wait for sometime before aborting.

**Comment by zoewangg** [comment] 2018-07-13 21:02
By default, s3 client will retry the requests for up to three times, so it is possible that you see the process doesn't seem to be aborted after 50 seconds, If you want to abort the request, you can set the `clientExecutionTimeout`

https://github.com/aws/aws-sdk-java/blob/9aed6de206067a63f151155cf37dc0329073539d/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L1301-L1303

**Comment by zoewangg** [comment] 2018-07-13 21:38
I tried to reproduce the `UnknownHostException` by cutting off my network and the request failed immediately after three retries.

Did you find out the upload not aborting from the logs? Do you have timestamp in the logs?

**Comment by MkJha** [comment] 2018-07-16 13:45
I still didn't get clearly : if connection time out default value is 5o second, why the client is throwing UnknownHostException  before that ?

2. For the second question :: I found why it is happening. I am running do..while until transfer is not done. (for transfer progress). Point is done remains false infinitely so the loop runs infinitely. could you please check on this?

**Comment by MkJha** [comment] 2018-07-16 13:51
{
        // print the transfer's human-readable description
        System.out.println(xfer.getDescription());
        // print an empty progress bar...
        printProgressBar(0.0);
        // update the progress bar while the xfer is ongoing.
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                return;
            }
            // Note: so_far and total aren't used, they're just for
            // documentation purposes.
            TransferProgress progress = xfer.getProgress();
            long so_far = progress.getBytesTransferred();
            long total = progress.getTotalBytesToTransfer();
            double pct = progress.getPercentTransferred();
            eraseProgressBar();
            printProgressBar(pct);
        } while (xfer.isDone() == false);
        // print the final state of the transfer.
        TransferState xfer_state = xfer.getState();
        System.out.println(": " + xfer_state);
    }
similar way i am doing.

**Comment by MkJha** [comment] 2018-07-18 13:04
@shorea  : "isDone should not be hanging indefinitely, it should return when it completes either successfully or unsuccessfully."

It should, but is it really happening so ?  
It can be reproduced(as per code snippet i have shared above): 

1.  do a upload , after calling upload , call showProgress (method which runs do..while to show progress until its done). after that call waitForCompletion. 

Run the code when upload progress is in midway, stop the network connection, wait for sometime , you can see the program doesn't exit. In fact, If you enable network again , it resumes from the previous upload point.

**Comment by shorea** [comment] 2018-07-18 19:58
Can you describe how you stop the network connection so I can repro?

**Comment by MkJha** [comment] 2018-07-19 05:36
I just disabled the wi-fi of the system running the code. or we can plug off the LAN cable.

**Comment by dagnir** [comment] 2018-07-31 22:17
hi @MkJha 

I believe the reason that the you're not seeing a 50 second delay when there is not network is because DNS lookup is performed before the client attempts to connect to the resolved host. In this case the DNS lookup does not use connection timeout value, and the underlying `Socket` just throws the exception right away. The socket timeout in this case is only used once the DNS lookup was successful and the socket attempts to connect to the resolved host.

Here's a sample snippet to illustrate this:

```java
        Socket s = new Socket();
        s.setSoTimeout(50000);
        s.connect(new InetSocketAddress("somehost", 80));
```

I was able to reproduce the hang when the network cuts out while a download is in progress. Will continue to look into it.

**Comment by MkJha** [comment] 2018-07-31 23:39
As I mentioned  earlier if i just use waitForCompletion, it throws error .  You know when file is big(10 GB), it takes a while to get uploaded. In such cases if i network goes for few seconds, is there any way to control/configure that . Like wait for x minutes before it to get network on. I mean in absence of that, such large file would have to be uploaded again from the begining.

**Comment by dagnir** [comment] 2018-08-04 00:41
Hmm I'm not sure I understand the question. Are you asking if it's possible for the SDK to detected that S3 is unreachable and if so pause up load until S3 becomes reachable again?

**Comment by MkJha** [comment] 2018-08-04 12:49
Yes ...you gt it right.  Is that possible ? Because you can't afford to start upload from the begging . Some configuration to resume in case of minor intermittent network failure (for few seconds)

**Comment by MkJha** [comment] 2018-08-04 12:50
And for hang issue  any update ?

**Comment by shorea** [comment] 2018-08-20 04:58
I wasn't able to reproduce the hang, when I cut the wifi it eventually timed out (took some time 2-3 mins I believe). Can you try again and let me know if it doesn't time out after several minutes?

**Comment by MkJha** [comment] 2018-08-20 09:31
It happens only when you loop through the progress to print the upload progress. If you just use waitForCompletion, it doesn't happen. You can talk to @dagnir  , as he is able to reproduce. (he has commented in this thread above)

**Comment by shorea** [comment] 2018-08-29 22:17
I was able to reproduce and fix this issue. It will be included in the next release.

**Comment by shorea** [comment] 2018-08-29 22:19
I've marked this as a feature request for the resume on failure feature. It's unlikely we will have time to implement it though so a pull request is the best option to get it in the SDK.

**Comment by pradeepkathare** [comment] 2019-02-21 09:50
> As I mentioned earlier if i just use waitForCompletion, it throws error , It doesn't hang. You know when file is big(10 GB), it takes a while to get uploaded. In such cases if i network goes for few seconds/minuets, is there any way to control/configure that . Like wait for x minutes before it throws error. I mean in absence of that, such large file would have to be uploaded again from the beginning.

Hi MKJha,

I am also facing same issue.If you find solution can you help me to sort it.

**Comment by debora-ito** [comment] 2019-12-31 20:50
@MkJha 

the SDK team has reviewed the feature request list for V1 and decided not to implement this one, as they're concentrating efforts on V2 new features. It'll be considered for V2.

I'll go ahead and close this one, feel free to reach out if you have further questions.

**Closed by debora-ito** 2019-12-31 20:50 UTC
Labels: feature-request
