### ISSUE TITLE
Unable to upload files to s3 with ec2 instance

### ISSUE THREAD

**Issue by dk2n** [aws/aws-sdk-java#980] opened 2017-01-10 18:49 UTC
In my web app, I has to upload product image to s3 and store the returned URL to RDS for later use. 

The pseudo code is:

```
void uploadProduct(...) {
  synchronized(this)
    verify_product_title;
    verify_product_price;
    upload_product_image;    // upload to s3 process
    persist_product;                // persist product info to DB
  }
}
```
So the problem is that I got an error while persist the product the database due to missing product_image_path.

So far, I checked the S3 bucket, and don't see the image file uploaded. Hence, I assume that the file uploading process was not completed before the persistence process.

And I also detected that if I upload the image through EC2 instance, I will have this problem. And if I run the code on localhost, then the code will process in order, and the product will be persisted. 

I also checked that my EC2 instances are attached IAM role, so permission should not be a problem.

I have no idea how this problem occurs. If any one have this code behavior before, please suggest where I should to look for to fix this problem. Thanks!

**Comment by zhangzhx** [comment] 2017-01-10 21:22
Hey @dk2n,

What SDK version you are using? Are you uploading content to S3 bucket the same region to the underlying EC2 instance? Can you show me some sample code to reproduce this issue and post the error log (exception trace) if possible?

**Comment by dk2n** [comment] 2017-01-11 07:10
Hey @zhangzhx 

- I am using SDK 1.11.22. 
- Yes, the S3 bucket and EC2 instance are in the same region. 
- I checked elasticbeanstalk-access_log and elasticbeanstalk-error_log and found no problem; while the catalina.out shows stack trace error that persisting a product need the product image. So the only assumption that I can come up is that somehow I cannot upload the image to the S3 bucket due to invalid permission probably

Here is the stack trace error:

`java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.common.util.file.FileUtil.convert(FileUtil.java:17)
	at com.core.amazon.bucket.S3MultipartUpload.uploadProduct(S3MultipartUpload.java:142)
	at com.web.controller.page.listing.NewListingPageController.getDisplayImage(NewListingPageController.java:183)
	at com.web.controller.page.listing.NewListingPageController.createNewListing(NewListingPageController.java:163)`


I checked my EC2 instances and see that they have already attached to an IAM role which has AdministratorAccess permission. 

Here is the code I use to upload file to S3 bucket:

```

private String upload(String bucketName, String keyName, File file) {
		AmazonS3 s3Client = new AmazonS3Client(AmazonUtil.getAwsCredentials());       
		String imageName = this.formatImage(keyName);
		
        // Create a list of UploadPartResponse objects. You get one of these
        // for each part upload.
        List<PartETag> partETags = new ArrayList<PartETag>();

        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new 
             InitiateMultipartUploadRequest(bucketName, imageName);
        InitiateMultipartUploadResult initResponse = 
        	                   s3Client.initiateMultipartUpload(initRequest);

        long contentLength = file.length();
        long partSize = 5242880; // Set part size to 5 MB (5*1024*1024).

        try {
            // Step 2: Upload parts.
            long filePosition = 0;
            for (int i = 1; filePosition < contentLength; i++) {
                // Last part can be less than 5 MB. Adjust part size.
            	partSize = Math.min(partSize, (contentLength - filePosition));
            	
                // Create request to upload a part.
                UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucketName).withKey(imageName)
                    .withUploadId(initResponse.getUploadId()).withPartNumber(i)
                    .withFileOffset(filePosition)
                    .withFile(file)
                    .withPartSize(partSize);

                // Upload part and add response to our list.
                partETags.add(
                		s3Client.uploadPart(uploadRequest).getPartETag());

                filePosition += partSize;
            }

            // Step 3: Complete.
            CompleteMultipartUploadRequest compRequest = new 
                         CompleteMultipartUploadRequest(
                                    bucketName, 
                                    imageName, 
                                    initResponse.getUploadId(), 
                                    partETags);

            s3Client.completeMultipartUpload(compRequest);
            s3Client.setObjectAcl(bucketName, imageName, CannedAccessControlList.PublicRead);
        } catch (Exception e) {
            s3Client.abortMultipartUpload(new AbortMultipartUploadRequest(
                    bucketName, imageName, initResponse.getUploadId()));
            return null;
        }
        return getPublishPath(bucketName, imageName);
	}
```

**Comment by davebozz** [comment] 2017-01-30 22:28
@dk2n Hey dk2n, are your credentials stores locally on your machine (if *nix ~/.aws)? Can you create a bucket, store anything in a bucket, etc... using the AWS CLI?

**Comment by zhangzhx** [comment] 2017-02-07 02:43
Hey @dk2n,

Sorry for the late response. Did you resolved the issue? It seemed like it is not related to AWS permissions. From the error message, it seems that you were creating some file under a folder you don't have permission to write. [Here](http://stackoverflow.com/questions/14131324/permission-denied-file-creation-in-java) is a similar issue and the reason is because the user doesn't have write permission to the target folder. Can you double check where you wanted to create the file and make sure you have the permission?

**Comment by zhangzhx** [comment] 2017-04-11 21:53
Hey @dk2n ,

Do you still see this issue? I'm closing this issue since it's been a while. Feel free to reopen it if you still have questions about this.

**Closed by zhangzhx** 2017-04-11 21:53 UTC
Labels: waiting-reply
