### ISSUE TITLE
S3 Java SDK not working with Mule

### ISSUE THREAD

**Issue by raghukaramel** [aws/aws-sdk-java#1135] opened 2017-04-28 18:13 UTC
I am building an application in Mule that uploads file to S3 using Java SDK and initialization of AmazonS3Client is failing at runtime. I am using Mule Enterprise Edition 3.4.0, Java 1.7 and S3 SDK 1.11.106. 

Here is the code that I am using... any suggestions?

package com.intuit.s3.test;

import org.mule.api.MuleMessage;
import org.mule.api.transformer.TransformerException;
import org.mule.transformer.AbstractMessageTransformer;

import java.io.File;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.PutObjectRequest;

public class S3FileUpload extends AbstractMessageTransformer {
	private static String bucketName     = "my-bucket-test123";
	private static String keyName        = "java-sdk-test-upload.txt";
	private static String uploadFileName = "/tmp/s3-upload-test.txt";

	@Override
	public Object transformMessage(MuleMessage message, String outputEncoding) throws TransformerException {
		DefaultAWSCredentialsProviderChain awsCredentialsProviderChain = new DefaultAWSCredentialsProviderChain();
		AmazonS3 s3Client = new AmazonS3Client(awsCredentialsProviderChain.getCredentials());
        try {
            System.out.println("Uploading a new object to S3 from a file\n");
            File file = new File(uploadFileName);
            s3Client.putObject(new PutObjectRequest(bucketName, keyName, file));

         } catch (AmazonServiceException ase) {
            System.out.println("Caught an AmazonServiceException, which " +
            		"means your request made it " +
                    "to Amazon S3, but was rejected with an error response" +
                    " for some reason.");
            System.out.println("Error Message:    " + ase.getMessage());
            System.out.println("HTTP Status Code: " + ase.getStatusCode());
            System.out.println("AWS Error Code:   " + ase.getErrorCode());
            System.out.println("Error Type:       " + ase.getErrorType());
            System.out.println("Request ID:       " + ase.getRequestId());
        } catch (AmazonClientException ace) {
            System.out.println("Caught an AmazonClientException, which " +
            		"means the client encountered " +
                    "an internal error while trying to " +
                    "communicate with S3, " +
                    "such as not being able to access the network.");
            System.out.println("Error Message: " + ace.getMessage());
        }
		return null;
	}

}

**Comment by kiiadi** [comment] 2017-04-28 21:13
What's the problem you're seeing?

**Comment by raghukaramel** [comment] 2017-04-28 21:52
It hangs at line - AmazonS3 s3Client = new AmazonS3Client(awsCredentialsProviderChain.getCredentials());

I don't see any error or any messages

**Comment by kiiadi** [comment] 2017-04-28 23:27
Where are you expecting credentials to be loaded from?

**Comment by kiiadi** [comment] 2017-04-28 23:28
Sorry, I'm not that familiar with mule.

**Comment by raghukaramel** [comment] 2017-04-28 23:28
~/.aws/credentials

**Comment by raghukaramel** [comment] 2017-04-28 23:30
No I am running it on my local. Mule is a spring based application container - more info can be found here - https://www.mulesoft.com/platform/mule

**Comment by kiiadi** [comment] 2017-04-28 23:32
Can you try this:

```java
AmazonS3 s3 = AmazonS3Client.builder().withCredentials(new ProfileCredentialsProvider()).build();
```

**Comment by raghukaramel** [comment] 2017-04-28 23:36
I tried that and couple other ways to create S3Client, but all of them fail the same way. Here are the different things I tried


		//BasicAWSCredentials awsCreds = new BasicAWSCredentials("abc", "xyz");
		//AmazonS3 s3Client = new AmazonS3Client(awsCreds);

		//AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentialsProviderChain.getCredentials())).build();

  		//AmazonS3 s3Client = new AmazonS3Client(new ProfileCredentialsProvider());

**Comment by kiiadi** [comment] 2017-04-28 23:49
have you been able to step through to see where it's hanging?

**Comment by raghukaramel** [comment] 2017-04-28 23:55
Yes, when I am stepping through the code, the cursor disappears for few seconds on the above line of code and then the control get transferred to line 76 of the below code - 
/*
 * $Id$
 * --------------------------------------------------------------------------------------
 *
 * (c) 2003-2010 MuleSoft, Inc. This software is protected under international copyright
 * law. All use of this software is subject to MuleSoft's Master Subscription Agreement
 * (or other master license agreement) separately entered into in writing between you and
 * MuleSoft. If such an agreement is not in place, you may not use the software.
 */
package org.mule.execution;

import org.mule.api.MessagingException;
import org.mule.api.MuleEvent;
import org.mule.api.MuleException;
import org.mule.api.construct.FlowConstruct;
import org.mule.api.construct.Pipeline;
import org.mule.api.processor.MessageProcessor;
import org.mule.context.notification.MessageProcessorNotification;
import org.mule.context.notification.ServerNotificationManager;

/**
 * Intercepts MessageProcessor execution to fire before and after notifications
 */
class MessageProcessorNotificationExecutionInterceptor implements MessageProcessorExecutionInterceptor
{

    private MessageProcessorExecutionInterceptor next;

    MessageProcessorNotificationExecutionInterceptor(MessageProcessorExecutionInterceptor next)
    {
        this.next = next;
    }

    MessageProcessorNotificationExecutionInterceptor()
    {

    }


    @Override
    public MuleEvent execute(MessageProcessor messageProcessor, MuleEvent event) throws MessagingException
    {
        ServerNotificationManager notificationManager = event.getMuleContext().getNotificationManager();
        boolean fireNotification = event.isNotificationsEnabled();
        if (fireNotification)
        {
            fireNotification(notificationManager, event.getFlowConstruct(), event, messageProcessor,
                             null, MessageProcessorNotification.MESSAGE_PROCESSOR_PRE_INVOKE);
        }

        MuleEvent result = null;
        MessagingException exceptionThrown = null;
        try
        {
            if (next == null)
            {
                result = messageProcessor.process(event);
            }
            else
            {
                result = next.execute(messageProcessor, event);
            }
        }
        catch (MessagingException e)
        {
            exceptionThrown = e;
            throw e;
        }
        catch (MuleException e)
        {
            exceptionThrown = new MessagingException(event, e, messageProcessor);
            throw exceptionThrown;
        }
        finally
        {
            if (fireNotification)
            {
                fireNotification(notificationManager, event.getFlowConstruct(), result != null ? result : event, messageProcessor,
                                 exceptionThrown, MessageProcessorNotification.MESSAGE_PROCESSOR_POST_INVOKE);
            }
        }
        return result;
    }

    protected void fireNotification(ServerNotificationManager serverNotificationManager, FlowConstruct flowConstruct, MuleEvent event, MessageProcessor processor, MessagingException exceptionThrown, int action)
    {
        if (serverNotificationManager != null
            && serverNotificationManager.isNotificationEnabled(MessageProcessorNotification.class))
        {
            if (flowConstruct instanceof Pipeline && ((Pipeline) flowConstruct).getProcessorPath(processor) != null)
            {
                serverNotificationManager.fireNotification(new MessageProcessorNotification(flowConstruct, event, processor, exceptionThrown, action));
            }
        }
    }
}

**Comment by kiiadi** [comment] 2017-04-29 00:02
I'm sorry, I don't see line numbers. Can you link me to a line in the repo? What version of the SDK are you using?

**Comment by raghukaramel** [comment] 2017-04-29 00:11
Here is the repo link - https://github.com/mulesoft/mule/blob/mule-3.4.1-HF1/core/src/main/java/org/mule/execution/MessageProcessorNotificationExecutionInterceptor.java

I am currently using AWS S3 SDK 1.11.106, I also tried the latest version 1.11.124 and few other older versions as well 1.10.x, 1.9.x etc. I am seeing the same behavior with all different versions.

**Comment by kiiadi** [comment] 2017-04-29 00:13
This looks like mule code - I'm looking for what part of the SDK you feel this is a problem with...

**Comment by raghukaramel** [comment] 2017-04-29 00:14
not sure about... that's where I am looking for help

**Comment by kiiadi** [comment] 2017-04-29 01:33
This repo is for the Aws Java SDK, the code you've posted isn't from our library. Have you tried asking in the mule repository? I'm unsure how else I'm able to help as you indicate the problem is not with the AWS Java SDK.

**Comment by raghukaramel** [comment] 2017-05-01 18:51
I agree, it looks like a Mule issue. I have opened a case with Mule and working with them currently.

**Comment by kiiadi** [comment] 2017-05-02 16:21
Closing this for now, feel free to re-open if you feel this is an issue with the SDK.

**Closed by kiiadi** 2017-05-02 16:21 UTC
Labels: Question
