### ISSUE TITLE
The error message for "com.amazonaws.SdkClientException: Unable to create HTTP entity" is "null"

### ISSUE THREAD

**Issue by JiachengYang2020** [aws/aws-sdk-java#2440] opened 2020-10-21 13:39 UTC
## Describe the bug

In production, our server failed to create a new file in the S3 bucket. In typical cases, there are usually detailed error messages accompanying the "com.amazonaws.SdkClientException: Unable to create HTTP entity: xxx" exception, like "timeout" or "reset" etc. But for this one, its additional information is null. 

## Expected Behavior

the "xxx" part of ""com.amazonaws.SdkClientException: Unable to create HTTP entity: xxx" should always be valid

## Current Behavior

full stakctrace

`Could not create file for file 'redacted.doc' with ID '-redacted' on S3 bucket 'redacted' com.amazonaws.SdkClientException: Unable to create HTTP entity: null.
   STACKTRACE:
   com.amazonaws.http.apache.utils.ApacheUtils.newBufferedHttpEntity(ApacheUtils.java:119)
   com.amazonaws.http.apache.request.impl.ApacheHttpRequestFactory.createHttpEntityForNonPostVerbs(ApacheHttpRequestFactory.java:225)
   com.amazonaws.http.apache.request.impl.ApacheHttpRequestFactory.wrapEntity(ApacheHttpRequestFactory.java:186)
   com.amazonaws.http.apache.request.impl.ApacheHttpRequestFactory.createApacheRequest(ApacheHttpRequestFactory.java:142)
   com.amazonaws.http.apache.request.impl.ApacheHttpRequestFactory.create(ApacheHttpRequestFactory.java:94)
   com.amazonaws.http.apache.request.impl.ApacheHttpRequestFactory.create(ApacheHttpRequestFactory.java:51)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor$ExecOneRequestParams.newApacheRequest(AmazonHttpClient.java:1858)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1278)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
   com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
   com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
   com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
   com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
   com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
   com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
   com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
   com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5801)
   com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1789)
   com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
   com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1687)
   com.caseware.simpleengagement.server.tb.stores.eng.S3FileStorage.createFile(S3FileStorage.java:60)
   com.caseware.simpleengagement.server.tb.stores.eng.DatabaseFileRepository.createFile(DatabaseFileRepository.java:254)
   com.caseware.simpleengagement.server.tb.stores.eng.DatabaseFileRepository.createFile(DatabaseFileRepository.java:243)
   com.caseware.simpleengagement.server.tb.stores.eng.FileRepository.createFile(FileRepository.java:92)
   com.caseware.simpleengagement.server.webdav.ObjectResourceRoot.write(ObjectResourceRoot.java:137)
   com.caseware.simpleengagement.server.webdav.WebdavServlet.doPut(WebdavServlet.java:813)
   javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
   com.caseware.simpleengagement.server.webdav.WebdavServlet.service(WebdavServlet.java:344)
   javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
   com.caseware.simpleengagement.server.service.PathServiceImpl.serviceObjectContent(PathServiceImpl.java:1146)
   com.caseware.simpleengagement.server.service.PathServiceImpl.serviceStatic(PathServiceImpl.java:589)
   com.caseware.simpleengagement.server.service.PathServiceImpl.service(PathServiceImpl.java:396)
   javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
   org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
   com.caseware.simpleengagement.server.service.PathServiceFilter.doFilter(PathServiceFilter.java:42)
   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
   com.caseware.simpleengagement.server.service.PermissionServiceFilter.doFilter(PermissionServiceFilter.java:44)
   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
   org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
   org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
   org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
   org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
   org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1156)
   org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
   org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   java.lang.Thread.run(Thread.java:748)`

## Steps to Reproduce

not sure how to reproduce since there is no way to tell what the actual cause of the exception was 

## Possible Solution

I guess it's more like a minor improvement to the logging

## Context

We are trying to determine what actually happened with this user's operation's error, and right now there is no way for us to tell that

## Your Environment

* AWS Java SDK version used: 1.11.587
* JDK version used: Java 8 
* Operating System and version: not relevant in this case i think

**Comment by debora-ito** [comment] 2020-11-02 22:56
Hi @JiachengYang2020 it seems the exception is not caused by general connectivity problems but trying to create a new BufferedHttpEntity:

https://github.com/aws/aws-sdk-java/blob/ff226f81bcc59addb955dd6e319b9f6460b4a55c/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/utils/ApacheUtils.java#L111-L121

I know this doesn't help a lot in the investigation of a cause for the exception. Are you seeing this `Unable to create HTTP entity: null` constantly? Is there anything special about the file you're trying to upload to S3?

**Comment by JiachengYang2020** [comment] 2020-11-09 23:11
@debora-ito hi, sorry for the late reply. 

No, I dont think this happens that often and so far, we havent identified any user impact issue that is associated with logs like this. My original intention for this ticket is that it would be nice to have some log improvements for this case.

**Comment by debora-ito** [comment] 2024-06-20 02:07
@JiachengYang2020

I apologize but we didn't have the chance to troubleshoot this further and improve the logs. We are closing old v1 issues before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so if this issue still persists in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)

**Closed by debora-ito** 2024-06-20 02:07 UTC
Labels: bug, p2
