### ISSUE TITLE
Java SDK issue downloading file from S3

### ISSUE THREAD

**Issue by SrinivasCengage** [aws/aws-sdk-java#935] opened 2016-12-08 20:09 UTC
Hi,

I am using AWS java sdk to download files from s3.
code works fine when I ran it as stand alone java program and able download files.
Issues is when I try to ran the same code through weblogic server (i.e deployed on weblogic server) its looking for certificates . Do we need any certificates ?

"As per documentation Java versions 1.7 or newer are packaged with updated certificates and are unaffected by this issue."

My java version - 1.7.0_79

Can some one help me to resolve this issue.

Error
-----
Below is the error -

throws java.io.IOException" resulted in exception: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by SrinivasCengage** [comment] 2016-12-08 21:36
SDK Version - 1.11.60

**Comment by varunnvs92** [comment] 2016-12-09 19:52
There were some old issues regarding similar issue:
https://github.com/aws/aws-sdk-java/issues/833
https://github.com/aws/aws-sdk-java/issues/319

Can you see if suggestions in these links work?

If not, can you give me steps on how to reproduce this issue? Thanks.

**Comment by SrinivasCengage** [comment] 2016-12-12 20:52
Hi varun,

I was able to resolve SSL cert issue.
Now I am seeing the below . I read some blogs regarding this error  and there is an older version of Joda jar on weblogic server class path  which is causing this issue.
I have tried including dependency jars in my code but still see same error.
Any idea how to resolve this issue on Oracle weblogic application server 12c

Caused by: java.lang.NoSuchMethodError: org.joda.time.format.DateTimeFormatter.withZoneUTC()Lorg/joda/time/format/DateTimeFormatter;
               at com.amazonaws.auth.internal.AWS4SignerUtils.<clinit>(AWS4SignerUtils.java:27)
               at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:86)
               at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:205)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1089)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
               at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4031)
               at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3973)
               at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:778)
               at com.amazonaws.samples.S3Sample.downloadFile(S3Sample.java:179)
               ... 147 more

Regards,
Srinivas

**Comment by varunnvs92** [comment] 2016-12-13 18:13
If you are using maven, you can explicitly override the joda-time version to v2.8.1 which is used by the SDK.

**Comment by SrinivasCengage** [comment] 2016-12-13 19:00
Yes I have done that and its working good now.
Still there is some error thrown by Joda time but it is not a blocker now.

**Comment by SrinivasCengage** [comment] 2016-12-13 19:00
Thanks for your help.

From: Pusa, Srinivas
Sent: Tuesday, December 13, 2016 2:00 PM
To: 'aws/aws-sdk-java' <reply@reply.github.com>
Subject: RE: [aws/aws-sdk-java] Java SDK issue downloading file from S3 (#935)

Yes I have done that and its working good now.
Still there is some error thrown by Joda time but it is not a blocker now.

**Comment by varunnvs92** [comment] 2016-12-13 19:26
Good to hear that its working now.

>>Still there is some error thrown by Joda time but it is not a blocker now.
I will keep the ticket open for now in case the Joda time issue is due to Java SDK. If it is not, feel free to close the issue.

**Comment by varunnvs92** [comment] 2016-12-16 22:20
Feel free to reopen if you have followup questions. Thank you.

**Closed by varunnvs92** 2016-12-16 22:20 UTC
