### ISSUE TITLE
XMLStreamExceptions should be in the Default Retry Policy

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#892] opened 2016-10-15 18:23 UTC
Sometimes, under load or with large network latency there is an issue where a request can get a `javax.xml.stream.XMLStreamException: ParseError at [row,col]:[22125,15]
Message: Read timed out` resulting in an `AmazonClientException`. This are typically transient issues but unfortunately the default retry policy does not have a match for them. This should be added to the default retry condition so it can be allowed to retry. 

The exception is rare but can show up like this:

```
com.amazonaws.AmazonClientException: Unable to unmarshall response (ParseError at [row,col]:[22125,15]
Message: Read timed out). Response Code: 200, Response Text: OK
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1452) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1135) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:948) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:661) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:635) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:618) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:586) ]
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:573) ]
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:445) ]
  at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:10791) ]
  at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10767) ]
  at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5190) ]
```

**Comment by kiiadi** [comment] 2016-10-15 18:44
One of the issues with retrying in this situation is we've already received a response from the service - we'd need to understand if the operation was idempotent before retrying.

For the `describeInstance` call in your example obviously a retry would be fine because that operation does not cause any mutation - but the same is not true for all operations.

**Comment by rdifalco** [comment] 2016-10-15 18:50
How great would it be to have a flag in your `ExecutionContext` indicating if the  request was idempotent or not? Then you could retry all manner of parse or other read-timeout exceptions.

**Comment by kiiadi** [comment] 2016-10-15 19:01
It's probably something we want to have on the operation itself - we're working with service teams to better document operations that are idempotent we can then use this information in the SDK's. At the moment we don't have this visibility; we'll retry certain error codes from services (mostly 500s) but if we've received a 200 response then we can't safely know when a retry can be done.

In the short-term we could potentially add something to the base request object that allowed SDK users to specify that a given operation is idempotent in their context - it still puts the onus on the end-user to determine (although the SDK could handle the retry).

**Comment by rdifalco** [comment] 2016-10-15 19:15
Good suggestion. Just a vote that if you add it to the `AmazonWebServiceRequest` as a short term fix then I wouldn't call it anything to do with idempotency. Probably a method like `request.setResponseProcessingErrorRetryable` (or something like that) would be a better name. If this flag is set then you can retry any response streaming/connection error on a 200. That matches desired behavior rather than the possible incorrect interpretation of the idempotent semantics. 

Personally, I wouldn't see it as a huge inconvenience to add this to my requests, for example a DynamoDB query call or describeInstances call.  It's much better for me than having to do additional retry blocks around the internal retry logic with this logic copied around as needed.

**Comment by kiiadi** [comment] 2016-10-15 19:21
What if it was a method that took a predicate something like:

`setRetryablePredicate(Predicate<AmazonServiceException> shouldRetry)`

This would allow customers maximum flexibility to define when a retry should happen without having to worry about the mechanics of the retry itself.

**Comment by rdifalco** [comment] 2016-10-15 19:24
I think that would be great for people like me but for others it would force them to understand what type of response processing errors there could be (and there could be quite a few). Maybe if you had predefined predicates like `RetryOnSuccessfulResponseProcessing` or something like that. Also, as a `setRetryablePredicate` method it becomes a little more murky if this augments or overrides the `ClientConfiguration`'s `RetryPolicy`.

**Comment by kiiadi** [comment] 2016-10-15 19:30
Yes, it's less about "should retry" and more "is this exception retryable" - I'll try to come up with a name that better shows the intent.

I like the idea of having some pre-canned predicates.

**Comment by rdifalco** [comment] 2016-10-15 19:48
You may have already considered this but another option that does not require any new constructs would be the ability to set a `RetryPolicy` on the request. Then you could have a predefined instance that retries properly for idempotent calls. The `RetryPolicy` on the request would take precedence over the one the `ClientConfiguration`. So it would be a complete `RetryPolicy`. I'm ambivalent on which you prefer, this is just an additional idea.

**Comment by fernomac** [comment] 2016-10-16 17:36
FWIW the ship has already sailed on idempotency, since the SDK retries on timeouts. Could be the service was *just* about to send you a 200, or already did but it got lost on the way. Most operations are idempotent, or at least give a reasonable "this thing already exists" exception, so it works out okay most of the time. 
(I think just a couple in EC2 that didn't take an idempotency token yet and DDB updates depending on the update, as of when I left?)

If you're going to have service teams mark operations, have them mark the ones that are not idempotent (and ask them to think *really* hard about whether they can be made idempotent instead). Placing the burden of figuring out what to do in case of a timeout on the caller is sad.

**Comment by rdifalco** [comment] 2017-03-12 17:03
See #1068. This kinda sucks. If you could pass this on to the RetryPolicy you could choose to ignore it in your default handler, but right now there is NO solution to this problem other than writing another layer of try..catch within a for..next loop around every Amazon Client call. Not really acceptable.

I argue that this is not a feature request but a bug.

**Comment by dagnir** [comment] 2017-03-21 21:55
#1068 fixed this issue by wrapping `XMLStreamException`s in `IOException` if they were caused by an IOE. Resolving this.

**Closed by dagnir** 2017-03-21 21:55 UTC
Labels: Feature Request

**Comment by ikornachevska-branch** [comment] 2018-12-05 18:20
Is there any other way to avoid this?
