### ISSUE TITLE
Getting InvalidLocationConstraint while creating the bucket

### ISSUE THREAD

**Issue by vagdevipedalenka** [aws/aws-sdk-java#1466] opened 2018-02-12 09:21 UTC
Please help me to solve this issue,

I am getting following error while creating the bucket.
Code: Create bucket in US_EAST_1 region
AmazonS3Client m_s3Client;
CreateBucketRequest obj = new CreateBucketRequest("example_bucket");
Bucket bucket = m_s3Client.createBucket(obj);

Note: I am not passing the region name while creating the bucket:

Error:
CreateBucket - com.amazonaws.services.s3.model.AmazonS3Exception: The specified location constraint is not valid. For more information about Regions, see How to Select a Region for Your Buckets. (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 1647771648), S3 Extended Request ID: null

**Comment by dagnir** [comment] 2018-02-12 18:24
Hi @vagdevipedalenka, what version of the SDK are you using? Can you provide a full code example (including how you're constructing the client) that reproduces this issue?

**Comment by vagdevipedalenka** [comment] 2018-02-19 13:05
Hi @dagnir, currently I am using aws- sdk-1.11.116 and http -client4.5.2.

Code I am using for creating bucket:
CreateBucketRequest obj = new CreateBucketRequest("BucketName");
			//As per AWS documentation region should not be set for the Region Virginia this needs to be empty
			if(!m_Region.getName().equalsIgnoreCase("us-east-1"))
			{
				obj.setRegion(m_Region.getName());	
				Bucket bucket = m_s3Client.createBucket(obj); 
			}
			else
			{
				Bucket bucket = m_s3Client.createBucket("BucketName"); 
			}


This is perfectly working fine for Amazon S3 cloud account(able to create bucket in us_east_1), but not working for Amazon S3 compatible cloud account.

If I use the below condition, then I am able to create bucket in Amazon S3 compatible cloud account, but as per API documentation, we should not set the region for default region.
if(m_Region.getName().equalsIgnoreCase("us-east-1"))
			{
				obj.setRegion(m_Region.getName());	
				Bucket bucket = m_s3Client.createBucket(obj); 
			}


Can you please let me know exact behaviour?

Thanks,
Vagdevi

**Comment by dagnir** [comment] 2018-02-20 16:57
> but not working for Amazon S3 compatible cloud account.

Can you explain what you mean by "Amazon S3 compatible cloud account"? Is this a service that exposes an S3-compatible API?

**Comment by janaurka** [comment] 2018-04-03 15:38
We are facing this issue as well. Using Ceph RadosGW (Luminous Release): http://docs.ceph.com/docs/master/radosgw/s3/

**Comment by janaurka** [comment] 2018-04-04 16:08
Oh, apparently our devs used a deprecated way to try to create an s3 bucket. That solved it for them: https://stackoverflow.com/questions/47769300/java-aws-sdk-the-specified-location-constraint-is-not-valid-non-amazon?rq=1 

Always fun when `infra` guys tell the `devs` on how to do code :D

**Comment by shorea** [comment] 2018-04-12 20:48
Looks like the issue has been fixed. Closing.

**Closed by shorea** 2018-04-12 20:48 UTC
Labels: Question, waiting-reply
