### ISSUE TITLE
Region.isServiceSupported(AmazonEKS.ENDPOINT_PREFIX) returns false always!!

### ISSUE THREAD

**Issue by anilcs81** [aws/aws-sdk-java#2208] opened 2020-01-31 22:11 UTC
It is observed that region.isServiceSupported(AmazonEKS.ENDPOINT_PREFIX) is returning false for all regions.

In another way,
RegionUtils.getRegionsForService(AmazonEKS.ENDPOINT_PREFIX)) is returning empty list

**Comment by debora-ito** [comment] 2020-02-03 18:00
Hi @anilcs81 that's because EKS data is not present in the [endpoints.json](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json) file. 

This is a duplicate of #1766, let's keep track of this issue over there. I'll reach out to the service team and ask for an update.

**Closed by debora-ito** 2020-02-03 18:00 UTC
Labels: duplicate, service-api

**Comment by anilcs81** [comment] 2020-02-03 21:05
But the other issue is open for a while now.. It seems to be quick fix .

**Comment by debora-ito** [comment] 2020-02-03 22:18
The endpoints.json is auto-generated, the info must be added upstream by each service team. I'll reach out to the EKS team again.
