### ISSUE TITLE
AWS S3 Client throws Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by sballa12** [aws/aws-sdk-java#1212] opened 2017-06-28 15:49 UTC
We recently changed our AWS S3 Client instantiation to use aws-java-sdk version 1.1.150 in order to use the AWS recommended Default Region Provider Chain, following details in http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

The S3 client is instantiated as follows:
AwsS3ClientBuilder.standard().withForceGlobalBucketAccessEnabled(true).build();

We are seeing a large number errors as below when getting objects from S3 using this client.

Exception stack trace:

com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168)
		at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1378)

We did some further analysis on our side and were able to conclude the following:

(1) Using aws-java-sdk version 1.10.54, and creating S3 client using the constructor as follows does NOT exhibit any exceptions/errors when calling getObject() on the client. This was the version that we were using before upgrading. Code used for creating client and get object:

AmazonS3 s3Client = new AmazonS3Client();
S3Object object = s3Client.getObject(new GetObjectRequest(bucketName, key));

(2) Using aws-java-sdk version 1.11.150, and using the code snippet same as above (creating S3 client using the constructor), we see the exception.

(3) Using aws-java-sdk version 1.11.150, and creating S3 client using the Client Builder (as recommended in your docs), we see the exception. Code used for creating client and get object:

AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withForceGlobalBucketAccessEnabled(true).build();
S3Object object = s3Client.getObject(new GetObjectRequest(bucketName, key));

Please review and advise.

**Comment by dagnir** [comment] 2017-06-28 16:15
@sballa12 Can you you please provide [wire logs](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) so we can see the request the client is making? Please ensure you remove any sensitive information.

**Comment by dagnir** [comment] 2017-06-28 16:16
Also is it just GET object that fails? Do other operations like list buckets work?

**Comment by sballa12** [comment] 2017-06-28 18:29
Adding wire log of a failed request to get object here:

2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "GET kkk HTTP/1.1[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "Host: bbb.s3.amazonaws.com[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "Authorization: AWS4-HMAC-SHA256 Credential=ccc/20170628/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=sss[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "X-Amz-Date: 20170628T174112Z[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "User-Agent: aws-sdk-java/1.11.150 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.40-b25/1.8.0_40[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "amz-sdk-invocation-id: yyy[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "amz-sdk-retry: 0/0/500[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "Content-Type: application/octet-stream[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "Connection: Keep-Alive[\r][\n]"
2017-06-28 13:41:12,325 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 >> "[\r][\n]"
2017-06-28 13:41:12,326 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-57 << "end of stream"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "GET kkk HTTP/1.1[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "Host: bbb.s3.amazonaws.com[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "Authorization: AWS4-HMAC-SHA256 Credential=ccc/20170628/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=sss[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "X-Amz-Date: 20170628T174112Z[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "User-Agent: aws-sdk-java/1.11.150 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.40-b25/1.8.0_40[\r][\n]"
2017-06-28 13:41:12,371 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "amz-sdk-invocation-id: yyy[\r][\n]"
2017-06-28 13:41:12,372 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "amz-sdk-retry: 1/43/495[\r][\n]"
2017-06-28 13:41:12,372 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "Content-Type: application/octet-stream[\r][\n]"
2017-06-28 13:41:12,372 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "Connection: Keep-Alive[\r][\n]"
2017-06-28 13:41:12,372 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 >> "[\r][\n]"
2017-06-28 13:41:12,375 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-59 << "end of stream"
2017-06-28 13:41:12,448 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "GET kkk HTTP/1.1[\r][\n]"
2017-06-28 13:41:12,448 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "Host: bbb.s3.amazonaws.com[\r][\n]"
2017-06-28 13:41:12,448 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2017-06-28 13:41:12,448 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "Authorization: AWS4-HMAC-SHA256 Credential=ccc/20170628/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=sss[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "X-Amz-Date: 20170628T174112Z[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "User-Agent: aws-sdk-java/1.11.150 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.40-b25/1.8.0_40[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "amz-sdk-invocation-id: yyy[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "amz-sdk-retry: 2/72/490[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "Content-Type: application/octet-stream[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "Connection: Keep-Alive[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 >> "[\r][\n]"
2017-06-28 13:41:12,449 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-53 << "end of stream"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "GET kkk HTTP/1.1[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "Host: bbb.s3.amazonaws.com[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "Authorization: AWS4-HMAC-SHA256 Credential=ccc/20170628/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=sss[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "X-Amz-Date: 20170628T174112Z[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "User-Agent: aws-sdk-java/1.11.150 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.40-b25/1.8.0_40[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "amz-sdk-invocation-id: yyy[\r][\n]"
2017-06-28 13:41:12,708 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "amz-sdk-retry: 3/256/485[\r][\n]"
2017-06-28 13:41:12,709 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "Content-Type: application/octet-stream[\r][\n]"
2017-06-28 13:41:12,709 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "Connection: Keep-Alive[\r][\n]"
2017-06-28 13:41:12,709 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 >> "[\r][\n]"
2017-06-28 13:41:12,711 [http-bio-8080-exec-5] DEBUG o.a.h.wire http-outgoing-38 << "end of stream"
com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1378)

**Comment by dagnir** [comment] 2017-06-29 01:03
@sballa12 I could not reproduce this locally. Do you see this for every get object request only at certain times?

Some Googling lead me to this https://issues.apache.org/jira/browse/HTTPCLIENT-1610. Do you by any chance have Apache HttpClient 4.4 as a dependency? You can check to make sure by using [mvn dependency:tree](https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html)

**Comment by sballa12** [comment] 2017-06-30 14:03
@dagnir Thank you for pointing us in the right direction! We were using Apache HttpClient 4.4. After upgrading to  Apache HttpClient 4.5.2 and Apache HttpCore 4.4.4, this problem went away. Thanks again.

**Comment by dagnir** [comment] 2017-06-30 16:12
Glad to help! Closing this issue.

**Closed by dagnir** 2017-06-30 16:12 UTC
Labels: Question, waiting-reply

**Comment by deepakagrawal121** [comment] 2017-12-15 06:21
I am using aws-sdk 1.11.233 with HttpCLient 4.5.3 and HttpCore 4.4.8. And Still facing the same issue any idea?

**Comment by yifanguo247** [comment] 2018-07-16 14:55
I am also facing the same issue.

**Comment by jfernandez** [comment] 2018-07-16 20:43
Likewise. These started happening for us very sporadically.

**Comment by Ev3rlasting** [comment] 2018-07-19 04:30
We are facing the same issue.

**Comment by xe0nic** [comment] 2018-07-24 15:40
Same here. Strangely - first time we run app, nothing happens. When we stop and start again it, problem appears. Now - when we reboot OS and start app again - back to normal again...

Tested on CentOS 7.5 (updated as for today), Java 1.8.0.171 (OpenJDK), SDK 1.11.372. Not sure what can be the cause, cause we have other machine in the same network, that doesn't have that problem...

**Comment by abbccdda** [comment] 2018-07-25 21:10
We are facing the same issue.

**Comment by gavinlreynolds** [comment] 2018-11-02 15:16
Was this issue ever resolved?

**Comment by akhaku** [comment] 2019-04-09 18:40
This is happening for us too. It happens sporadically when downloading a large file - around 1.2GB (i.e. lots of parts being downloaded by TransferManager).
SDK version 1.11.501
Java version 1.8.0_202
Apache http client 4.5.6

No code changes or SDK upgrades.

**Comment by notenbrood** [comment] 2019-12-17 11:21
We're still running in to this pretty often, even with the latest versions of Apache HTTP Client

**Comment by Abbyliu2013** [comment] 2020-09-03 15:16
Issue still found in below version, and seems d) is better than before.

a) 
Java Version. -- 1.8 Amazon Corretto 8
 AWS SDK version -  Java 1.11.398
HTTP Client version - 4.5.9
HTTP core  4.4.11

b) 
Java Version. -- 1.8 Amazon Corretto 8
 AWS SDK version -  Java 1.11.839 
HTTP Client version - 4.5.12
HTTP core  4.4.13 

c)
Java Version. -- 1.8 Amazon Corretto 8
 AWS SDK version -  Java 1.11.839 
HTTP Client version - 4.5.10
HTTP core  4.4.11

d)
Java Version. -- 1.8 Amazon Corretto 8
AWS SDK version -  Java 1.11.839 
HTTP Client version - 4.5.2
HTTP core  4.4.4

**Comment by lyohannan** [comment] 2021-01-19 22:50
Was anyone able to resolve this issue? I am seeing this issue with Apache HTTP Core version 4.4.9 and Apache HTTP Client version 4.5.5.

**Comment by debora-ito** [comment] 2021-01-20 01:42
@lyohannan and anybody else who may be experiencing this issue:

please open a new issue with your findings. Make sure to provide all the details you can in the new issue template.

**Comment by tamar-sy** [comment] 2022-05-08 09:54
> 

@lyohannan 
Do you have any solution for this issue?

**Comment by riteshmaurya** [comment] 2022-10-20 10:33
Have you got any solution to this problem? I am having same issue

**Comment by XiaoanHi** [comment] 2022-11-07 06:24
I solved the problem by turning off the command line agent.

**Comment by harshanadias** [comment] 2022-11-08 09:08
> command line agent.

what you mean by command line agent? from where you turn it off pls?

**Comment by harshanadias** [comment] 2022-11-16 11:38
we also face same issue with high load

using below dependencies: 

Amazon correto 11 with Undertow 2.2.18

[INFO] +- com.amazonaws:aws-java-sdk-core:jar:1.12.330:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.13.3:compile
[INFO] |  \- joda-time:joda-time:jar:2.8.1:compile

**Comment by sxusarah** [comment] 2022-12-23 15:21
We also face the issue too with a small load upon below env. The downloading speed does not exceed 10M/seconds

EC2:  m5.large with 2vCPU and 8G memory
Test: download batch files of size 2M~8M from Amazon S3 
JDK: 1.8.0_352
AWS Java SDK:  v1.12.261
HTTP Client version: 4.5.13
HTTP core: 4.4.15

**Comment by harshanadias** [comment] 2022-12-24 02:04
> Undertow
my issue was due to dependency conflicts between Undertow and tomcat. After I exclude tomcat it works fine

**Comment by harshanadias** [comment] 2022-12-24 02:06
> we also face same issue with high load
> 
> using below dependencies:
> 
> Amazon correto 11 with Undertow 2.2.18
> 
my issue was due to dependency conflicts between Undertow and tomcat. After I exclude tomcat it works fine

**Comment by griffinmm** [comment] 2023-03-10 20:14
> ```java
> .withMaxErrorRetry(10)
> ```

This is what worked for me.

**Comment by caozibiao** [comment] 2023-03-13 09:53
org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  |     \- org.apache.httpcomponents:httpcore:jar:4.4.6:compile

we also face same issue with high load

**Comment by antonmaeso100** [comment] 2025-03-05 15:42
org.apache.httpcomponents:httpclient:jar:4.5.13:compile

We also face the same issue under high load

**Comment by MingNiu** [comment] 2025-05-21 08:40
facing the same issue

com.amazonaws:aws-java-sdk-bom:1.12.642
org.apache.httpcomponents:httpclient:4.5.14
