### ISSUE TITLE
Unable to send  signed POST request to AWS Elasticsearch service

### ISSUE THREAD

**Issue by martinformanko** [aws/aws-sdk-java#2275] opened 2020-03-24 21:35 UTC
I apologize if this is a configuration issue but I am afraid I already have tried everything to isolate and to resolve the problem but without any success - so maybe its a SDK bug.

**The problem**
AWS SDK signs incorrectly POST requests to AWS Elasticsearch service. Calling for example `elasticsearchClient.refresh()` of specific index throws an exception:
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
However, PUT and GET requests work flawlessly.

**Environment**
My elasticsearch service 7.4 is accessible within VPC and requires signed API calls. I am using AWS4 signing, Apache HTTP client (as provided in AWS SDK) 4.5.10, the newest version of AWS SDK from Maven.

**How to reproduce**
https://github.com/martinformanko/elastic-test.
Two possible running configurations:
- **Main.java** - Spring application
- **MainWithoutSpring.java** - plain Java app

**Important to mention** - POST request works in Go and appopriate Go library, with the same ACCESS_ID and SECRET_KEY, so this should not be a permission issue.

**Comment by martinformanko** [comment] 2020-03-24 21:38
Probably found the bug immediately after opening the issue by fixing interceptor:
From this:
```
        if (request instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest =
                    (HttpEntityEnclosingRequest) request;
            if (httpEntityEnclosingRequest.getEntity() != null) {
                signableRequest.setContent(httpEntityEnclosingRequest.getEntity().getContent());
            } 
        }
```
to this:
```
        if (request instanceof HttpEntityEnclosingRequest) {
            HttpEntityEnclosingRequest httpEntityEnclosingRequest =
                    (HttpEntityEnclosingRequest) request;
            if (httpEntityEnclosingRequest.getEntity() != null) {
                signableRequest.setContent(httpEntityEnclosingRequest.getEntity().getContent());
            } else {
                signableRequest.setContent(new ByteArrayInputStream(new byte[0]));
            }
        }
```
Are  you aware of any other use case when this would not work?

**Comment by debora-ito** [comment] 2020-03-25 01:59
Hi @martinformanko this is a duplicate of #2205. The issue is with Elasticsearch POST requests with query params but no content, for some reason the SDK calculates the signature using the query params as content value, resulting in the signature mismatch error. 

Your second comment shows a workaround for this problem: specifying an empty byte array as content - you can also specify it in your signable request.

Let's keep track of this in the other issue, please add a 👍🏻on it and feel free to add any comments about your use case.

**Closed by debora-ito** 2020-03-25 01:59 UTC
Labels: duplicate
