### ISSUE TITLE
S3 TransferManager - no support for KMS encryption with uploadFileList or similar operation

### ISSUE THREAD

**Issue by seoj** [aws/aws-sdk-java#568] opened 2015-12-04 15:16 UTC
I am using TransferManager to upload multiple files into S3 which requires KMS encryption.
I have so far have not found a friendly way of setting my KMS key ID for uploading using uploadFileList() method.

I'd imagine I could set the headers directly using ObjectMetadataProvider, but is there a simpler, more friendly way? If not will there be support for it?

PS. I am looking for an equivalent to PutObjectRequest.setSSEAwsKeyManagementParams(SSEAwsKeyManagementParams) for TransferManager

**Comment by shorea** [comment] 2015-12-11 00:56
We are working on supporting this. Unfortunately it's not even possible with ObjectMetadataProvider due to a bug in our MD5 validation logic. I'll update this issue when there is progress.

**Comment by seoj** [comment] 2015-12-15 14:02
I noticed that the latest versions of AWS SDK has a system property at com.amazonaws.services.s3.internal.SkipMd5CheckStrategy.DISABLE_PUT_OBJECT_MD5_VALIDATION_PROPERTY which we can set temporarily to disable this MD5 validation for KMS uploads when setting ObjectMetadata headers.

But obviously setting a system property which disables validation is not proper and this is meant to be very temporary. We are using this method to get around the problem initially, but will refactor when the proper implementation is released.

**Comment by shorea** [comment] 2015-12-17 04:14
A fix for this has been released in 1.10.41. You should be able to use SSE-C or SSE-KMS by setting the headers directly using ObjectMetadataProvider.

**Closed by shorea** 2015-12-17 04:14 UTC
Labels: Feature Request

**Comment by bharatnanda** [comment] 2018-12-14 00:40
I'm trying SSE-C using TransferManager and uploadFileList method. Here is what I did:

TransferManager xferMgr = TransferManagerBuilder.standard().build();
		MultipleFileUpload xfer = null;
		if (StringUtil.isNullOrEmpty(encryptionKey)) {
			xfer = xferMgr.uploadFileList(tenantBucketId, outputFolder, localDirectory, Arrays.asList(files));
		} else {
			ObjectMetadataProvider objectMetadataProvider = ((File file, ObjectMetadata metadata) -> {
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_ALGORITHM, "AES256");
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_KEY, encryptionKey);
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_KEY_MD5, Md5Utils.md5AsBase64(Base64.getDecoder().decode(encryptionKey)));
			});
			xfer = xferMgr.uploadFileList(tenantBucketId, outputFolder, localDirectory, Arrays.asList(files),
					objectMetadataProvider);
		}

I'm able to upload multiple small files simultaneously, however code throws exception in case of big file like 250 MB.
Following is the exception I'm seeing:

Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multi-part upload. Individual part upload failed : The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 08CA2CA356DB6C37; S3 Extended Request ID: 1sLnZUD04Rz2hlpACDI85X9v1I+mvt9RMkT1wqf5NGjReFKYWiHZpSuDsbmRuXasP79JZ1ljnpU=)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.collectPartETags(CompleteMultipartUpload.java:127)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:89)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 08CA2CA356DB6C37; S3 Extended Request ID: 1sLnZUD04Rz2hlpACDI85X9v1I+mvt9RMkT1wqf5NGjReFKYWiHZpSuDsbmRuXasP79JZ1ljnpU=), S3 Extended Request ID: 1sLnZUD04Rz2hlpACDI85X9v1I+mvt9RMkT1wqf5NGjReFKYWiHZpSuDsbmRuXasP79JZ1ljnpU=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
	at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3307)
	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3292)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:33)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:23)
	... 4 more
I guess, its a bug.
Using sdk-1.11.294
