### ISSUE TITLE
Proxy is not working while listing objects in S3 V1 SDK

### ISSUE THREAD

**Issue by subrahmanyam5b0** [aws/aws-sdk-java#2891] opened 2022-12-19 03:44 UTC
### Describe the bug

Proxy configuration is not working when we perform any operation after client creation.

### Expected Behavior

When we set the proxy while building the client, if we perform any operations like S3 list objects the same proxy has to set again.

### Current Behavior

We have an application running in AWS EKS and we need to perform operations on S3 we created all the IAM roles and created service accounts in EKS, with CLI it was working fine. When we try from Java V1 SDK we are getting connection time out for sts.amazon.com. as we are behind we are configured the client configuration with required proxy. During client creation we could see from logs proxy is configured. When we tried to ist objects proxy is not configured for amazon http client. With the system.set properties for proxy it was working fine

		System.out.println("Connecting to S3 Bucket ..");
        //System.setProperty("https.proxyHost",proxyHost);
        //System.setProperty("https.proxyPort",proxyPort);
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.withProxyHost(proxyHost);
        clientConfiguration.withProxyPort(Integer.parseInt(proxyPort));
        clientConfiguration.setProxyHost(proxyHost);
        clientConfiguration.setProxyPort(Integer.parseInt(proxyPort));
        clientConfiguration.setProtocol(Protocol.HTTPS);
        clientConfiguration.setProxyProtocol(Protocol.HTTPS);
        final AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                .withClientConfiguration(clientConfiguration)
                .withCredentials(WebIdentityTokenCredentialsProvider.create())
                .build();
        System.out.println("Connected to S3 Bucket .." + s3.getRegionName());
        ListObjectsV2Result result = s3.listObjectsV2("development-test");
        System.out.println(("Objects : {}" + result.getObjectSummaries().stream().limit(20).map(S3ObjectSummary::getKey).collect(Collectors.toList())));

### Reproduction Steps

Application should be up and running with required services account in AWS eks
Create S3 client using proxy. 
Try to list the objects 
Connection timeout for sts.amazin.aws.com

### AWS Java SDK version used

1.12.362

### JDK version used

Open JDK 1.8

### Operating System and version

EKS UBI 8

**Comment by subrahmanyam5b0** [comment] 2022-12-19 06:37
Logs --- with Client Configuration Proxy while creating the client.

Connecting to S3 Bucket ..
09:44:35.474 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
09:44:35.741 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
09:44:36.543 [main] INFO com.amazonaws.http.AmazonHttpClient - Configuring Proxy. Proxy Host: 10.239.9.190 Proxy Port: 443
09:44:36.855 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.EnvironmentVariableCsmConfigurationProvider@1e04fa0a: Unable to load Client Side Monitoring configurations from environment variables!
09:44:36.856 [java-sdk-http-connection-reaper] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Closing connections idle longer than 60000 MILLISECONDS
09:44:36.856 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider@1af2d44a: Unable to load Client Side Monitoring configurations from system properties variables!
09:44:36.857 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.ProfileCsmConfigurationProvider@58695725: Unable to load config file
Connected to S3 Bucket ..ap-southeast-1
09:44:37.750 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.EnvironmentVariableCsmConfigurationProvider@1e04fa0a: Unable to load Client Side Monitoring configurations from environment variables!
09:44:37.750 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider@1af2d44a: Unable to load Client Side Monitoring configurations from system properties variables!
09:44:37.750 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.ProfileCsmConfigurationProvider@58695725: Unable to load config file
09:44:37.842 [main] DEBUG com.amazonaws.request - Sending Request: POST https://sts.amazonaws.com /
09:44:37.945 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
09:44:37.954 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
09:44:37.956 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://sts.amazonaws.com:443][total available: 0; route allocated: 0 of 50; total allocated: 0 of 50]
09:44:38.042 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://sts.amazonaws.com:443][total available: 0; route allocated: 1 of 50; total allocated: 1 of 50]
09:44:38.044 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {s}->https://sts.amazonaws.com:443
09:44:38.056 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to sts.amazonaws.com/54.239.29.25:443
09:44:38.056 [main] DEBUG com.amazonaws.http.conn.ssl.SdkTLSSocketFactory - connecting to sts.amazonaws.com/54.239.29.25:443
09:44:38.056 [main] DEBUG com.amazonaws.http.conn.ssl.SdkTLSSocketFactory - Connecting socket to sts.amazonaws.com/54.239.29.25:443 with timeout 10000
09:44:48.068 [main] DEBUG com.amazonaws.http.conn.ClientConnectionManagerFactory -
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy2.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1727)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1694)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1683)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1042)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1010)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.newSession(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:149)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.access$000(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:40)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:65)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:62)
        at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:295)
        at com.amazonaws.auth.RefreshableTask.blockingRefresh(RefreshableTask.java:251)
        at com.amazonaws.auth.RefreshableTask.getValue(RefreshableTask.java:192)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getCredentials(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:130)
        at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getCredentials(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:40)
        at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getCredentials(STSProfileCredentialsServiceProvider.java:71)
        at com.amazonaws.auth.WebIdentityTokenCredentialsProvider.getCredentials(WebIdentityTokenCredentialsProvider.java:76)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:845)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5397)
        at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:971)
        at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:934)

**Comment by subrahmanyam5b0** [comment] 2022-12-19 06:38
Logs - With Proxy for System.set Property

Connecting to S3 Bucket ..
10:20:59.777 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
10:20:59.966 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
10:21:00.955 [main] INFO com.amazonaws.http.AmazonHttpClient - Configuring Proxy. Proxy Host: 10.239.9.190 Proxy Port: 443
10:21:01.250 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.EnvironmentVariableCsmConfigurationProvider@1e04fa0a: Unable to load Client Side Monitoring configurations from environment variables!
10:21:01.250 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider@1af2d44a: Unable to load Client Side Monitoring configurations from system properties variables!
10:21:01.251 [java-sdk-http-connection-reaper] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Closing connections idle longer than 60000 MILLISECONDS
10:21:01.251 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.ProfileCsmConfigurationProvider@58695725: Unable to load config file
Connected to S3 Bucket ..ap-southeast-1
10:21:01.962 [main] INFO com.amazonaws.http.AmazonHttpClient - Configuring Proxy. Proxy Host: 10.239.9.190 Proxy Port: 443
10:21:01.963 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.EnvironmentVariableCsmConfigurationProvider@1e04fa0a: Unable to load Client Side Monitoring configurations from environment variables!
10:21:01.963 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.SystemPropertyCsmConfigurationProvider@1af2d44a: Unable to load Client Side Monitoring configurations from system properties variables!
10:21:01.964 [main] DEBUG com.amazonaws.monitoring.CsmConfigurationProviderChain - Unable to load configuration from com.amazonaws.monitoring.ProfileCsmConfigurationProvider@58695725: Unable to load config file
10:21:02.051 [main] DEBUG com.amazonaws.request - Sending Request: POST https://sts.amazonaws.com /
10:21:02.158 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
10:21:02.244 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
10:21:02.246 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {tls}->http://10.239.9.190:443->https://sts.amazonaws.com:443][total available: 0; route allocated: 0 of 50; total allocated: 0 of 50]
10:21:02.347 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {tls}->http://10.239.9.190:443->https://sts.amazonaws.com:443][total available: 0; route allocated: 1 of 50; total allocated: 1 of 50]
10:21:02.350 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {tls}->http://10.239.9.190:443->https://sts.amazonaws.com:443
10:21:02.353 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to /10.239.9.190:443
10:21:02.440 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 100.68.159.188:50950<->10.239.9.190:443

**Comment by debora-ito** [comment] 2023-03-04 03:35
@subrahmanyam5b0 apologies for the long silence.

The cause for the error is that the proxy settings defined in the ClientConfiguration are not passed to the underlying STS client used in the WebIdentityTokenCredentialsProvider.

As you noticed, the proxy System Properties are honored, so this is the recommended workaround. This is a similar ask of https://github.com/aws/aws-sdk-java/issues/2558 so I'll close this to avoid duplicate issues. Please reach out if you have other questions.

**Closed** 2023-03-09 02:56 UTC
Labels: bug
