### ISSUE TITLE
Hang in SDK with parallel uploads under load

### ISSUE THREAD

**Issue by ajfabbri** [aws/aws-sdk-java#1102] opened 2017-04-05 21:56 UTC
We have reproduced a hang in the aws-sdk-java version 1.11.86.  It takes some time to reproduce but is pretty reliable.

Support case ID 2115933851.

The original reproduction was using Hadoop, but we've created an SDK-only test that reproduces the bug here:

https://github.com/ajfabbri/awstest

**Comment by ajfabbri** [comment] 2017-04-05 21:58
Run the included test for awhile.. At some point it should hang.  Using jstack or a debugger you'll see a thread stuck in com.amazonaws.services.s3.transfer.internal.CopyImpl.waitForCopyResult() and never getting woke up.

**Comment by ajfabbri** [comment] 2017-04-05 22:11
Filed a Hadoop bug [here](https://issues.apache.org/jira/browse/HADOOP-14283), since that project depends on this.

**Comment by dagnir** [comment] 2017-04-07 22:50
Good news, we've found the root cause to be a subtle scheduling issue with the way `CopyMonitor#setFuture` works. We are considering possible solutions now.

**Comment by dagnir** [comment] 2017-04-11 18:54
This is fixed upstream. It should be available in our next release which will probably happen later today.

**Comment by dagnir** [comment] 2017-04-11 23:15
Hi @ajfabbri this is fixed in [1.11.119](https://github.com/aws/aws-sdk-java/blob/1.11.119/CHANGELOG.md#bugfixes). Closing this issue.

**Closed by dagnir** 2017-04-11 23:15 UTC
Labels: Bug
