### ISSUE TITLE
Issue with DynamoDBTypeConverted

### ISSUE THREAD

**Issue by knap1930** [aws/aws-sdk-java#820] opened 2016-08-23 00:39 UTC
calling marshallIntoObject in DynamoDBMapper seems to ignore the new @DynamoDBTypeConverted annotation?

```

com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: Field com.kamcord.stream.data.dynamo.model.v1.StreamSessionTable[started_at] could not unconvert
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.unconvert(DynamoDBMapperFieldModel.java:204)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.unconvertAndSet(DynamoDBMapperFieldModel.java:286)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperTableModel.unconvert(DynamoDBMapperTableModel.java:250)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.privateMarshallIntoObject(DynamoDBMapper.java:547)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.marshallIntoObject(DynamoDBMapper.java:533)
	at com.kamcord.stream.data.dynamo.DynamoDataAccessor.updateStreamSession(DynamoDataAccessor.java:3728)
	at com.kamcord.stream.data.dynamo.DynamoDataAccessor$Proxy$_$$_WeldClientProxy.updateStreamSession(Unknown Source)
	at com.kamcord.stream.manager.StreamManager.updateStreamSession(StreamManager.java:1223)
	at com.kamcord.stream.manager.StreamManager$Proxy$_$$_WeldClientProxy.updateStreamSession(Unknown Source)
	at com.kamcord.stream.data.dynamo.helper.SessionQueueWorker.run(SessionQueueWorker.java:87)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: type [DEFAULT[class org.joda.time.DateTime]] is not supported; requires @DynamoDBDocument or @DynamoDBTypeConverted
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardAttributeTypes$Conversions$1.unconvert(StandardAttributeTypes.java:321)
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardAttributeTypes$Conversions$1.unconvert(StandardAttributeTypes.java:315)
	at com.amazonaws.services.dynamodbv2.datamodeling.StandardTypeConverters$2.unconvert(StandardTypeConverters.java:614)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.unconvert(DynamoDBMapperFieldModel.java:202)
	... 10 more
]]

```

**Comment by shorea** [comment] 2016-08-23 00:48
Duplicate of #817

**Closed by shorea** 2016-08-23 00:48 UTC
