### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.amazonaws.util.IOUtils.closeQuietly

### ISSUE THREAD

**Issue by umesh2611** [aws/aws-sdk-java#2907] opened 2023-01-10 09:20 UTC
### Describe the bug

Hi,

I am following the link : [https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html ](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) to send a kafka message to the MSK cluster ( provisioned / IAM ) 

When i am sending the message i get the following error : 

2023-01-10T14:05:04.035+05:30

Copy
2023-01-10 08:35:04,033 - ERROR - kafka-producer-network-thread | producer-1 - org.apache.kafka.common.utils.KafkaThread - Uncaught exception in thread 'kafka-producer-network-thread | producer-1':

2023-01-10T14:05:04.035+05:30	java.lang.NoSuchMethodError: 'void com.amazonaws.util.IOUtils.closeQuietly(java.io.Closeable, org.apache.commons.logging.Log)'
	at software.amazon.msk.auth.iam.internals.UserAgentUtils.getLibraryVersion(UserAgentUtils.java:73)
at software.amazon.msk.auth.iam.internals.UserAgentUtils.getLibraryVersion(UserAgentUtils.java:73)
	at software.amazon.msk.auth.iam.internals.UserAgentUtils.<clinit>(UserAgentUtils.java:43)
at software.amazon.msk.auth.iam.internals.UserAgentUtils.<clinit>(UserAgentUtils.java:43)

complete log  :

[https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252FTmf628NormalizationUPALIWAL/log-events/ecs$252Ftmf628NormalizationContainer2$252F798843bb106f4e5a8fe41e423673e0a5 ](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Fecs$252FTmf628NormalizationUPALIWAL/log-events/ecs$252Ftmf628NormalizationContainer2$252F798843bb106f4e5a8fe41e423673e0a5)

What i analyzed, the IOUtils pacakged in com.amazonaws.aws-java-sdk-bundle-1.12.262.jar contains a method with the following signature : 

public static void com.amazonaws.util.IOUtils.closeQuietly(java.io.Closeable,com.amazonaws.thirdparty.apache.logging.Log)

but  "aws-msk-iam-auth" is expecting a method with the following signature : 
'void com.amazonaws.util.IOUtils.closeQuietly(java.io.Closeable, org.apache.commons.logging.Log)'

Can you pease help me on moving ahead ?

/Umesh Paliwal

### Expected Behavior

NA

### Current Behavior

NA

### Reproduction Steps

NA

### AWS Java SDK version used

2.17.195

### JDK version used

11

### Operating System and version

Linux

**Comment by debora-ito** [comment] 2023-01-18 22:51
Duplicate of https://github.com/aws/aws-sdk-java-v2/discussions/3688. Closing this one.

**Closed by debora-ito** 2023-01-18 22:51 UTC
Labels: bug, needs-triage
