### ISSUE TITLE
o.apache.coyote.http11.Http11Processor : Error parsing HTTP request header java.io.EOFException: null

### ISSUE THREAD

**Issue by sumit4209211** [aws/aws-sdk-java#2315] opened 2020-05-07 04:00 UTC
## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment] 2020-05-07 16:37
Duplicate of #2316.

**Closed by debora-ito** 2020-05-07 16:37 UTC
Labels: duplicate
