### ISSUE TITLE
com.amazonaws.regions.EndpointToRegion#guessRegionNameForEndpoint Broken for Endpoint String without Schema

### ISSUE THREAD

**Issue by original-brownbear** [aws/aws-sdk-java#2274] opened 2020-03-23 10:07 UTC
After upgrading to `1.11.749`, I see this failure when constructing an S3 client that uses e.g. endpoint string `127.0.0.1:5021` or any other string that doesn't contain a schema.

```
  Caused by: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:5
  1>    at java.base/java.net.URI.create(URI.java:906)
  1>    at com.amazonaws.regions.EndpointToRegion.guessRegionOrRegionNameForEndpoint(EndpointToRegion.java:71)
  1>    at com.amazonaws.regions.EndpointToRegion.guessRegionNameForEndpoint(EndpointToRegion.java:41)
  1>    at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:323)
  1>    at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:725)
  1>    at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:453)
  1>    at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
  1>    at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
```

The JavaDocs explicitly state that an endpoint string without a schema should work and it used to work in `1.11.636` so this is new it seems.
I think this can easily be fixed by using e.g. `com.amazonaws.AmazonWebServiceClient#toURI` which is used in other places to handle this kind of string to `URI` conversion.

**Comment by debora-ito** [comment] 2020-03-24 23:17
Hi @original-brownbear, thank you for reaching out. This is a duplicate of #2255, let's track this issue over there.

**Closed by debora-ito** 2020-03-24 23:17 UTC
Labels: duplicate
