### ISSUE TITLE
Presigned expirable URL is not ready immediately after creation

### ISSUE THREAD

**Issue by jmayday** [aws/aws-sdk-java#1699] opened 2018-07-26 20:21 UTC
I'm using aws-java-sdk-s3 in version 1.11.367 and I observed that sometimes, after requesting presigned URL to object in my bucket, the link is not valid for some time (I get _"Forbidden Request has expired"_). I have to wait few seconds before the link gets valid. 

My expiration time is rather short and set to 13 seconds. I also observed, that if I generate an URL which expiration time is longer (one hour or one week), it is immediately ready to use. 

I checked docs and I haven't found anything saying that link might not be immediately ready after creation. I checked this: [Amazon docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html)

Have you observed such behaviour? What might be the reason?

Below some piece of code I'm using to generate the URL:
```
ResponseHeaderOverrides responseHeaders = new ResponseHeaderOverrides()
    .withContentDisposition("attachment; filename=\"" + filename + "\"")
    .withContentType(guessContentTypeFromName(filename));

GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(
    this.bucket, uuid)
    .withMethod(HttpMethod.GET)
    .withExpiration(expiration)
    .withResponseHeaders(responseHeaders);

URL url = s3client.generatePresignedUrl(generatePresignedUrlRequest);
```

I think it's just exactly what has been given [here as example](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html).

**Comment by dagnir** [comment] 2018-07-31 21:41
Hi @jmayday I tried but was unable to reproduce the error described using the given sample code:

```java
        AmazonS3 s3 = AmazonS3ClientBuilder.defaultClient();

        GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(
                "dongie-test-bucket", "8kb_file.dat")
                .withMethod(HttpMethod.GET)
                .withExpiration(new Date(System.currentTimeMillis() + TimeUnit.MILLISECONDS.convert(13, TimeUnit.SECONDS)));

        URL url = s3.generatePresignedUrl(generatePresignedUrlRequest);

        HttpsURLConnection conn = ((HttpsURLConnection) url.openConnection());

        System.out.println(conn.getResponseCode());
        IOUtils.drainInputStream(conn.getInputStream());
```

When you say immediately after creation, how much delay is there between creation of the presigned URL and actually performing a GET request on it? With a relatively short expiration time (13 seconds) it could be that your system clock and S3's have drifted apart, and if S3's clock is a little ahead of yours then its possible that by the time S3 receives the request, it computes that the expiration for the URL has passed.

**Comment by jmayday** [comment] 2018-08-01 06:25
@dagnir 

> I tried but was unable to reproduce the error described using the given sample code:

As I said - it doesn't happen all the time. Also for me it's not possible to recreate the issue now. 

> When you say immediately after creation, how much delay is there between creation of the presigned URL and actually performing a GET request on it?

Less than 1 second

> With a relatively short expiration time (13 seconds) it could be that your system clock and S3's have 
drifted apart, and if S3's clock is a little ahead of yours then its possible that by the time S3 receives the request, it computes that the expiration for the URL has passed.

I contacted my S3 provider support and they did some good job analyzing logs. It came out, that providers clock was sometimes ahead of mine and sometimes behind. In both cases, when difference was greater than expiration time I got 403 response. 

Some examples:

Time of loadbalancer | X_Amz_Date | X_Amz_Expires | status | Time diff [s]
-- | -- | -- | -- | --
2018-07-30T20:56:33.000+0200 | 20180730T185556Z | 13 | 403 | -37
2018-07-24T01:28:35.000+0200 | 20180723T232832Z | 14 | 200 | -3 
2018-07-27T09:56:13.000+0200 | 20180727T075629Z | 13 | 403 | 16 (my clock is ahead of S3)

**Comment by dagnir** [comment] 2018-08-01 17:46
@jmayday Ah okay. For clock skew errors, the SDK is able to [self-correct](https://github.com/aws/aws-sdk-java/blob/b76991ef8db5076b5605c6e1cfd708ddf8bb7406/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1313-L1317) if it receives a clock skew exception from the service but that's only if the actual request is made through the service client, and not through a presigned URL.

One suggestion, if you don't have it enabled already, would to be enable NTP on your machine(s) so that the systems' time is in sync with the UTC reference.

**Comment by shorea** [comment] 2018-08-20 04:59
Closing issue, feel free to reopen if you have further questions/issues.

**Closed by shorea** 2018-08-20 04:59 UTC
Labels: Question, waiting-reply
