### ISSUE TITLE
DefaultRequest toString adds space between endpoint and resourcePath

### ISSUE THREAD

**Issue by SmarMykel** [aws/aws-sdk-java#2962] opened 2023-04-17 17:04 UTC
### Describe the bug

```
@Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(getHttpMethod()).append(" ");
        builder.append(getEndpoint()).append(" ");
        String resourcePath = getResourcePath();

        if (resourcePath == null) {
            builder.append("/");
        }
        else {
            if (!resourcePath.startsWith("/")) {
                builder.append("/");
            }
            builder.append(resourcePath);
        }

        return builder.toString();
    }
```

    
 In [aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/DefaultRequest.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/DefaultRequest.java) toString method does this. I have been trying to understand why this necessary but can't understand.
    
There a space appended after the  `getEndpoint()` ?. 
Specifically  `builder.append(" ")`  after `builder.append(getEndpoint())`
    
 If my endpoint is `Endpoint: https://api.example.com` and `Resource Path: /users/123`, then I will get `GET https://api.example.com /users/123` with a space between the endpoint and resource path
    
 

### Expected Behavior

DefaultRequest toString() returns for 

Endpoint = https://api.example.com
Resource Path =  /users/123

https://api.example.com/users/123 with no space between the endpoint and resource path

### Current Behavior

DefaultRequest toString() returns for 

Endpoint = https://api.example.com
Resource Path =  /users/123

https://api.example.com /users/123 with a space between the endpoint and resource path

### Reproduction Steps

```
val endpoint = "https://api.example.com"
val path = "/users/123"
val httpMethodNameValue = "GET"

val awsRequest = DefaultRequest<Any>("execute-api")

awsRequest.endpoint = URI.create(endpoint)
awsRequest.resourcePath = "/$path"
awsRequest.httpMethod = httpMethodNameValue

// put breakpoint after this code and see the DefaultRequest

println()
```

### Possible Solution

```
@Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append(getHttpMethod()).append(" ");
        builder.append(getEndpoint());
        String resourcePath = getResourcePath();

        if (resourcePath == null) {
            builder.append("/");
        }
        else {
            if (!resourcePath.startsWith("/")) {
                builder.append("/");
            }
            builder.append(resourcePath);
        }

        return builder.toString();
    }
```

### AWS Java SDK version used

2.20.47

### JDK version used

openjdk 17.0.6 2023-01-17 LTS

### Operating System and version

MacOS Ventura 13.3

**Comment by debora-ito** [comment] 2023-05-02 02:56
@SmarMykel thank you for reaching out.

What is your use case?
How do you use DefaultRequest#toString?

**Comment by SmarMykel** [comment] 2023-05-03 22:27
I use as a `SignableRequest<?> request` so I can generate a request that can be signed using the `public AWS4Signer()` class.

**Comment by debora-ito** [comment] 2023-05-04 19:43
Yes, as a good practice we don't recommend your code logic to rely on the String representation of an object. The toString method should be used in situations like logging and debugging.

Closing as this is not a bug. Feel free to reach out if you have any other question.

**Closed by debora-ito** 2023-05-04 19:43 UTC
Labels: bug
