### ISSUE TITLE
java s3 client reporting incorrect region for requested bucked

### ISSUE THREAD

**Issue by iceback** [aws/aws-sdk-java#2455] opened 2020-11-10 23:13 UTC
The s3 client claims the bucket is in us-east-1 when the web page shows that it's in us-west-2
## Describe the bug
I am re-running an application which last week read these buckets/files correctly but today the s3 client is reporting that the buckets are in us-east-1

## Expected Behavior
I should be able to read the files using the s3client

## Current Behavior
I get an error from the s3 library saying the bucket is in us-east-1

My aws configuration:
aws configure
AWS Access Key ID [****************UJHF]: 
AWS Secret Access Key [****************tpk5]: 
Default region name [us-west-2]: 
Default output format [json]: 

Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: A4D923262D74EBAA; S3 Extended Request ID: B55760P4B/MjjELCgzzHvw1lIGXDJayCT1Z+Co0dMBODTVqC5ZUJCVoYs5jW4QMqQqF0R3w9BNQ=; Proxy: null), S3 Extended Request ID: B55760P4B/MjjELCgzzHvw1lIGXDJayCT1Z+Co0dMBODTVqC5ZUJCVoYs5jW4QMqQqF0R3w9BNQ=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1828)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1412)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1374)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1512)
        at edu.utah.camplab.tools.S3FileInputStream.getS3Reader(S3FileInputStream.java:31)
        at edu.utah.camplab.app.PedParLoader.buildMarkerAlleleMap(PedParLoader.java:872)
        at edu.utah.camplab.app.PedParLoader.lambda$load$0(PedParLoader.java:225)
        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:636)
        at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:633)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564)
        at org.jooq.impl.Tools$12$1.block(Tools.java:4926)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
        at org.jooq.impl.Tools$12.get(Tools.java:4923)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533)
        at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:633)
        at edu.utah.camplab.app.PedParLoader.load(PedParLoader.java:214)
        at edu.utah.camplab.app.PedParLoader.main(PedParLoader.java:116)

I'm using logback but I get no reports from either of the suggested packages

not relevant

## Your Environment

* AWS Java SDK version used:
AWS jars:
com.amazonaws/aws-java-sdk-s3/1.11.898/cabf3a3575d43987279ba52af9f889182a4a03ea/aws-java-sdk-s3-1.11.898.jar:
com.amazonaws/aws-java-sdk-kms/1.11.898/e8555557725dffa1ea19ce6594a569c8820522c2/aws-java-sdk-kms-1.11.898.jar:
com.amazonaws/jmespath-java/1.11.898/4b9c23e416ae8366250709e059e43a9eef0cff51/jmespath-java-1.11.898.jar:
com.amazonaws/aws-java-sdk-core/1.11.898/2e491240bfe4c9aaf1baa21667333da3771bfcca/aws-java-sdk-core-1.11.898.jar:

* JDK version used:
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

* Operating System and version:
ubuntu 20.04

**Comment by debora-ito** [comment] 2020-11-11 18:02
Duplicate of #2456.

**Closed by debora-ito** 2020-11-11 18:02 UTC
Labels: bug, needs-triage
