### ISSUE TITLE
Sax Feaure "disallow-doctype-decl" incompatible with fasterxml woodtstox SaxParser

### ISSUE THREAD

**Issue by pwachira** [aws/aws-sdk-java#2830] opened 2022-08-22 23:21 UTC
### Describe the bug

Fasterxml woodstox does not support the sax feature http://apache.org/xml/features/disallow-doctype-decl
and results in an saxexception if woodstox is the sax driver found in classpath.
To fix this I had to add the jvm option -Dorg.xml.sax.driver=org.apache.xerces.parsers.SaxParser

Is there a way to use this as the default - maybe in META-INF?

### Expected Behavior

No exception when sax parser is required for sdk operations

### Current Behavior

 exception when sax parser is required for sdk operations

### Reproduction Steps

I created a spring integration aws from the example shown here https://github.com/spring-projects/spring-integration-aws
At runtime the S3InboundFileSynchronizer failed due to 

```
Caused by: org.xml.sax.SAXNotRecognizedException: Feature 'http://apache.org/xml/features/disallow-doctype-decl' not recognized
	at com.ctc.wstx.sax.WstxSAXParser.setFeature(WstxSAXParser.java:532)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.disableExternalResourceFetching(XmlResponsesSaxParser.java:254)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:136)
```

Problem was resolved when I set jvm option `-Dorg.xml.sax.driver=org.apache.xerces.parsers.SaxParser`

### AWS Java SDK version used

11

### JDK version used

11

### Operating System and version

1.12.272

**Comment by debora-ito** [comment] 2022-09-07 17:24
Closing as a duplicate of https://github.com/aws/aws-sdk-java/discussions/2829.

**Closed by debora-ito** 2022-09-07 17:24 UTC
Labels: bug, needs-triage
