### ISSUE TITLE
Kinesis Agent throws InvalidSignatureException due to special chars in access key

### ISSUE THREAD

**Issue by adzdo** [aws/aws-sdk-java#1948] opened 2019-03-21 19:46 UTC
New access key for AWS Firehose was generated with AWS Management Console, the new key included a forward slash. After updating the config, Kinesis Agent continually threw this send error. Regenerated a key without any special chars to resolve, but expected any key generated by the Management Console would work with the Kinesis sdk.

2019-03-13 16:03:00.863+0000 ******** (sender-0) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[fh:**://***//.log]:RecordBuffer(id=2,records=2,bytes=2113) Retriable send error (com.amazonaws.services.kinesisfirehose.model.AmazonKinesisFirehoseException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: InvalidSignatureException; Request ID: *********)). Will retry.

https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/AgentAWSCredentialsProvider.java

I can't find any code in the amazon-kinesis-agent source that handles generating signatures. As far as I can tell, it relies on aws-java-sdk-core for auth, and aws-java-sdk-kinesis for delivering records to a stream.

**Comment by debora-ito** [comment] 2019-03-25 19:08
Closing as duplicate of #1941.

**Closed by debora-ito** 2019-03-25 19:08 UTC
