### ISSUE TITLE
Unable to add WebACL to cloudfront distribution

### ISSUE THREAD

**Issue by varkey98** [aws/aws-sdk-java#2901] opened 2022-12-31 04:51 UTC
### Describe the bug

Getting `com.amazonaws.services.cloudfront.model.InvalidWebACLIdException: Unable to verify read permissions on Web ACL. Please retry the request` error when trying to add a web ACL to a cloudfront distribution.

### Expected Behavior

The DistributionConfig to get updated

### Current Behavior

```
Exception in thread "main" com.amazonaws.services.cloudfront.model.InvalidWebACLIdException: Unable to verify read permissions on Web ACL. Please retry the request. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidWebACLId; Request ID: 9ad339a4-c486-4a39-944a-9e71a20da231; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
An illegal reflective access operation has occurred

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
Illegal reflective access by com.amazonaws.util.XpathUtils (file:/Users/varkeychanjacob/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk-core/1.12.375/8427e4269d9f99b2eeb1a3b8acec406a4d109930/aws-java-sdk-core-1.12.375.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
Please consider reporting this to the maintainers of com.amazonaws.util.XpathUtils

Use --illegal-access=warn to enable warnings of further illegal reflective access operations

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
All illegal access operations will be denied in a future release

	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.cloudfront.AmazonCloudFrontClient.doInvoke(AmazonCloudFrontClient.java:9517)
	at com.amazonaws.services.cloudfront.AmazonCloudFrontClient.invoke(AmazonCloudFrontClient.java:9484)
	at com.amazonaws.services.cloudfront.AmazonCloudFrontClient.invoke(AmazonCloudFrontClient.java:9473)
	at com.amazonaws.services.cloudfront.AmazonCloudFrontClient.executeUpdateDistribution(AmazonCloudFrontClient.java:8353)
	at com.amazonaws.services.cloudfront.AmazonCloudFrontClient.updateDistribution(AmazonCloudFrontClient.java:8321)
	at ai.traceable.platform.oob.provider.waf.aws.test.main4.main(main4.java:85)
```

### Reproduction Steps

```
distributionConfig.setWebACLId("webACLARN");
  UpdateDistributionRequest updateDistributionRequest = new UpdateDistributionRequest().withId("distributionID").withDistributionConfig(distributionConfig).withIfMatch(getDistributionConfigResult.getETag());
  client.updateDistribution(updateDistributionRequest);
```

### AWS Java SDK version used

1.12.375

### JDK version used

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Operating System and version

macOS 13.0.1

**Comment by debora-ito** [comment] 2023-01-18 23:03
Duplicate of https://github.com/aws/aws-sdk-java/discussions/2900. Closing.

**Closed by debora-ito** 2023-01-18 23:03 UTC
Labels: bug, needs-triage
