### ISSUE TITLE
SdkClientException: Unable to load credentials from service endpoint.

### ISSUE THREAD

**Issue by SakuraLxm** [aws/aws-sdk-java#2849] opened 2022-09-19 13:08 UTC
### Describe the issue

! java.net.SocketTimeoutException: Connect timed out
! at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
! at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
! at java.base/java.net.Socket.connect(Socket.java:633)
! at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
! at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
! at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
! at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
! at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
! at software.amazon.awssdk.regions.internal.util.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:45)
! at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:112)
! at software.amazon.awssdk.regions.util.HttpResourcesUtils.readResource(HttpResourcesUtils.java:91)
! at software.amazon.awssdk.auth.credentials.InstanceProfileCredentialsProvider$InstanceProviderCredentialsEndpointProvider.endpoint

i can see my table by awstools which create by my project.but,when i running my project it make err..
i also use vpn  and config targeD 0.0.0.0/0 ，i can also connet my redis ..  i dont know why

### Links

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/22929594/191024090-d81f7fe5-55cd-49eb-a8af-0c154244a72a.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/22929594/191024272-c25cd0a0-9c2f-4fde-af82-f701a2324be4.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/22929594/191024529-af77ed26-6879-46c0-8510-6478d3210c6c.png">

**Comment by SakuraLxm** [comment] 2022-09-19 13:10
<img width="290" alt="image" src="https://user-images.githubusercontent.com/22929594/191024891-ed8a7946-8b34-4007-b90e-8205554b55a0.png">

**Comment by SakuraLxm** [comment] 2022-09-19 13:12
<img width="535" alt="image" src="https://user-images.githubusercontent.com/22929594/191025226-0f020307-b2b7-4ad8-96ec-dd082418feee.png">

**Comment by SakuraLxm** [comment] 2022-09-20 19:14
i solved it. when i do like this 
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22929594/191344687-d7c12ec0-6cbd-4f2b-bf0c-ff88101fcf09.png">
but. anybody can tell me why?  this is my first time use aws..

**Comment by debora-ito** [comment] 2022-09-20 21:04
I can't say for sure since some things are defined outside of the code samples you provided (like `config`) but I'll say that probably `InstanceProfileCredentialsProvider` was not reaching the IMDS endpoint, due to a misconfigured vpc or security group.

**Comment by SakuraLxm** [comment] 2022-09-21 03:18
> 

thanks.. but vpc  and security group works normally.. when i changed my code like this
<img width="861" alt="image" src="https://user-images.githubusercontent.com/22929594/191406496-8af729b8-213f-4837-9fdf-54855bae8da6.png">  everything is settled.Whether I should configure something on the “idea”

**Comment by debora-ito** [comment] 2022-09-26 18:02
@SakuraLxm I'm sorry but I don't fully understand your question based on the screenshots. If you provide a full reproducible code it may be easier. 
How was the code before? What exactly did you change to?

**Comment by SakuraLxm** [comment] 2022-09-28 03:48
> 
The comment part is the original code, but the current code is not commented

**Comment by debora-ito** [comment] 2022-09-28 18:28
If your application is running in EC2 and InstanceProfileCredentialsProvider is throwing `Connect timed out` it's an indication that the client timed out when connecting to the EC2 IMDS endpoint. 

You can check if the endpoint is reachable from the EC2 instance by manually running  the CURL commands listed here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

If it is not reachable, check the networking configuration of the EC2 instance. 

This is likely not an issue with the SDK, so I'll go ahead and close this. Feel free to reach out if you have any other question.

**Closed by debora-ito** 2022-09-28 18:28 UTC
Labels: guidance
