### ISSUE TITLE
CloudFormation listStacks request does not respect StackStatusFilters anymore

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#551] opened 2015-11-03 20:45 UTC
A listStacks request returns all StackSummaries, regardless of the passed in StackStatusFilters.

This seems to be due a change in [ListStacksRequestMarshaller.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model/transform/ListStacksRequestMarshaller.java#L64) - the current prefix for the added parameters is "stackStatusFilters.member." instead of the previous "StackStatusFilter.member." (lowercase start and added 's').

The change seems to have been introduced with version 1.10.28.

**Comment by sopel** [comment] 2015-11-09 09:16
@shorea - this issue is affecting an increasing number of users of our [Tasks for AWS](https://marketplace.atlassian.com/plugins/net.utoolity.atlassian.bamboo.tasks-for-aws) add-on for Atlassian Bamboo (see [UAA-121](https://utoolity.atlassian.net/browse/UAA-121)). It seems trivial to fix and we just skipped the pull request due to the assumption that it has been introduced by the new code generator for the CloudFormation client, thus suggesting that someone in the know should check for similar regressions introduced by this change.

Given you have quickly fixed https://github.com/aws/aws-sdk-java/issues/552#issuecomment-154588952 and _tentatively scheduled for next Tuesday_, could you please consider addressing this seemingly trivial though severe bug in the upcoming release as well? Thanks much!

**Comment by shorea** [comment] 2015-11-09 16:51
Hey sorry for the lack of response. This has been fixed in the code generator and staged for the next release which is still scheduled for tomorrow. We can also push this out today if it's an urgent issue.

**Comment by sopel** [comment] 2015-11-09 18:53
@shorea - thanks for the update and your offer to escalate the release, much appreciated: if your next release will indeed be pushed out on Tuesday as planned this would be sufficient to schedule our own point release for Wednesday.

**Comment by manikandanrs** [comment] 2015-11-11 01:36
This is fixed in the latest release 1.10.33. https://aws.amazon.com/releasenotes/Java/2423908263921241

**Closed by manikandanrs** 2015-11-11 01:36 UTC
