### ISSUE TITLE
doesTargetMatchNonProxyHosts throws an exception for Docker host

### ISSUE THREAD

**Issue by vladtf** [aws/aws-sdk-java#2970] opened 2023-04-28 09:01 UTC
### Describe the bug

When deploying the APP inside and Docker on AWS ECS when trying to describe the log groups I'm getting an error:
```
\\.\pipe\docker_engine
^: java.util.regex.PatternSyntaxException: Unknown character property name {In/Isi} near index 5
``` 

This error this being thrown from here:
`com.amazonaws.http.apache.SdkProxyRoutePlanner.doesTargetMatchNonProxyHosts(SdkProxyRoutePlanner.java:63)`

Unfortunately it's a closed system so I cannot enter with debug, but I suppose the cause is the http target `\\.\pipe\docker_engine` which is being checked against some non proxy hosts like `localhost`.

The workaround I'm wokring on is to disable non proxy hosts check.

### Expected Behavior

I'm expecting that host `\\.\pipe\docker_engine` should not pass the pattern match, neither to throw an exception.

### Current Behavior

An `PatternSyntaxException` is being thrown.

### Reproduction Steps

1. Quarkus app deployed inside a docker context
2. Have non_proxy_hosts configured in System properties or ENV variables
3. Call an log describe request

### Possible Solution

A possible solution will be to catch this kind of exception `java.util.regex.PatternSyntaxException: Unknown character property name {In/Isi} near index 5` thrown by `java.util.regex.Pattern`.

### AWS Java SDK version used

1.12.429

### JDK version used

Java 11

### Operating System and version

Redhat openjdk minimal11

**Comment by vladtf** [comment] 2023-04-28 09:28
Update: The problem is caused not by the target host but by the non_proxy_host. I could reproduce it locally when providing got `hostPatterns` that docker host:
![image](https://user-images.githubusercontent.com/45298740/235110636-a64d50f7-c511-416f-ac6b-985aa9f76326.png)

**Comment by debora-ito** [comment] 2023-05-02 02:44
[SdkProxyRoutePlanner](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/SdkProxyRoutePlanner.java) is marked as `@SdkInternalApi`, it was meant for internal use so we don't recommend depending on it.

Besides, the cause of the exception are the control characters "\r\n" present in the pattern, which are not valid. This is a valid exception.

**Closed** 2023-05-03 13:49 UTC
Labels: bug, closing-soon
