### ISSUE TITLE
Connection Timeout waiting for connection from pool, while using TransferManager for downloading a file from presigned Url

### ISSUE THREAD

**Issue by nikhilhanda** [aws/aws-sdk-java#2088] opened 2019-08-28 16:27 UTC
I am using TransferManager for downloading a file from its presigned url. Since the max S3 connections are 5. The TransferManager is failing to close the S3connection after downloading the file. In the below code snippet I am downloading a file using a presigned url 50 times in a loop but after 5 successful downloads, the 6th file is not getting downloaded.

      ClientConfiguration clientConfigurationTemplate = new ClientConfiguration();
      clientConfigurationTemplate.setMaxConnections(5);
      clientConfigurationTemplate.setConnectionMaxIdleMillis(100);

      AmazonS3 s3client = AmazonS3ClientBuilder.standard()
          .withEndpointConfiguration(
              new AwsClientBuilder.EndpointConfiguration("https://s3.amazonaws.com/", "us-east-1"))
          .withClientConfiguration(clientConfigurationTemplate)
          .build();

      TransferManager t = TransferManagerBuilder.standard().withS3Client(s3client).withShutDownThreadPools(false).build();

      String presignedUrl = "https://presignedurl";
      URL url = new URL(presignedUrl);
      for (int i = 0; i < 50; i++) {
        String filePath = "TEST"+i;
        final PresignedUrlDownloadRequest presignedUrlDownloadRequest =
            new PresignedUrlDownloadRequest(url);
        PresignedUrlDownload downloadResult = t.download(presignedUrlDownloadRequest, new File(filePath));
        downloadResult.waitForCompletion();
      }

The exception being observed is: 

`Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)`

**Comment by debora-ito** [comment] 2019-08-29 20:39
Is it possible that your downloads are taking more time than the configured connection timeout? For example, when attempting to download the 6th file, all the five connections are still active.

**Comment by nikhilhanda** [comment] 2019-08-31 10:30
No, the downloads are not taking more time than the connection timeout. In the for loop of the above code snippet, it is first downloading a file and waiting for it to get completely downloaded before starting the next download. Once a file is downloaded, the S3 Connection should be released for other download requests. But in this case the connection is not getting released due to which 5 files are downloaded and we run of the S3 connections to process new download requests.

**Comment by debora-ito** [comment] 2019-09-06 00:42
@nikhilhanda I was not able to reproduce the issue. 

Some questions that might help identify the cause:
- Were the 5 downloads completed successfully? 
- What's the size of the file being downloaded?
- Could you provide us the wire logs of the operation? Please make sure there's no sensitive data in it.

Also, is there any particular reason to serialize the downloads, or this is just for testing purposes?

**Comment by nikhilhanda** [comment] 2019-09-06 15:37
Have you tried running the sample code snippet attached above by providing it a pre-signed URL? 
You should be able to reproduce the issue with the above code snippet.

Answers to the 3 questions above:
1. Yes, the 5 files were completely downloaded.
2. Size of the file is ~10 MB.
3. I am not sure whether I would be able to do that.

 Intentionally I did not try to serialize the download. Can you point me to the line of code where it is getting done in the above snippet?

**Comment by debora-ito** [comment] 2019-09-10 16:15
Thank you for the follow-up. I was able to reproduce the issue, will investigate the cause.

**Comment by dagnir** [comment] 2019-09-21 00:13
Looks like the operation leaks a connection causing the connection pool to eventually get exhausted. Will continue to dig into this and get a fix out soon.

**Comment by dagnir** [comment] 2019-09-27 22:22
Hi, the fix for this bug has been released as part of [1.11.641](https://github.com/aws/aws-sdk-java/blob/1.11.641/CHANGELOG.md#amazon-s3). Thanks!

**Closed by dagnir** 2019-09-27 22:22 UTC
Labels: bug, investigating
