### ISSUE TITLE
Kinesis Agent throws InvalidSignatureException due to special chars in access key

### ISSUE THREAD

**Issue by adzdo** [aws/aws-sdk-java#1941] opened 2019-03-14 19:40 UTC
New access key for AWS Firehose was generated with AWS Management Console, the new key included a forward slash.  After updating the config, Kinesis Agent continually threw this send error.  Regenerated a key without any special chars to resolve, but expected any key generated by the Management Console would work with the Kinesis sdk.

2019-03-13 16:03:00.863+0000 ******** (sender-0) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [ERROR] AsyncPublisher[fh:**********:/**/*****/****/****.log]:RecordBuffer(id=2,records=2,bytes=2113) Retriable send error (com.amazonaws.services.kinesisfirehose.model.AmazonKinesisFirehoseException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: InvalidSignatureException; Request ID: *********)). Will retry.

**Comment by debora-ito** [comment] 2019-03-14 23:27
Hi @adzdo, having a forward slash in the access key should not be a problem, as mentioned here: #1425. Can you use the same credentials for other API requests?

Signature not matching can have several causes, it would help if you could provide a sample code for reproduction.

**Comment by adzdo** [comment] 2019-03-15 15:54
Hi @debora-ito, I don't really have code to share, I'm not not directly making API requests - I have a process writing to a log file, and Kinesis Agent set up reading from the log and sending new records to a firehose.  A new secret access key was generated for the access key id I was using, when I restarted the Kinesis Agent using the new secret access key, I started getting the InvalidSignature exceptions, no other change was made.  Switching to a new secret access key, without any specials chars, resolved the InvalidSignature exceptions, so I don't think this is related to policy permissions.  I'm using Kinesis Agent version 1.1, which is packaged with aws-java-sdk version 1.11.28, which I pulled from https://github.com/awslabs/amazon-kinesis-agent.             

The call the precipitates the exception is putRecordBatch, from class, com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.

**Comment by debora-ito** [comment] 2019-03-15 22:25
Amazon Kinesis Agent has its own credential [settings](https://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html#agent-config-settings) and credentials provider, so I'm guessing the issue with slash may be in their implementation. As you said, you are not directly making API requests, so this doesn't look like an issue with the SDK. 

Can you open an issue on the https://github.com/awslabs/amazon-kinesis-agent repo? 

Feel free to reopen this if any further questions come up.

**Comment by adzdo** [comment] 2019-03-19 17:03
https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/AgentAWSCredentialsProvider.java

I can't find any code in the amazon-kinesis-agent source that handles generating signatures.  As far as I can tell, it relies on aws-java-sdk-core for auth, and aws-java-sdk-kinesis for delivering records to a stream, which are both in this repo.

**Comment by debora-ito** [comment] 2019-03-25 19:08
Reopening, as it looks you're not happy with the outcome.

**Comment by debora-ito** [comment] 2019-03-25 23:57
Ok, I still cannot reproduce the issue, and here's what I've tried:

- My secret access key has a forward slash
- Created a Firehose delivery stream through the AWS console, with Direct PUT as source and an S3 bucket as destination
- Executed the following code snippet, based on the `putRecordBatch()` method used by [amazon-kinesis-agent](https://github.com/awslabs/amazon-kinesis-agent):

```java
ProfileCredentialsProvider credentials = new ProfileCredentialsProvider();
try {
    credentials.getCredentials();
} catch (Exception e) {
    throw new AmazonClientException(
            "Cannot load the credentials from the credential profiles file. ", e);
}

AmazonKinesisFirehose firehoseClient =
                new AmazonKinesisFirehoseClient(credentials, new ClientConfiguration());

List<Record> requestRecords = new ArrayList<>();

String PUT_RECORD_STREAM_SOURCE = "putRecordInput.txt";
InputStream inputStream = new FileInputStream(new File(PUT_RECORD_STREAM_SOURCE));

if (inputStream == null) {
    throw new FileNotFoundException("Could not find file " + PUT_RECORD_STREAM_SOURCE); 
}

try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
    String line = null; 
    while ((line = reader.readLine()) != null) {
        String data = line + "\n";
        requestRecords.add(new Record().withData(ByteBuffer.wrap(data.getBytes())));
    }
}

PutRecordBatchRequest request = new PutRecordBatchRequest();
request.setRecords(requestRecords);
request.setDeliveryStreamName(myDeliveryStream);

PutRecordBatchResult result = firehoseClient.putRecordBatch(request);
```

The code is executed with success, I'm not getting any `InvalidSignatureException` error.

Some things we can try next:

1. Kinesis agent is using a really old version of the SDK (`1.11.28`), could you please try executing the agent with a newer version? The latest version is `1.11.524`
2. I noticed the Kinesis Agent also uses [Kinesis and CloudWatch clients](https://github.com/awslabs/amazon-kinesis-agent/blob/627d2269811ef80161e5873baa59f86c035a517d/src/com/amazon/kinesis/streaming/agent/AgentContext.java#L173-L198), using the same method to load the AWSCredentialsProvider. Are you also having issues with the Kinesis or CloudWatch APIs? If not, the signature calculation is working fine then.

**Comment by adzdo** [comment] 2019-03-26 16:07
Sorry didn't realize the sdk version the master kinesis-agent branch is using was that old.  I tested with an access key containing a forward slash, using aws-java-sdk version 1.11.524, and the agent passes auth without error.  I'll open an issue in their repo to address.  Thanks.

**Comment by debora-ito** [comment] 2019-03-27 17:35
Glad we were able to determine the cause of the issue. Closing this, feel free to reopen if you have further questions.

**Closed by debora-ito** 2019-03-27 17:35 UTC
Labels: guidance, response-requested
