### ISSUE TITLE
AWS Java SDK not supporting environment variable override

### ISSUE THREAD

**Issue by johannesfloriangeiger** [aws/aws-sdk-java#3105] opened 2024-04-15 08:04 UTC
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the feature

The AWS CLI supports overriding e.g. the endpoint via parameters

```
aws s3 ls --endpoint-url http://localhost:4566
```

or

```
AWS_ENDPOINT_URL=http://localhost:4566 aws s3 ls
```

meanwhile the Java SDK does not consider environment variables, see e.g. the following minimal example

```
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import software.amazon.awssdk.services.s3.S3Client;
import uk.org.webcompere.systemstubs.environment.EnvironmentVariables;
import uk.org.webcompere.systemstubs.jupiter.SystemStub;
import uk.org.webcompere.systemstubs.jupiter.SystemStubsExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SystemStubsExtension.class)
class S3FacadeTest {

    @SystemStub
    private EnvironmentVariables environmentVariables = new EnvironmentVariables("AWS_ENDPOINT_URL", "http://localhost:4566");

    @Test
    void testGetContent() {
        assertEquals("http://localhost:4566", System.getenv("AWS_ENDPOINT_URL"));

        try (final var s3Client = S3Client.create()) {
            final var listBucketsResponse = s3Client.listBuckets();
            listBucketsResponse.buckets().forEach(System.out::println);
        }
    }
}
```

which makes use of System Stubs

```
        <dependency>
            <groupId>uk.org.webcompere</groupId>
            <artifactId>system-stubs-jupiter</artifactId>
            <version>2.1.3</version>
            <scope>test</scope>
        </dependency>
``` 

and which leads to a `software.amazon.awssdk.services.s3.model.S3Exception: The provided token has expired.` because the SDK by default uses the `default` profile of the local AWS credentials file despite the overridden endpoint.

### Use Case

Overriding the endpoints for local testing.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.24.5

### JDK version used

17

### Operating System and version

Mac OS Sonoma

**Comment by debora-ito** [comment] 2024-04-15 20:07
Hi @johannesfloriangeiger this is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/4501, please use that issue to track progress.

**Closed by debora-ito** 2024-04-15 20:07 UTC
Labels: feature-request, duplicate
