### ISSUE TITLE
Select Object Content doesn't return the fields for NULL values

### ISSUE THREAD

**Issue by abhiupadhyay** [aws/aws-sdk-java#2576] opened 2021-05-18 14:49 UTC
We are trying to get the content of a Parquet file, where few of the column can have null values, When We use the output serialization as JSON, We get the JSON String containing only NOT_NULL columns.

## Describe the bug
I have a sample parquet file with below schema. It contains only one row for simplicity, which has first_name as 'test_first_name'  and last_name as NULL. I tried getting the content via select-object-content command in AWS CLI or via JAVA Code using AWS SDK using Output Serialization as JSON. I get the content as JSON string for this file but the JSON contains only 'first_name' field.
 
`{
  "type" : "record",
  "name" : "schema",
  "fields" : [ {
    "name" : "first_name",
    "type" : [ "null", "string" ],
    "default" : null
  }, {
    "name" : "last_name",
    "type" : [ "null", "string" ],
    "default" : null
  } ]
}`

## Expected Behavior
It should return me all the Columns in JSON irrespective of whether they are having NULL or NOT_NULL values.

## Current Behavior
It only returns NOT_NULL Column as Key-Value in JSON.

## Steps to Reproduce
1) Unzip the attached Parquet-ZIP.zip and upload the parquet file present in it to a S3 bucket.
[Parquet-ZIP.zip](https://github.com/aws/aws-sdk-java/files/6502079/Parquet-ZIP.zip)

2) GET the latest AWS CLI and run the below command.
` aws s3api select-object-content     --bucket <your_bucket_name>     --key sample-parquet.parquet     --expression "select * from s3object s limit 1"     --expression-type 'SQL'     --input-serialization '{"Parquet": {}}'     --output-serialization '{"JSON": {}}' "output.json"`

3) Open the output.json and observe it contains only 'first_name' field.

## Context
We are trying to show the parquet files in a tabular format. To achieve this first we prepare the column list by fetching a single row and then map values to it by fetching the further rows. If our parquet is having two columns for example, and first row is having first column as NOT NULL and second column as NULL & Second row is having both Columns as NOT NULL. Then we get only the first column in our column list due to this issue which leads us to skip the value of Second Column in Second row also. It would have become very simple if AWS SDK returns us the all the columns in a JSON irrespective of their values.

## Your Environment

* AWS Java SDK version used: 1.11.1020
* AWS CLI Version: 2.2.5.0
* JDK version used: 11
* Operating System and version: Windows 10

**Comment by debora-ito** [comment] 2021-05-18 18:26
Hi @abhiupadhyay Are you seeing the same issue when using the Java SDK? Your reproduction steps only include a AWS CLI command.

**Comment by abhiupadhyay** [comment] 2021-05-19 05:01
Hi @debora-ito , Yes the behavior is same for SDK as well. Below is the code snippet of how we prepare the SelectObjectContentRequest.

`SelectObjectContentRequest request = new SelectObjectContentRequest();
        request.setBucketName(bucketName);
        request.setKey(objectKey);
        request.setExpression("select * from s3object s limit 1");
        request.setExpressionType(ExpressionType.SQL);
        InputSerialization inputSerialization = new InputSerialization();
        inputSerialization.setParquet(new ParquetInput());
        request.setInputSerialization(inputSerialization);
        OutputSerialization outputSerialization = new OutputSerialization();
        outputSerialization.setJson(new JSONOutput());
        request.setOutputSerialization(outputSerialization);`

**Comment by debora-ito** [comment] 2021-05-21 02:06
HI @abhiupadhyay I believe this is the expected behavior by S3 Select. Running the same query in the AWS Console the result is:
```
{
  "first_name": "test_first_name"
}
```

**Comment by debora-ito** [comment] 2021-05-21 02:16
Changing the expression to `SELECT first_name, last_name FROM s3object s LIMIT 5` the result is:
```
{
  "first_name": "test_first_name",
  "last_name": null
}
```

Let us know if you have any more questions.

**Comment by abhiupadhyay** [comment] 2021-05-21 09:55
Hi @debora-ito , I can't use the columnNames in the Select Query because by using the `select * from s3object s limit 1` query, I am trying to prepare a column list hence I have to go with *.

Referring to this StackOverFlow [post](https://stackoverflow.com/questions/55693870/aws-s3-select-skips-missing-values-in-result-set ), there was a similar problem with CSV Output serialization as well, but it was fixed. Similar problem still persist with JSON Output serialization.

**Comment by debora-ito** [comment] 2021-05-22 01:16
In the stackoverflow link, the expression filed lists all the columns in  `SELECT s.A, s.B, s.C`  instead of using asterisk `SELECT *`.

But I see how this behavior is confusing, I'll reach out to the S3 Select team and ask for clarification. Will update here when I hear back.

**Comment by abhiupadhyay** [comment] 2021-05-24 05:07
@debora-ito - Thank you! Please let me know once you hear from them.

**Comment by abhiupadhyay** [comment] 2021-06-01 04:13
Hi @debora-ito , Did we hear anything back?

**Comment by abhiupadhyay** [comment] 2021-06-08 16:31
Hi @debora-ito any updates on this?

**Comment by debora-ito** [comment] 2021-06-08 22:52
Yes! I heard back from the service team, and they said this is the expected behavior for JSON output. If you want the schema you can try using CSV, just be careful because select does not support converting from Parquet to CSV if the input data format has nested data types.

I asked them to update the documentation to make clear this is the intended behavior. Let me know if you have more questions, otherwise marking this to auto resolve soon.

**Comment by abhiupadhyay** [comment] 2021-06-09 04:33
@debora-ito  - Having Output Serialization as CSV won't give me the Column Name hence i won't be able to get the schema on parquet.
withFileHeaderInfo comes only with the CSVInput and for a parquet file, SDK expects input serialization as ParquetInput.

Please let me know your thoughts on this.

**Comment by debora-ito** [comment] 2021-06-15 17:19
Since the behavior was confirmed as expected by the service team, if you'd like to I can request them a new feature to add the option to return null values in JSON outputs.

**Comment by abhiupadhyay** [comment] 2021-06-15 17:29
@debora-ito - It will be very helpful if we can do this. As we are loosing some information here if the Parquet rows has null column value.

**Comment by abhiupadhyay** [comment] 2021-06-21 07:58
@debora-ito - Did you get any update on this?

**Comment by debora-ito** [comment] 2021-06-22 00:25
Hi @abhiupadhyay I've reached out to them with the feature request, no updates yet. When I hear something back I'll add a comment here.

**Comment by abhiupadhyay** [comment] 2021-06-22 05:17
Sure Thank you @debora-ito

**Comment by debora-ito** [comment] 2021-08-02 17:32
@abhiupadhyay the service team acknowledged the feature request and they've added to their backlog.

Since there's no more pending actions on the Java SDK side, I'll go ahead and close this.

**Closed by debora-ito** 2021-08-02 17:32 UTC
Labels: feature-request, service-api

**Comment by marripavan11** [comment] 2022-04-05 10:35
@debora-ito any update on the backlog? Is it released?
