### ISSUE TITLE
aws-java-sdk-s3 depends on the wrong version of aws-java-sdk-kms

### ISSUE THREAD

**Issue by vromero** [aws/aws-sdk-java#790] opened 2016-07-27 07:31 UTC
+-xxx:xxx:1.0.0-SNAPSHOT
      +-com.amazonaws:aws-java-sdk:1.11.21
        +-com.amazonaws:aws-java-sdk-s3:1.10.30
          +-com.amazonaws:aws-java-sdk-kms:1.10.30
    and
    +-xxx:xxx:1.0.0-SNAPSHOT
      +-com.amazonaws:aws-java-sdk:1.11.21
        +-com.amazonaws:aws-java-sdk-kms:1.11.21

It becomes obvious when running a maven build using the enforcer plugin:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-enforcer-plugin</artifactId>
    <version>1.4.1</version>
    <executions>
        <execution>
            <id>enforce-banned-dependencies</id>
            <goals>
                <goal>enforce</goal>
            </goals>
            <configuration>
                <rules>
                    <dependencyConvergence/>
                </rules>
                <fail>true</fail>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by shorea** [comment] 2016-07-27 15:49
It looks consistent when looking at the pom. https://github.com/aws/aws-sdk-java/blob/cf8422ac37418e9f9f0c2863463d2bed2683503a/aws-java-sdk-s3/pom.xml#L18

**Comment by vromero** [comment] 2016-07-27 19:20
If you take a closer look to the tree you'll see that the problem is the SDK having transitive dependencies to the wrong S3 version:

```
+-com.amazonaws:aws-java-sdk:1.11.21
    +-com.amazonaws:aws-java-sdk-s3:1.10.30
```

**Comment by shorea** [comment] 2016-07-28 19:08
I'm not able to reproduce locally. Could you try cleaning our local maven repository? Do any of you other dependencies pull in a different version of an SDK module?

Here's my pom for reference, the only conflict I had to resolve was commons-logging
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.shorea</groupId>
    <artifactId>sandbox</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.20</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.4.1</version>
                <executions>
                    <execution>
                        <id>enforce-banned-dependencies</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <dependencyConvergence/>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>1.2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
```

**Comment by vromero** [comment] 2016-08-03 21:58
Apologies, on the road, will take a look next week.

**Comment by shorea** [comment] 2016-08-26 05:05
Closing this issue for now. If it's still a problem feel free to reopen.

**Closed by shorea** 2016-08-26 05:05 UTC
Labels: waiting-reply

**Comment by tmack8001** [comment] 2018-02-06 00:35
This is still a problem with the 1.11.246 sdk versions...

```
$ mvn dependency:tree | grep aws-java-sdk-kms -C 3
[INFO] |  |  \- joda-time:joda-time:jar:2.9.9:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.125:compile
[INFO] \- com.amazonaws:aws-java-sdk-s3:jar:1.11.246:compile
[INFO]    \- com.amazonaws:aws-java-sdk-kms:jar:1.11.125:compile
```
