### ISSUE TITLE
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 

### ISSUE THREAD

**Issue by SushmaReddyLoka** [aws/aws-sdk-java#2285] opened 2020-04-07 06:38 UTC
After upgrading version of aws sdk  from 1.11.526 to 1.11.740  we are seeing issue in invoking lambda function with below stack trace.

com.amazonaws.SdkClientException: Failed to connect to service endpoint:
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:47) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:166) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:111) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1251) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:827) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:777) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524) ~[aws-java-sdk-core-1.11.740.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3935) ~[aws-java-sdk-lambda-1.11.740.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3902) ~[aws-java-sdk-lambda-1.11.740.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3891) ~[aws-java-sdk-lambda-1.11.740.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:2180) ~[aws-java-sdk-lambda-1.11.740.jar:?]
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:2151) ~[aws-java-sdk-lambda-1.11.740.jar:?]
	... our stack followed by
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_171]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_171]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_171]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_171]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_171]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_171]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_171]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:82) ~[aws-java-sdk-core-1.11.740.jar:?]
	... 39 more

We are invoking aws lambda from a java application which runs inside ec2 instance, using aws sdk  "aws-java-sdk-lambda". 

Wondering if this is an known regression from aws sdk side or do you suspect any ec2 instance configuration.
This error was never seen before sdk version upgrade . 
This lambda invocation fails on few ec2 instances and goes through fine on others.

**Comment by zoewangg** [comment] 2020-04-13 22:02
Hi, @SushmaReddyLoka the transient errors could be caused by the SDK support for [IMDS v2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) released a while ago.

The error is retryable but unfortunately, we can't implement retry for IMDS credentials fetching for backwards compatibility reasons, so we recommend implementing your own retry strategy for `InstanceProfileCredentialsProvider` in this case.

**Comment by debora-ito** [comment] 2020-04-20 17:13
Closing this, feel free to reopen if you have any questions.

**Closed by debora-ito** 2020-04-20 17:13 UTC
Labels: closing-soon, guidance

**Comment by telebh** [comment] 2020-09-15 01:47
I used to use AWS Java SDK 1.11.23, it worked fine with EnvironmentVariableCredentialsProvider() and ProfileCredentialsProvider. Today I have updated SDK to version 1.11.723, but I can't connect to AWS services like SNS getting exception :

xception in thread "main" com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)
	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)
	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)
	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:166)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1251)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:827)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:777)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.sns.AmazonSNSClient.doInvoke(AmazonSNSClient.java:2270)
	at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2246)

**Comment by shambhand** [comment] 2020-09-28 10:24
Facing the same issue intermittently with AWS SDK v1.11.788 on kubernetes cluster trying to connect using Kube2Iam

**Comment by ffeltrinelli** [comment] 2022-04-08 18:37
Hi! I talked about this issue and described our custom solution [in this article](https://medium.com/expedia-group-tech/service-slow-to-retrieve-aws-credentials-ebc02a38e95b).

**Comment by edencorbin** [comment] 2023-05-09 12:13
Hey wow, maybe this is totally different then others, but I was instantiating a AWSCognitoIdentityProviderClientBuilder and getting this error, adding .withRegion(Regions.US_WEST_2) fixed it for me.

**Comment by KushalKhajuria** [comment] 2023-12-27 20:18
Yup! Adding .withRegion(Regions.US_WEST_2) solved the problem for me too! Thanks.

**Comment by amzar96** [comment] 2024-12-06 09:07
Hi, I faced the same issue `com.amazonaws.SdkClientException: Failed to connect to service endpoint:`

```bash
com.amazonaws.SdkClientException: Failed to connect to service endpoint:
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:112)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:407)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:376)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:287)
```

I am using Pyspark btw. 

```python
df.write.format("io.github.spark_redshift_community.spark.redshift").option(
    "url",
    "jdbc:redshift://{host}:{port}/{database}".format(
        host=self._host, port=self._port, database=self._database
    ),
).option("dbtable", f"{schema}.{table}").option(
    "tempdir",
    f"s3a://{self.s3_temp_bucket}/{self.s3_temp_key}/{self._database}/{self._result_schema}/{table}/",
).option(
    "user", self._user
).option(
    "password", self._password
).option(
    "include_column_list", True
).option(
    "extracopyoptions", "TIMEFORMAT 'auto' DATEFORMAT 'auto' TRUNCATECOLUMNS"
).option(
    "temporary_aws_access_key_id", self._s3_access_key
).option(
    "temporary_aws_secret_access_key", self._s3_secret_key
).option(
    "temporary_aws_session_token", self._s3_token
).option(
    "region", "ap-southeast-1"
).mode(
    "append"
).save()
```

I already passed the region.
