### ISSUE TITLE
Is there a programmatic way to get the EKS cluster token using java aws sdk

### ISSUE THREAD

**Issue by srinivasev** [aws/aws-sdk-java#2738] opened 2022-04-14 10:41 UTC
### Describe the bug

**This is a guidance ticket --**

I want to get the EKS cluster token programmatically using java aws sdk code. I couldn't find it in the samples code section. Below details are available with me for generating the token.

`aws_access_key_id, aws_secret_access_key, aws_session_token, region, cluster-name`

Kindly help,

### Expected Behavior

Please provide any code example which can generate the token and can be used in the kube-config file for accessing the cluster.

### Current Behavior

NA

### Reproduction Steps

NA

### AWS Java SDK version used

1.12.197

### JDK version used

1.8

### Operating System and version

Linux

**Comment by debora-ito** [comment] 2022-04-14 16:56
Duplicate of https://github.com/aws/aws-sdk-java/discussions. Closing.

**Closed by debora-ito** 2022-04-14 16:56 UTC
Labels: duplicate, guidance
