### ISSUE TITLE
Release process of the SDK temporarily breaks maven/gradle builds using latest.release

### ISSUE THREAD

**Issue by paulbakker** [aws/aws-sdk-java#2956] opened 2023-04-12 17:50 UTC
### Describe the bug

We notice every time the SDK gets released, there is a time period of a few hours where the new version is found by Gradle, but the artifacts haven't finished syncing to maven central yet.

Builds that rely on some sort of `latest.release` mechanism (or `1.+`) fail with an error that the artifacts can't be downloaded.

I think the issue might be that POMs get published before the actual artifacts.

### Expected Behavior

Once a new version is found by Maven/Gradle, it should be able to successfully use this version.

### Current Behavior

Failed downloads in Gradle/Maven for the newly published SDK version, for a few hours until syncing is completed.

### Reproduction Steps

Publish a new SDK version and immediately try to use this version in a Gradle/Maven build (with maven central).

### AWS Java SDK version used

Affects both 1.x and 2.x

### JDK version used

17

### Operating System and version

macos

**Comment by debora-ito** [comment] 2023-04-13 17:26
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/3882.

There's not a lot the Java SDK team can do to improve the experience, this is mostly on the Sonatype side.
Please track the progress of the issue open to the Sonatype team, reference is in the other Github issue.

**Closed by debora-ito** 2023-04-13 17:26 UTC
Labels: guidance
