### ISSUE TITLE
JSON parse error while handling error response

### ISSUE THREAD

**Issue by mwm-twx** [aws/aws-sdk-java#821] opened 2016-08-23 19:05 UTC
While trying to create a thing with the AWSIotClient, I received this stacktrace.  It appears to be receiving HTML when only JSON is expected.

``` java
14:02:00.987 [NettyClient-NIO-3] INFO  c.a.http.JsonErrorResponseHandler - Unable to parse HTTP response content
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@239a4a9e; line: 1, column: 2]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2610) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737) ~[jackson-core-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3742) ~[jackson-databind-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3687) ~[jackson-databind-2.6.1.jar:2.6.1]
    at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2285) ~[jackson-databind-2.6.1.jar:2.6.1]
    at com.amazonaws.http.JsonErrorResponseHandler$JsonContent.parseJsonContent(JsonErrorResponseHandler.java:179) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.JsonErrorResponseHandler$JsonContent.<init>(JsonErrorResponseHandler.java:169) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.JsonErrorResponseHandler$JsonContent.createJsonContent(JsonErrorResponseHandler.java:162) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:64) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:36) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1346) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:923) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:701) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:453) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:415) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:364) [aws-java-sdk-core-1.11.14.jar:na]
    at com.amazonaws.services.iot.AWSIotClient.doInvoke(AWSIotClient.java:3609) [aws-java-sdk-iot-1.11.14.jar:na]
    at com.amazonaws.services.iot.AWSIotClient.invoke(AWSIotClient.java:3579) [aws-java-sdk-iot-1.11.14.jar:na]
    at com.amazonaws.services.iot.AWSIotClient.createThing(AWSIotClient.java:973) [aws-java-sdk-iot-1.11.14.jar:na]
```

**Comment by spfink** [comment] 2016-08-23 23:36
Can you provide any sample code that reproduces this error? Based on the stacktrace this is occurring when IoT is returning back an error on your original request and not on a successful request.

**Comment by fernomac** [comment] 2016-08-24 00:09
Perhaps you're not setting a thing name, or setting it to the empty string?

[linky](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iot/src/main/java/com/amazonaws/services/iot/model/transform/CreateThingRequestMarshaller.java#L70)

AWS services that pass parameters in the URI path get grumpy in "exciting" ways if you leave any of those parameters out. :( There was talk at some point about checking for this on the client side whenever a parameter is mapped to the URI path - it's a bit of a hack, but the alternative is ... this (or worse, if you end up matching the URI pattern for some other operation and the request goes through but does the wrong thing).

**Comment by steveloughran** [comment] 2016-08-28 11:10
presumably the client is checking the return type is JSON or XML as appropriate before attempting to parse it?

**Comment by mwm-twx** [comment] 2016-09-08 14:36
@fernomac, this error was seen while running automated tests, so it's not an issue with the thing-name.  These tests do not normally cause this error and the true cause is hidden by the parse error, so I can't say what went wrong.

It may have been a transient issue on an AWS service, but the issue here is an assumption of receiving JSON as a response format which ends up masking the real error cause.

**Comment by mnesbitt** [comment] 2016-12-12 13:56
I have been seeing this error as well, except mine is coming from the AmazonDynamoDBStreamsClient. I was able to debug and see the raw content (expected to be JSON) as:

"<html><body><b>Http/1.1 Service Unavailable</b></body> </html>"

Seems the AmazonHttpClient is expecting this response to always be JSON.

**Comment by steveloughran** [comment] 2016-12-12 17:16
This could actually be a repetition of a classic SOAP stack bug: failing to check the return code or content type before trying to parse the XML document. I remember [exploring their ability to handle 302 and text/html](http://www.xml.com/pub/a/ws/2003/10/28/sitefinder.html) in those few weeks in 2003 when Verisign had all of .com redirecting to a search page on a DNS failure.

It's important to check for this stuff, not just because of verisign, verizon and other "helpful" ISPs, but because enterprise firewalls and proxies can get in the way too. 

Anyway, nothing I can do about this; we'll mention it in the hadoop s3a docs if someone is willing to add it to the troubleshooting section

**Comment by shorea** [comment] 2017-01-25 15:57
Resolving this issue. The SDK handles errors more robustly now and preserves the HTTP content when we can't parse it. If the problem still persists please contact the IoT service team to determine why they are sending HTML instead of JSON.

**Closed by shorea** 2017-01-25 15:57 UTC
