### ISSUE TITLE
FIFO SQS does not consume messages in "Order"

### ISSUE THREAD

**Issue by smartrchauhan** [aws/aws-sdk-java#1400] opened 2017-11-28 22:05 UTC
#### MaxNumberOfMessage - I am using this property to restrict messages want to consume but it does not work as expected; Following cases i tested:-

1. I removed maxNumberOfMessage and still it was consuming 10 messages while in documentation it says If we we are not setting this property then default value will be 1.
2. Suppose i put following 10 messages in FIFO SQS:-
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    then it consume all messages and return the list but result i see in descending order, here is the example results:-
10, 9, 8, 7, 6, 5, 4, 3, 2, 1 
So it just inverse the list in result and once i get the 0 index value so it gives the value i put at last.
3. If I set explicitly 1 into maxNumberOfMessage and publish following 10 messages in SQS:-
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
then it does return just one element is 10 so it still seems to consuming all 10 messages and since we ask to return one element only so it does list.get(0) and as per bullet #3 it has the inverse list so 10 is on index 0.

Here is my code to consume the FIFO SQS:-

```
 ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest();
 
        receiveMessageRequest.setQueueUrl("sampleQueueURL");
         receiveMessageRequest.setMaxNumberOfMessages(1);
         receiveMessageRequest.setWaitTimeSeconds(10);
 
         ReceiveMessageResult result = amazonSqsClient
                                                     .receiveMessage(receiveMessageRequest);
 
         List<Message> messages = result.getMessages();
```
I am using following versions:-
- Amazon SDK Version - 1.11.125
- Java Version - 1.8

Please let me know if i am missing anything in the code. Hoping really quick reply as it is something we are stuck and stoping our actual release.

Thank you in advance.
Rambrij Chauhan

**Comment by varunnvs92** [comment] 2017-11-29 23:24
I tested the cases you mentioned multiple times and following is the behavior I observed.

>> I removed maxNumberOfMessage and still it was consuming 10 messages while in documentation it says If we we are not setting this property then default value will be 1.

Without maxNumberOfMessage, I never got a messages list with size greater than 1. Sometimes I see 0 messages and sometimes I saw 1 message. Never more than that.

>> So it just inverse the list in result and once i get the 0 index value so it gives the value i put at last.

Again I saw the exact opposite behavior of what you mentioned. I uploaded messages with '1' and '2' body. Everytime I got message '1' first and then '2' which is the expected FIFO behavior.

I used the 1.11.231 version. My guess is that there might be a bug in your program where you upload the numbers in reverse order. Do you mind sharing your code? (make sure there is no sensitive data).

**Comment by smartrchauhan** [comment] 2017-11-30 15:03
Hi Varun,

I am not putting values using any program but feeding sqs manually by using amazon console. I am putting all 1 t0 10 in amazon sqs then running my consumer. Code is given above in details. 

Could you please have a look my consumer code above and let me know if i am missing anything.

Thanks
Rambrij

**Comment by smartrchauhan** [comment] 2017-11-30 15:20
Ok So i tested with standalone sqs project without using spring and it seems to be working, do you know if there is any bug in spring boot (spring-cloud-starter-aws-messaging) with amazon. Because i feel like whenever i am using spring boot it does throw the behaviour mentioned above.

**Comment by varunnvs92** [comment] 2017-11-30 18:40
@smartrchauhan 
I have not used sprint boot and have not heard about this behavior before. As you mentioned this bug is only seen with spring boot, better to post the question in stack-overflow or spring boot communities for quicker resolution.

**Comment by varunnvs92** [comment] 2017-12-06 05:09
Closing as the issue is in the sprint boot application and not related to the SDK. Feel free to reopen if you have more questions related to Java SDK. Thank you.

**Closed by varunnvs92** 2017-12-06 05:09 UTC
Labels: waiting-reply
