### ISSUE TITLE
MD5DigestCalculatingInputStream fails with CloneNotSupportedException

### ISSUE THREAD

**Issue by Gilis95** [aws/aws-sdk-java#1192] opened 2017-06-10 06:50 UTC
I've got a problem with usage of AWS in java. Here are scenarios:

**First attempt:**
   

    private void multipartUpload(String bucket, String fileName, File tempFile, ObjectMetadata metadata)
            throws AmazonClientException, InterruptedException, IOException {
        // Create request to upload a part.
        List<PartETag> partETags = new ArrayList<>();
    
        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new
                InitiateMultipartUploadRequest(bucket, fileName);
        InitiateMultipartUploadResult initResponse =
                mS3Client.initiateMultipartUpload(initRequest);
    
        long currentFilePosition = 0;
        long contentLength = tempFile.length();
        long partSize = UploadConfigHelper.CHUNK_SIZE_FOR_MULTIPART_UPLOADS;
    
        for (int i = 0; currentFilePosition < contentLength; i++) {
    
            ResettableInputStream inputStream = newResettableInputStream(tempFile);
            inputStream.skip(currentFilePosition);
    
            // Last part can be less than 5 MB. Adjust part size.
            partSize = Math.min(partSize, (contentLength - currentFilePosition));
    
    
            // Create request to upload a part.
            UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucket).withKey(fileName)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(i)
                    .withFileOffset(currentFilePosition)
                    .withInputStream(inputStream)
                    .withPartSize(partSize);
    
            // Upload part and add response to our list.
            partETags.add(mS3Client.uploadPart(uploadRequest).getPartETag());
    
            inputStream.close();
            currentFilePosition += partSize;
    
        }
    
        CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucket, fileName,
                initResponse.getUploadId(), partETags);
    
        mS3Client.completeMultipartUpload(compRequest);
    }

**Which fails with next:**

  

      Caused by: java.lang.IllegalStateException: unexpected
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.cloneFrom(MD5DigestCalculatingInputStream.java:54)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.mark(MD5DigestCalculatingInputStream.java:66)
    at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:96)
    at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:96)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:681)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
    at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3043)
    at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3028)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.multipartUpload(AmazonS3ConnectorImpl.java:414)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.upload(AmazonS3ConnectorImpl.java:322)
    ... 88 more
    
    
    Caused by: java.lang.CloneNotSupportedException
    at java.security.MessageDigest$Delegate.clone(MessageDigest.java:571)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.cloneFrom(MD5DigestCalculatingInputStream.java:52)
    ... 100 more

Second attempt:

    private void multipartUpload(String bucket, String fileName, File tempFile, ObjectMetadata metadata)
            throws AmazonClientException, InterruptedException, IOException {
        // Create request to upload a part.
        List<PartETag> partETags = new ArrayList<>();

        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new
                InitiateMultipartUploadRequest(bucket, fileName);
        InitiateMultipartUploadResult initResponse =
                mS3Client.initiateMultipartUpload(initRequest);

        long currentFilePosition = 0;
        long contentLength = tempFile.length();
        long partSize = UploadConfigHelper.CHUNK_SIZE_FOR_MULTIPART_UPLOADS;
        /** File content represent as byte array */
        byte[] content = Files.readAllBytes(tempFile.toPath());

        for (int i = 0; currentFilePosition < contentLength; i++) {

            ResettableInputStream inputStream = newResettableInputStream(tempFile);
            inputStream.skip(currentFilePosition);

            // Last part can be less than 5 MB. Adjust part size.
            partSize = Math.min(partSize, (contentLength - currentFilePosition));

            String md5 = new String(content)
                    .substring((int) currentFilePosition, (int) (currentFilePosition + partSize));

            // Create request to upload a part.
            UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucket).withKey(fileName)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(i)
                    .withFileOffset(currentFilePosition)
                    .withInputStream(inputStream)
                    .withMD5Digest(Md5Utils.md5AsBase64(md5.getBytes()))
                    .withPartSize(partSize);

            // Upload part and add response to our list.
            partETags.add(mS3Client.uploadPart(uploadRequest).getPartETag());

            inputStream.close();
            currentFilePosition += partSize;

        }

        CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucket, fileName,
                initResponse.getUploadId(), partETags);

        mS3Client.completeMultipartUpload(compRequest);
    }

**Which fails with next**

    Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: The target server failed to respond
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:724)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
    at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3043)
    at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3028)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.multipartUpload(AmazonS3ConnectorImpl.java:420)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.upload(AmazonS3ConnectorImpl.java:322)
    ... 88 more
    Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
    at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:875)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:715)
    ... 96 more

**P.S:**
Reason why I'm trying to sum MD5 is that otherwise aws wrap my input stream or file ,which transform, into MD5DigestCalculatingInputStream and tries to clone it which leads to error, I've already hit that problem into single upload and worked it around by passing md5 to upload method which leads to skip srtream wrapping. I am looking for way to pass again the md5 or to find why streams tries to clone or why exception is not handled.
I am testing against both Ceph and Official Amazon S3.

**Java Version** : 1.8.0_121-b13
**AWS Version** : 1.11.30

Thanks in advance.

**Comment by millems** [comment] 2017-09-25 22:57
Sorry about the delay on this. The `CloneNotSupportedException` here seems to indicate that you're using a security provider that returns non-cloneable message digests. At minimum, we should give a better error message.  Do you know which security provider you are currently using?

**Comment by Gilis95** [comment] 2017-09-26 05:30
Yes that was the problem our first provider was an old version of certicom
which was providing a non clonable  version of this stream. There is
already default implementation of java but for some reason due to certicom
it was failing. So we make Bouncy Castle first one and it was not failing,
but due to security reasons we cannot replace Certicom with Bouncy Castle.
Our temporary solution is to turn off local md5 sum calculation. Thanks for
response.

На 26.09.2017 г. 1:57 пр.об. "millems" <notifications@github.com> написа:

**Comment by millems** [comment] 2017-09-26 16:49
Sorry about the inconvenience. This is a bit challenging for us to handle, because to support mark/reset we need to be able to copy the message digest along with its current state so that if we reset the stream, we can go back to the checksum state where it was marked. There's no guaranteed-present way of performing this copy.

I'll see if I can come up with anything as a workaround, but at a minimum I'll make the exception message let people know what's wrong.

**Comment by millems** [comment] 2017-09-26 17:25
I'm actually not able to reproduce the problem on the latest version of the SDK. Feel free to try upgrading to see if it helps fix your problem!

**Comment by Gilis95** [comment] 2017-09-26 17:47
Ok, thanks.

На 26.09.2017 г. 8:26 сл.об. "millems" <notifications@github.com> написа:

**Comment by millems** [comment] 2017-09-26 19:17
I was wrong - I was able to reproduce it locally when using a resettable input stream. I'll see about updating the MD5 input stream to disable support for mark-and-reset if the digest isn't cloneable. It will hurt the SDK's ability to retry the request, but it will at least not entirely block it.

**Comment by millems** [comment] 2017-09-28 19:29
A change has been made to mitigate this issue that should be rolled out in the next few days. The SDK will attempt to clone the digest when the input stream is created. If it fails, the stream will be marked as not supporting mark/reset.

**Closed by millems** 2017-09-28 19:29 UTC
Labels: Question

**Comment by Gilis95** [comment] 2017-09-28 20:19
Thanks very much!

На 28.09.2017 г. 10:29 сл.об. "millems" <notifications@github.com> написа:
