### ISSUE TITLE
Using DAX client to initialize AmazonDynamoDB object

### ISSUE THREAD

**Issue by uzokirov** [aws/aws-sdk-java#1454] opened 2018-01-19 22:02 UTC
import com.amazonaws.PredefinedClientConfigurations;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.dax.AmazonDax;
import com.amazonaws.services.dax.AmazonDaxClientBuilder;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;

AmazonDax client = AmazonDaxClientBuilder.standard().withClientConfiguration(PredefinedClientConfigurations.dynamoDefault())
    		    		                                              .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("some endpoint", "some region"))
    		    		                                              .withCredentials(new AWSStaticCredentialsProvider("Some AWSCredentials"))
    		    		    		                                      .build();

How can I use it to instantiate AmazonDynamoDB instance?

**Comment by spfink** [comment] 2018-01-19 22:34
Why do you need a AmazonDynamoDB instance? Dax should replace the need for an AmazonDynamoDB client. The operations should all be the same.

**Comment by uzokirov** [comment] 2018-01-20 00:25
I have an existing code that relies on existence of AmazonDynamoDB or equivalent interface. What I get is AmazonDax object, not AmazonDaxClient. I have added this package:

	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-dax</artifactId>

version 1.11.267

however I can't seem to resolve references to

com.amazon.dax.client.dynamodbv2.AmazonDaxClient;
com.amazon.dax.client.dynamodbv2.ClientConfig;
com.amazon.dax.client.dynamodbv2.ClusterDaxClient;

**Comment by spfink** [comment] 2018-01-20 00:55
The Dax module in this SDK is more of a control plane for configuring Dax. If you would like to use Dax to actually communicate with your tables and data in DynamoDB you need to following the instructions here:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.html

It is not included in the SDK.

**Comment by uzokirov** [comment] 2018-01-22 17:36
Is there a maven artefact for DAX client API?

**Comment by shorea** [comment] 2018-01-22 18:57
@uzokirov I'm not sure, I'll ask the DynamoDB team and get back to you.

**Comment by shorea** [comment] 2018-01-24 21:52
Spoke with the DAX team, unfortunately there is no Maven artifact yet. The team has it on their roadmap but they don't have a tentative date yet. If I hear more information I'll let you know but in the meantime I'll close this issue.

**Closed by shorea** 2018-01-24 21:52 UTC
Labels: Question

**Comment by dulaja** [comment] 2018-05-09 13:12
@shorea Then what is this artifact? https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-dax

**Comment by bamapookie** [comment] 2018-06-06 13:40
@dulaja the client must be manually downloaded and included in your project.  See this page: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.html

@shorea Is there an issue tracking the inclusion of the DAX client in the SDK, or at least, tracking its publishing in Maven?  If not, should I create one?

**Comment by millems** [comment] 2018-06-06 16:34
DAX will likely be managed in a separate GitHub repository. I will check with the DAX team to see if they are tracking towards any public completion date.

**Comment by millems** [comment] 2018-06-06 17:41
DAX has confirmed that releasing it to GitHub and Maven is in their backlog, but don't have any specific date to communicate at this time.

**Comment by rigregs** [comment] 2018-07-03 00:05
Do we have more news about the release date of DAX on maven? Manually download a dependency isn't the best way!

**Comment by millems** [comment] 2018-07-03 17:21
Sorry, still no date we can give from the DAX team. We definitely understand it's a pain to not be able to use maven to manage this dependency.

**Comment by hroongta** [comment] 2018-07-11 15:55
Any word on this?

**Comment by YaRuliY** [comment] 2018-07-17 14:31
any news on this question?

**Comment by shorea** [comment] 2018-07-17 15:57
I'll follow up with the DAX team.

**Comment by oleschaper** [comment] 2018-07-19 11:15
Yes, please!

**Comment by jdhardy** [comment] 2018-07-19 19:56
I pushed the DAX client to Maven this morning. Documentation on how to add it is at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-java.html#DAXClient.Maven.

**Comment by dsilvasc** [comment] 2018-07-19 19:59
@jdhardy Thanks for that.  Which repository did you upload to?  It's not showing up here yet: https://mvnrepository.com/artifact/com.amazonaws/amazon-dax-client

**Comment by dsilvasc** [comment] 2018-07-19 20:03
ah looks like maven central: https://repo.maven.apache.org/maven2/com/amazonaws/amazon-dax-client/

**Comment by shorea** [comment] 2018-07-19 20:04
@dsilvasc it'll sync to mvnrepository after some time. That's a mirror of Maven Central I believe.

**Comment by adolfoweloy** [comment] 2018-12-20 01:36
> DAX has confirmed that releasing it to GitHub and Maven is in their backlog, but don't have any specific date to communicate at this time.

any news on this question?

**Comment by jdhardy** [comment] 2018-12-20 16:17
@adolfoweloy No, nothing to report at this time. A GitHub release is still in our backlog.

**Comment by mydata** [comment] 2019-06-19 14:03
@jdhardy any update on this? Can we use the ones given in the aws fax docs with dynamodbmapper?

**Comment by jdhardy** [comment] 2019-06-19 15:13
@mydata The current DAX client (available from https://mvnrepository.com/artifact/com.amazonaws/amazon-dax-client) implements AmazonDynamoDB and should be usable with DynamoDBMapper. The [TryDax example](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-java.TryDax.html) shows the DAX and DynamoDB clients being used interchangeably.

As for a GitHub release, that's still on the backlog.

**Comment by mydata** [comment] 2019-06-19 15:31
Regarding infrastructure, Dynamo db does not associated with any security groups. When dax is created , do we need any sg to be associated with or they are accessible just with IAM policy being attached to instance where app is being deloyed? For separate cache, like redid we do maintain sg which can communicate between ec2 and redid. Trying to see any such config needed when using dax with dynamodb. @jdhardy

**Comment by jdhardy** [comment] 2019-06-19 17:33
This isn't really the proper place for a different question - better to use StackOverflow or the [AWS Forums](https://forums.aws.amazon.com).

That said, yes, for now DAX requires a security group, very much like how ElastiCache Redis works.

**Comment by evankozliner** [comment] 2022-02-11 17:37
AWS should provide more clear guidance here. DynamoDBMapper in java is common (even for internal use in AWS itself)
