### ISSUE TITLE
dynamodb batchGetItem UnsupportedOperationException

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#1458] opened 2018-02-02 11:40 UTC
DynamoDB.batchGetItem tries to update an unmodifiable map under some conditions and throws an UnsupportedOperationException

the requestItems map is updated, but it can come from spec.getUnprocessedKeys()
BatchGetItemSpec.withUnprocessedKeys makes the map unmodifiable

stacktrace:
```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.Collections$UnmodifiableMap.put(Collections.java:1458)
	at com.amazonaws.services.dynamodbv2.document.internal.BatchGetItemImpl.doBatchGetItem(BatchGetItemImpl.java:92)
	at com.amazonaws.services.dynamodbv2.document.internal.BatchGetItemImpl.batchGetItem(BatchGetItemImpl.java:64)
	at com.amazonaws.services.dynamodbv2.document.DynamoDB.batchGetItem(DynamoDB.java:158)
```

**Comment by varunnvs92** [comment] 2018-02-05 22:36
Do you have a reproducible test case? Sample code is helpful.
Did this issue happen in the latest version of the SDK?

**Comment by brackxm** [comment] 2018-02-06 08:14
it happened with version 1.11.253

**Comment by varunnvs92** [comment] 2018-02-06 21:48
Can you provide a reproducible test code?

**Comment by brackxm** [comment] 2018-02-09 15:34
code snippet

```
        DynamoDB db = new DynamoDB(Regions.EU_WEST_1);
        Map<String, KeysAndAttributes> keys = new HashMap<>();
        keys.put("abc", new KeysAndAttributes());
        BatchGetItemSpec spec = new BatchGetItemSpec()
                .withTableKeyAndAttributes(new TableKeysAndAttributes("table1")
                    .addHashOnlyPrimaryKey("h", "value1"))
                .withUnprocessedKeys(keys);
        db.batchGetItem(spec);
```

**Comment by zakgof** [comment] 2018-02-15 21:39
Same issue exists in `BatchWriteItemImpl`:
If your `BatchWriteItemSpec` contains both TableWriteItems and UnprocessedItems, you get an UnsupportedOperationException as SDK tries to append TableWriteItems to unmodifiable map of UnprocessedItems 

Reproducible on aws-java-sdk-dynamodb:1.11.278

Suggested fix is to copy `spec.getUnprocessedItems()` into a modifiable map:

Write:
```
 private BatchWriteItemOutcome doBatchWriteItem(BatchWriteItemSpec spec) {
        final Collection<TableWriteItems> tableWriteItemsCol =
                spec.getTableWriteItems();
        // Unprocessed items take precedence
        Map<String, List<WriteRequest>> requestItems = new 
                new LinkedHashMap<String, List<WriteRequest>>(spec.getUnprocessedItems()); 
```
Get:
```
 private BatchGetItemOutcome doBatchGetItem(BatchGetItemSpec spec) {
        final Collection<TableKeysAndAttributes> tableKeysAndAttributesCol =
                spec.getTableKeysAndAttributes();
        // Unprocessed keys take precedence
        Map<String, KeysAndAttributes> requestItems = new LinkedHashMap<String, List<WriteRequest>>(spec.getUnprocessedKeys());
```

**Comment by millems** [comment] 2018-06-06 05:35
A fix has been made and will go out with the next dynamo release, likely later this week or next.

**Comment by exp-jkhan** [comment] 2018-06-12 02:55
Hi @millems it seems the same is happening with DynamoDB.putItem(PutItemSpec) where if putItemSpec is instantiated with withValueMap(). It tries to update UnmodifiableEntrySet.UnmodifiableEntrySet when invoking InternalUtils.toAttributeValue, then throws an exception. Will this be fixed in the next dynamo release as well?

stacktrace: 
```
java.lang.UnsupportedOperationException: value type: class java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntry

	at com.amazonaws.services.dynamodbv2.document.internal.InternalUtils.toAttributeValue(InternalUtils.java:222)
	at com.amazonaws.services.dynamodbv2.document.internal.InternalUtils.fromSimpleMap(InternalUtils.java:89)
	at com.amazonaws.services.dynamodbv2.document.internal.PutItemImpl.doPutItem(PutItemImpl.java:78)
	at com.amazonaws.services.dynamodbv2.document.internal.PutItemImpl.putItem(PutItemImpl.java:63)
	at com.amazonaws.services.dynamodbv2.document.Table.putItem(Table.java:168)
```

**Comment by millems** [comment] 2018-06-12 17:20
Darn, I only fixed batchPut and batchGet. Reopening to fix it for putItem and make sure it's not an issue for any other requests.

**Comment by exp-jkhan** [comment] 2018-06-12 19:15
tyvm @millems!

**Comment by dagnir** [comment] 2018-06-19 22:35
@exp-jkhan What version of the SDK are you using? Can you provide a test case?

**Comment by dagnir** [comment] 2018-06-19 22:38
Ah I see, it looks like the exception was being thrown from here: https://github.com/aws/aws-sdk-java/blob/856d27b5d4f374fbb6299a3504f109ef23c1ea3a/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/internal/InternalUtils.java#L220-L223

which corresponds to before 1.11.270

**Comment by dagnir** [comment] 2018-06-19 23:11
This appears to be a different issue since it doesn't look like the client is attempting to modify an unmodifiable collection.

**Comment by exp-jkhan** [comment] 2018-06-19 23:15
Hi,

I'm using version 11.11.200, 

repro steps are:

Create a Map<String, Object> map with entries, initialize a PutItemSpec with .withValueMap(map)- 

then that exception I listed is thrown

**Comment by dagnir** [comment] 2018-06-19 23:33
Thanks @exp-jkhan. I could sort of getting the error to manifest with this code snippet, but it's correct behavior since we don't support marshalling `EntrySet` into an `AttributeValue`:

```java        
        Map.Entry<String, Object> unmodifiableEntry = Collections
                .unmodifiableMap(new ValueMap()
                        .withString("foo", "bar"))
                .entrySet().iterator().next();

        Map<String, Object> valueMap = new HashMap<String, Object>();
        valueMap.put("someAttr", unmodifiableEntry);

        Table table = dynamo.getTable(MY_TABLE);

        table.putItem(spec);
```

**Comment by dagnir** [comment] 2018-06-22 18:59
Going to go ahead and reclose this. Please feel free to reopen when you have a repro case @exp-jkhan

**Closed by dagnir** 2018-06-22 18:59 UTC
Labels: Bug
