### ISSUE TITLE
When adding filters to PutBucketNotificationConfigurationRequest get software.amazon.awssdk.services.s3.model.S3Exception: The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by vdkrav93** [aws/aws-sdk-java#2260] opened 2020-03-12 17:58 UTC
Code:
FilterRule filterRulePrefix = FilterRule.builder().name(FilterRuleName.PREFIX).value(prefixFilter).build();
    FilterRule filterRuleSuffix = FilterRule.builder().name(FilterRuleName.SUFFIX).value(suffixFilter).build();
    S3KeyFilter s3KeyFilter = S3KeyFilter.builder().filterRules(filterRulePrefix, filterRuleSuffix
        ).build();
    NotificationConfigurationFilter filter = NotificationConfigurationFilter
        .builder().key(s3KeyFilter).build();
    QueueConfiguration queueConfig = QueueConfiguration.builder().id("S3SqsNotification")
        .queueArn(queueArn).events(Collections.singleton(
            Event.fromValue(Constants.S3ReaderConstants.S3_EVENT_CREATED))).filter(filter).build();
    NotificationConfiguration notifConf = NotificationConfiguration.builder()
        .queueConfigurations(queueConfig).build();
    PutBucketNotificationConfigurationRequest putReq = PutBucketNotificationConfigurationRequest
        .builder().bucket(bucketName).notificationConfiguration(notifConf).build();
    s3Client.putBucketNotificationConfiguration(putReq);

**Comment by vdkrav93** [comment] 2020-03-12 18:00
Exception:
Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: The XML you provided was not well-formed or did not validate against our published schema (Service: S3, Status Code: 400, Request ID: AC8C281B81AFCBEE)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:158)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:86)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$4(BaseClientHandler.java:215)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:114)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:87)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:122)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:148)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:102)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putBucketNotificationConfiguration(DefaultS3Client.java:6368)

**Comment by vdkrav93** [comment] 2020-03-12 18:01
Version: 'com.amazonaws:aws-java-sdk-s3:1.11.742'

**Comment by debora-ito** [comment] 2020-03-13 20:51
If I would guess I'd say that is something related to the prefix or suffix you are specifying in the filter. Does the `putBucketNotificationConfiguration` call work without the s3KeyFilter?

Another way to check is to [enable wire logging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and see the XML that is being sent in the request. If you choose to share the wire logs here, please make sure there's no sensitive data.

**Comment by vdkrav93** [comment] 2020-03-13 21:10
Please, note that I am using not strings to specify filter rule name , but  validated members FilterRuleName.PREFIX and FilterRuleName.SUFFIX. Yes, it works without s3KeyFilter, 
error happens when filter function is called for QueueConfiguration.builder().

Can you reproduce this error?

I would like to help but not right now.
I believe that since request is built entirely with builders, it should not fail.
Aren't you agree?

**Comment by debora-ito** [comment] 2020-03-13 21:55
Sorry, I should have been more clear, I was referring to the suffix and prefix values, not the names. 
No, I could not reproduce it. Checking the XML in the wire logs would be the next step then.

**Comment by debora-ito** [comment] 2020-03-20 18:45
@vdkrav93 were you able to get the wire logs?

**Comment by vdkrav93** [comment] 2020-03-21 17:48
I am sorry, Debora, had too much work this week.
I will try to do it next week.

Thanks,
Vladimir

________________________________

**Comment by debora-ito** [comment] 2020-04-03 20:53
@vdkrav93 I'll close this for now, please reopen when you have more info.

Check for not encoded characters in the values you are providing in the filters, this may be the cause.

**Closed by debora-ito** 2020-04-03 20:53 UTC
Labels: closing-soon, guidance, response-requested
