### ISSUE TITLE
What version of amazon-kinesis-client should we use?

### ISSUE THREAD

**Issue by nikesh-dev** [aws/aws-sdk-java#1741] opened 2018-08-24 09:02 UTC
I am trying to use https://github.com/aws/aws-sdk-java/tree/1.11.295/src/samples/AmazonKinesis sample. What combination of amazon-kinesis-client and aws-java-sdk version should I use? 
"com.amazonaws.services.kinesis.clientlibrary.types.ShutdownReason" couldnot resolve.
Getting above error when trued latest versions.

**Comment by zoewangg** [comment] 2018-08-27 16:40
Closing the issue, feel free to reopen if you have further questions/issues.

**Closed by zoewangg** 2018-08-27 16:40 UTC
Labels: Question

**Comment by humank** [comment] 2018-10-26 09:59
Hi, @zoewangg. It doesn't work for using same version aws-java-sdk bom management.
Because the root cause is the kinesis clientlibrary do lack of the class, the attachment diagram is the folder extracted from the kinesis clientlibrary jar file.

> com.amazonaws.services.kinesis.clientlibrary.types.ShutdownReason

![screen shot 2018-10-26 at 5 58 20 pm](https://user-images.githubusercontent.com/3405925/47559706-ca515280-d948-11e8-8ee2-c3ed0ac27040.png)
