### ISSUE TITLE
Error with ObjectMapper in version 1.10.33

### ISSUE THREAD

**Issue by hacbq** [aws/aws-sdk-java#564] opened 2015-11-28 04:40 UTC
In version 1.10.33, I see this code use ObjectMapper
https://github.com/aws/aws-sdk-java/blob/1.10.33/aws-java-sdk-core/src/main/java/com/amazonaws/internal/config/InternalConfig.java
But in my project use Spring Boot 1.2.7 & jackson 2.4.6, I get error message:
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at com.amazonaws.internal.config.InternalConfig.<clinit>(InternalConfig.java:43)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:304)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:139)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:134)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:95)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:59)
```
I try this code in my project:
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.enable(JsonParser.Feature.ALLOW_COMMENTS);
```
 and eclipse SDK show:
```
The method enable(MapperFeature...) in the type ObjectMapper is not applicable for the arguments (JsonParser.Feature)
```

**Comment by zhangzhx** [comment] 2015-11-28 20:04
Hi,

It seems that your jackson version is too low. The method 
```
ObjectMapper enable(com.fasterxml.jackson.core.JsonParser.Feature... features)
```
came into jackson since version 2.5
```
https://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/ObjectMapper.html#enable(com.fasterxml.jackson.core.JsonParser.Feature...)
```
Could you update the version to 2.5 or higher and see if you still have the issue?

**Comment by hacbq** [comment] 2015-11-30 02:41
I will try it. Now i use default version in Spring boot 1.2.7 :)

**Comment by manikandanrs** [comment] 2015-11-30 17:12
Can you confirm if the issue is fixed ?

**Comment by hacbq** [comment] 2015-12-01 05:02
I still use version 1.10.32, i will try to update in this week

**Comment by manikandanrs** [comment] 2015-12-08 02:23
Any updates on this ?

**Comment by hacbq** [comment] 2015-12-08 02:29
So busy :(. I will rely when I update :)

**Comment by manikandanrs** [comment] 2015-12-08 02:48
Closing this for now. Feel free to re open when you have an update.

**Closed by manikandanrs** 2015-12-08 02:48 UTC
Labels: waiting-reply

**Comment by hacbq** [comment] 2015-12-09 10:11
I updated last version jackson and no problem :+1:

**Comment by manikandanrs** [comment] 2015-12-09 16:48
Glad to hear the problem is resolved.
