### ISSUE TITLE
WARNING when compiling to native Quarkus executable

### ISSUE THREAD

**Issue by zeppelinux** [aws/aws-sdk-java#2587] opened 2021-05-27 19:56 UTC
Compiling to a native executable produces following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazonaws.util.XpathUtils (file:/Users/dimas/IdeaProjects/gwifi-dyndns/target/gwifi-dyndns-native-image-source-jar/lib/com.amazonaws.aws-java-sdk-core-1.11.1022.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()
WARNING: Please consider reporting this to the maintainers of com.amazonaws.util.XpathUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

## Steps to Reproduce
1. checkout this project https://github.com/zeppelinux/gwifi-dyndns
2. ./mvnw package -Pnative

## Context
Just a heads up for you, it still works.

## Your Environment
* AWS Java SDK version used: aws-java-sdk-route53 1.11.1022
* JDK version used: graalvm-ce-java11-21.0.0.2
* Operating System and version: OS X 11.4

**Comment by debora-ito** [comment] 2021-05-28 01:06
Hi @zeppelinux, this is a duplicate of https://github.com/aws/aws-sdk-java/issues/1603.

As I mentioned in the other thread we decided not to fix this in v1.
I'll go ahead and close this, feel free to reach out if you have any other question.

**Closed by debora-ito** 2021-05-28 01:06 UTC
Labels: bug, duplicate

**Comment by zeppelinux** [comment] 2021-05-28 06:46
I see it's going to be fixed in sdk be, so it's all I wanted to accomplish. Thanks!
