### ISSUE TITLE
Download state is incorrect after abort

### ISSUE THREAD

**Issue by skjernaa** [aws/aws-sdk-java#2648] opened 2021-09-28 10:11 UTC
## Describe the bug
When a download is aborted, the state of the download object should be Canceled. But currently it changes to Failed shortly after the call to abort()

The bug was introduced with the fix to https://github.com/aws/aws-sdk-java/issues/2263

## Expected Behavior
download.getState() should keep returning Canceled

## Current Behavior
download.getState() starts returning Failed shortly after the call to abort()

## Steps to Reproduce
TransferManager transferManager = ...;
Download download = transferManager.download(bucketName, objectKey, file);
Thread.sleep(1000);
download.abort();
assertEquals(TransferState.Canceled, download.getState()); // Typically passes
Thread.sleep(100);
assertEquals(TransferState.Canceled, download.getState()); // Fails. The state is now Failed

## Possible Solution

Bug is in CompleteMultipartDownload.cleanupAfterException (or the caller of this method), where InterruptedException should not mark the download as failed (or more generally: the download should not be set to failed, if the state is already canceled)

## Your Environment

aws-java-sdk-s3-1.12.28.jar

**Comment by aaoswal** [comment] 2021-11-01 21:29
Hi @skjernaa,
I am not able to reproduce the issue on SDK Version `1.11.638`. Can you please provide me with some additional information below for reproducing the issue to further assist you:

1. How are the files being uploaded to the S3 buckets?
2. What is the size of the file that you are uploading?
3. Any additional customizations that you are using for uploading or in the code?

**Comment by skjernaa** [comment] 2021-11-04 14:35
Hi @aaoswal

Just to clarify: The issue is with downloading. In my environment, on 1.11.638 the test always passes and on 1.12.28 the test always fails.

The file I download is a ~18 MB binary file.

I have attached my full, self contained test (replaced bucket name and key).

[TransferManagerTest.java.txt](https://github.com/aws/aws-sdk-java/files/7475559/TransferManagerTest.java.txt)

**Comment by debora-ito** [comment] 2024-06-18 21:21
Hi @skjernaa  

We apologize but this won't get fixed in v1. If this is still an issue on [TransferManager v2](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/transfer/s3/S3TransferManager.html), please let us know and put the repro case details in a new [aws/aws-sdk-java-v2 issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose).

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)

**Closed by debora-ito** 2024-06-18 21:21 UTC
Labels: bug, p3
