### ISSUE TITLE
upload is slow....

### ISSUE THREAD

**Issue by dil022dixith** [aws/aws-sdk-java#1871] opened 2019-01-09 15:56 UTC
We are using below code snap to upload the object.
Part size is 128 MB.
We are trying for 200 MB and it takes 7 seconds to upload which is slower as compared to other open source : JClouds. JClouds takes 4 seconds.

Upload uploadObject = awsTransMgr.upload( theOp.container + suffix, mBmd.getName(), payload.openStream(), objMetadata );
UploadResult uploadResult = uploadObject.waitForUploadResult();

Need help to improve the performance here.

**Comment by debora-ito** [comment] 2019-01-09 16:35
Closing as a duplicate of #1868.

**Closed by debora-ito** 2019-01-09 16:35 UTC
