### ISSUE TITLE
Downloading object from SSE KMS encrypted S3 bucket fails

### ISSUE THREAD

**Issue by gatla1234** [aws/aws-sdk-java#1415] opened 2017-12-09 20:46 UTC
Hello There, I am trying to download the object from S3 bucket(which is  encrypted with AWS KMS key).  
AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard().withCredentials(awsCredentialsProvider).withClientConfiguration(clientConfiguration).withForceGlobalBucketAccessEnabled(true).withRegion(Regions.US_EAST_1);
                 s3client = s3ClientBuilder.build();

Download download = txManager.download( newGetObjectRequest(bucketName,key), file); where txManager is TransferManager object built by passing s3client.

This code snippet is throwing the error saying..."The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch"

Full Logs:::::
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4319)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4266)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1406)
	at com.amazonaws.services.s3.transfer.DownloadTaskImpl.getS3ObjectStream(DownloadTaskImpl.java:42)
	at com.amazonaws.services.s3.transfer.DownloadCallable.retryableDownloadS3ObjectToFile(DownloadCallable.java:281)
	at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:135)
	at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

-->I am using my accessKey and secret key inorder to build s3client. The java sdk version is 1.11.235. The above code snippet is working normally for Non-encrptyted buckets.  But throwing error for encrypted buckets.

I also tried 	
SSECustomerKey sseKey=new SSECustomerKey(AWSKmsId);
Here AWSKmsId I am providing is base64 encoded and this is the same key I provided to encrypt the bucket and I gave while putting the object to the same bucket.
 
Download download = txManager.download(newGetObjectRequest(bucketName,key).withSSECustomerKey(sseKey),
						file);

This code snippet is throwing error Saying..."Bad request".

--->I want to add one more Comment that, without using transfer manager I am able to download the file from SSE KMS encrypted object normally, even without passing any KMS key. But If I am using Transfer Manager, then It is throwing error saying..." The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch"

Could you please help me regarding this...Thanks

**Comment by shorea** [comment] 2017-12-11 19:56
Is the bucket in another region? Can you turn on debug logging and share the canonical request as computed by the SDK (be sure to redact any sensitive information).

**Comment by gatla1234** [comment] 2017-12-12 04:04
Hello Shorea, actually the bucket is in the same region. I have one quick question for you and All. Do Transfer Manager supports Downloading of SSE KMS encrypted objects??. 

I see that there is no way to pass the KMS keyID as parameter while downloading the object through transfer manager. And also one more observation is that, TransferManager supports uploading the objects to SSE KMS encrypted bucket by passing KMS keyID. Here is the proof for that 

PutObjectRequest putRequest = new PutObjectRequest(bucketName,
   keyName, file).withSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams(keyID));

**Comment by shorea** [comment] 2017-12-12 19:14
You should be able to set the KMS key id in the GetObjectRequest.

**Comment by gatla1234** [comment] 2017-12-12 19:33
ok, then could you please provide method signature to prove it is accepting the KMS keyID as parameter. Actually I am not able to find it.

**Comment by dagnir** [comment] 2017-12-18 22:06
@gatla1234 Can you provide a full code example that reproduces the error?

This test snippet works fine with 1.11.235:

```java
public class GitHub1415 {
    public static final String BUCKET = "my-bucket";
    public static final String KEY = "my-object-key";
    public static final String KMS_KEY_ID = "my-kms-key-id";

    private AmazonS3 s3;
    private TransferManager tm;

    public GitHub1415() {
        s3 = AmazonS3ClientBuilder.standard()
                .withForceGlobalBucketAccessEnabled(true)
                .withRegion(Regions.US_EAST_1)
                .build();
        tm = TransferManagerBuilder.standard().withS3Client(s3).build();
    }

    public void testIt() throws IOException, InterruptedException {
        tm.download(new GetObjectRequest(BUCKET, KEY),
                Files.createTempFile("gh1415-test-", "").toFile()
        ).waitForCompletion();

    }

    public static void main(String[] args) throws IOException, InterruptedException {
        GitHub1415 gh1415 = new GitHub1415();
        gh1415.testIt();
    }
}
```

**Comment by danesavot** [comment] 2017-12-19 01:10
I've got the same issue today. I can't seem to find way to specify kmsid for getObjectRequest.

**Comment by gatla1234** [comment] 2017-12-20 16:47
Hello @dagnir , yes it is working for me also in us-east-1(N.virginia region). And also working for london region. But I am getting same error for every other region. Eventhough I am passing any region while building S3client

Here is my code, I am working with::::
public static final String BUCKET = "my-bucket";
    public static final String KEY = "my-object-key";
File tempFile =new File("C://Tempfile.txt");

AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard()
.withCredentials(awsCredentialsProvider).withClientConfiguration(clientConfiguration)
.withForceGlobalBucketAccessEnabled(true).withRegion(Regions.US_WEST_1);
AmazonS3 s3client = s3ClientBuilder.build();

TransferManagerBuilder txmanagerBuilder=TransferManagerBuilder.standard().withS3Client(s3Client);

TransferManager txManager = txmanagerBuilder.build();

Download download = txManager.download(new GetObjectRequest(BUCKET,KEY, tempFile);
				download.waitForCompletion();

**Comment by dagnir** [comment] 2017-12-20 19:39
I'm still unable to reproduce this when setting the region to `us-west-1` or `ap-southeast-2`. How are you constructing your credentials provider?

**Comment by gatla1234** [comment] 2017-12-20 20:08
@dagnir  just confirming, you changed the region to us-west-1 or ap-southeast-2 but trying to download the file from us-east-1 right?. If this is the case, could you please keep the region as us-west-1 and try to download the file from bucket in us-west-1 and also make sure your bucket is SSE KMS encrypted. 

In my case, what I am doing is , I am trying to download the object from us-west-1 keeping region same us-west-1 and also all the buckets are SSE KMS encrypted. Still producing the same error

**Comment by dagnir** [comment] 2017-12-20 22:43
> In my case, what I am doing is , I am trying to download the object from us-west-1 keeping region same us-west-1

So you're unable to download an object from a bucket in `us-west-1` with your client configured to the same region? Seems very weird that that wouldn't work.

Here's a full example that's working for me:

```java
package com.dongie;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.CreateBucketRequest;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.SSEAlgorithm;
import com.amazonaws.services.s3.model.ServerSideEncryptionByDefault;
import com.amazonaws.services.s3.model.ServerSideEncryptionConfiguration;
import com.amazonaws.services.s3.model.ServerSideEncryptionRule;
import com.amazonaws.services.s3.model.SetBucketEncryptionRequest;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Stream;

public class GitHub1415 {
    private static final String BUCKET_PREFIX = "my-prefix-";
    private static final String KEY = "encrypted-by-default.txt";
    private static final Map<Regions, String> KMS_KEYS = new HashMap<>();
    static {
        KMS_KEYS.put(Regions.US_WEST_1, "key-id-1");
        KMS_KEYS.put(Regions.AP_SOUTHEAST_2, "key-id-2");
    }

    public void setUp(Regions region) {
        AmazonS3 s3 = createS3(region);
        String bucketName = bucketName(region);
        try {
            s3.createBucket(new CreateBucketRequest(bucketName, region.getName()));
            s3.setBucketEncryption(new SetBucketEncryptionRequest().withBucketName(bucketName)
                    .withServerSideEncryptionConfiguration(new ServerSideEncryptionConfiguration()
                            .withRules(new ServerSideEncryptionRule()
                                    .withApplyServerSideEncryptionByDefault(new ServerSideEncryptionByDefault()
                                            .withSSEAlgorithm(SSEAlgorithm.KMS)
                                            .withKMSMasterKeyID(KMS_KEYS.get(region))))));
            s3.putObject(bucketName, KEY, new ByteArrayInputStream("test".getBytes(StandardCharsets.UTF_8)), new ObjectMetadata());
        } catch (Exception ignored) {
        }
    }

    public AmazonS3 createS3(Regions region) {
        return AmazonS3ClientBuilder.standard()
                .withRegion(region)
                .withForceGlobalBucketAccessEnabled(true)
                .build();
    }

    public String bucketName(Regions region) {
        return BUCKET_PREFIX + region.getName();
    }

    public void test() {
        Stream.of(Regions.US_WEST_1, Regions.AP_SOUTHEAST_2).forEach(r -> {
            setUp(r);
            testDownloadUsingRegion(r);
        });
    }

    public void testDownloadUsingRegion(Regions region) {
        AmazonS3 s3 = null;
        TransferManager tm = null;
        try {
            s3 = createS3(region);
            tm = TransferManagerBuilder.standard().withS3Client(s3).build();
            tm.download(bucketName(region), KEY, Files.createTempFile("test-file", "").toFile()).waitForCompletion();
            System.out.printf("Successfully downloaded using region %s%n", region.getName());
        } catch (Exception e) {
            System.out.printf("Could not download using region %s%n", region.getName());
            throw new RuntimeException(e);
        } finally {
            s3.shutdown();
            tm.shutdownNow();
        }
    }

    public static void main(String[] args) {
        GitHub1415 gitHub14152 = new GitHub1415();
        gitHub14152.test();
    }
}
```

The original error

> The request signature we calculated does not match the signature you provided.

Indicates there's a request signing error.

Please tell us how you're configuring your `awsCredentialsProvider`. Incorrect credentials can lead to this error.

**Comment by gatla1234** [comment] 2017-12-22 00:39
I tried the above code in my machine, still I am getting same issue for california,tokyo , sydney ...regions. but this is code is working for virginia, ohio,london even though i am specifying the regions as "US_WEST_1".

**Comment by shorea** [comment] 2018-01-24 21:45
@gatla1234 are you still seeing this issue?

**Comment by shorea** [comment] 2018-01-29 08:13
Closing issue, feel free to reopen if you are still encountering the problem

**Closed by shorea** 2018-01-29 08:13 UTC
Labels: Question, waiting-reply
