### ISSUE TITLE
Error doing an upload with metadata

### ISSUE THREAD

**Issue by svoorakk** [aws/aws-sdk-java#223] opened 2014-05-06 08:37 UTC
When doing an S3 upload with metadata, there is a 403 error . This can be worked around by URLEncoding the metadata keys so that the upload is successful. But it is not an ideal solution since anyone retrieving metadata should be aware that it needs to be URL decoded. Also viewing metadata in AWS console, metadata is displayed with url encoding. Details are provided here : http://stackoverflow.com/questions/23239304/error-with-aws-java-sdk-doing-an-upload-with-metadata

**Comment by breedloj** [comment] 2016-01-21 00:02
Closing this since the issue is nearly 2 years old and this is expected behavior.

**Closed by breedloj** 2016-01-21 00:02 UTC
