### ISSUE TITLE
Custom endpoint for SQS (VPC Endpoint) does not work.

### ISSUE THREAD

**Issue by harihara-n** [aws/aws-sdk-java#2135] opened 2019-10-29 18:18 UTC
### Issue description

Please refer to https://github.com/aws/aws-sdk-ruby/issues/2114 - this issue is the exact same as that one (for which a fix is being developed), but for Java. 

[QueueUrlHandler](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/QueueUrlHandler.java) is the equivalent in Java that is causing SQS calls to not work when specifying a custom endpoint (such as an SQS VPC Endpoint). This is because, the custom endpoint is being replaced with the host in the queue URL, which happens to be `sqs.<region>.amazonaws.com`

**Comment by juaoose** [comment] 2020-01-07 23:49
Would it be appropiate to look at the incoming request, if such object already has an endpoint, then just use that endpoint instead of setting it from the QueueUrl? Are there other assumptions I might be overlooking?

**Comment by debora-ito** [comment] 2020-01-08 23:31
Hi @hhk1989, I just want to confirm the issue you're seeing with the SDK for Java, is the following code a good example of you're trying to do?

```java
AmazonSQS sqsClient = AmazonSQSClientBuilder.standard()
    .withRegion(Regions.AP_SOUTH_1)
    .build();

SendMessageRequest sendMessageRequest = new SendMessageRequest()
    .withQueueUrl("https://vpce-<vpce-id>.sqs.us-west-2.vpce.amazonaws.com/<user-id>/<sqs-queue>")
    .withMessageBody("Hello");
SendMessageResult result = sqsClient.sendMessage(sendMessageRequest);

```

Could you share the stacktrace of the error?

**Comment by hhk1989** [comment] 2020-01-13 20:38
@debora-ito apologies for the late response.

The code snippet we have would be something like the following (similar to the Ruby code in the linked issue above).

```
AwsClientBuilder.EndpointConfiguration endpointConfiguration = new AwsClientBuild.EndpointConfiguration("https://vpce-<vpce-id>.sqs.us-west-2.vpce.amazonaws.com", Regions.US_WEST_2)

AmazonSQS sqsClient = AmazonSQSClientBuilder.standard()
    .withRegion(Regions.US_WEST_2)
    .withEndpointConfiguration(endpointConfiguration)
    .build();

SendMessageRequest sendMessageRequest = new SendMessageRequest()
    .withQueueUrl("https://sqs.us-west-2.amazonaws.com/<account_id>/<queue_name>")
    .withMessageBody("Hello");
SendMessageResult result = sqsClient.sendMessage(sendMessageRequest);
```

 The above makes a request to `https://sqs.us-west-2.amazonaws.com` origin, rather than the VPC Endpoint specified in the endpoint configuration.

The error we get is in our applications in the DC is a 403, because the application has not whitelisted the above SQS public API path in our internal squid proxy that selectively allows only whitelisted public paths.

**Comment by debora-ito** [comment] 2020-01-16 21:33
> The issue is that the above makes a request to https://sqs.us-west-2.amazonaws.com origin, rather than the VPC Endpoint specified in the endpoint configuration.

I understand it now. We may not be able to change this behavior, but a possible solution would be specifying the vpc endpoint url directly in the queue url as I did in my code example.

Anyway, we are investigating.

**Comment by debora-ito** [comment] 2020-01-22 19:48
I can reproduce the issue, marking as a bug.

The issue is in our backlog, pending prioritization.

**Comment by Quanzzzz** [comment] 2020-08-24 22:45
Hi @hhk1989, after checking this issue and trying to reproduce it, I got a question about your expecting behavior of the sdk. I'm supposing that you want to custom the endpoint and send message to SQS via this endpoint, and that's indeed not currently supported in java sdk, as the host in queue url will override the client configured endpoint. However,  I also tried to send the message to a queue with the VPC-Endpoint specified in the url as:
```
SendMessageRequest sendMessageRequest = new SendMessageRequest()
    .withQueueUrl("vpce-xxxx-yyy-us-west-2a.sqs.us-west-2.vpce.amazonaws.com/userid/sqs-queue-name")
    .withMessageBody("Hello");
SendMessageResult result = sqsClient.sendMessage(sendMessageRequest);
```
This ran into an exception of ```com.amazonaws.SdkClientException: Unable to execute HTTP request: vpce-0ab61fe684cccb125.sqs.us-west-2.amazonaws.com```, which means SQS can't resolve this endpoint.
Besides, I also tried to use the vpc-e in the endpoint-url by:
```
aws sqs send-message --region us-east-2 --endpoint-url https://vpce-xxxx-yyy-us-west-2a.sqs.us-west-2.vpce.amazonaws.com/ --queue-url https://sqs.us-east-2.amazonaws.com/123456789012/ --message-body "Hello from Amazon SQS."
```
according to the tutorial of sending the sqs message from Amazon VPC (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-sending-messages-from-vpc.html), and this ran into the same exception too.

So I think cusomizing the endpointt of the client doesn't help with this issue. Since the vpc-e doesn't work when it's configured in the queue url, it wouldn't work when it's configured in the client, either. 

As a result, could you let us know about your expected behavior of the sdk considering this?

**Comment by hhk1989** [comment] 2020-09-01 17:18
@debora-ito @Quanzzzz Thanks for the response. However, I do not believe that is true. If you look at https://github.com/aws/aws-sdk-ruby/pull/2156/files (fixes https://github.com/aws/aws-sdk-ruby/issues/2114) - they have been able to fix the issue I opened for the ruby SDK and the above functionality already works as expected for the Go SDK. 

Also one thing I noticed in the above code snippet you pasted (which differs from https://github.com/aws/aws-sdk-ruby/issues/2114#issuecomment-551260376) is that you have no included the protocol portion of the queueURL, i.e. `https://` here.

**Comment by Quanzzzz** [comment] 2020-09-11 00:32
Hi, @hhk1989 sorry for delay. Have you tried using normal endpoint and queue url without vpce specified in them in your EC2 instance as what the tutorial(https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-sending-messages-from-vpc.html) shows:
```
aws sqs send-message --region us-east-2 --endpoint-url https://sqs.us-east-2.amazonaws.com/ --queue-url https://sqs.us-east-2.amazonaws.com/123456789012/ --message-body "Hello from Amazon SQS."
```
Within the VPC, if you have created a VPC endpoint for particular service, the normal endpoint will be mapped to your VPC endpoint, thus you don't need to specify anything when you are sending the requests. Just like the example above, if you are running your application on your EC2 instance and using the normal endpoint, your VPC endpoint should have already been used.
Otherwise, we also understand that you might have some other reasons to customize the VPC endpoint in the client, could you please let us know the motivation so we can have a more clear idea about why we do need to support resolving VPC endpoints in our SDK? Thanks.

**Comment by akirsman** [comment] 2020-10-05 21:19
But the problem it's for on-prem machines with no Internet access, in those cases only workingaround is to (kind of) statically resolve sqs.<region>.amazonaws.com to the IP of the VPC endpoint...

**Comment by Quanzzzz** [comment] 2021-02-17 18:11
This issue is now a known issue to our side. Currently we don't have a plan to support this feature, and the main reason is that this feature request would be a breaking change, which conflicts with our speculation of backwards compatibility.

For customers who want to use this feature, please use our [v2 SDK](https://github.com/aws/aws-sdk-java-v2). The V2 SDK has better consistency with the other SDKs' behavior and it does support endpoint overriding. 

Here are some of the docs we have for v2 for reference:
https://docs.aws.amazon.com/sdk-for-java/latest/migration-guide/whats-different.html
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html

**Closed** 2021-02-19 22:38 UTC
Labels: bug

**Comment by cpatel-r7** [comment] 2022-05-03 20:36
Hi! Was this feature added to v1 AWS SDK by any chance?
