### ISSUE TITLE
unable to get the instance information from the amazon sdk (API amazonEC2Client.describeInstances())

### ISSUE THREAD

**Issue by bhadradeka** [aws/aws-sdk-java#824] opened 2016-08-24 14:44 UTC
Hi All,
In the following scenario I am unable to get the instance information from the amazon sdk (API amazonEC2Client.describeInstances()) -
If you have encountered this issue, can you please help ?
 
App-server: has two interfaces- eth0 ( public IP : XX.XXX.XXX.28)
                                                   eth1 ( Elastic IP : XX.XXX.XXX.137)
    While the following call sequence works for public IP: XX.XXX.XXX.28, it does not work for Elastic IP : XX.XXX.XXX.137.  
    Basically, amazonEC2Client.describeInstances(describeInstancesRequest).getReservations() >>>>> returns empty
 
            // Here host is IP XX.XXX.XXX.28 or XX.XXX.XXX.137
            List<Filter> hostFilters = new ArrayList<>();
            hostFilters.add(new Filter("ip-address", Arrays.asList(host)));
            hostFilters.add(new Filter("private-ip-address", Arrays.asList(host)));
            DescribeInstancesRequest describeInstancesRequest = new DescribeInstancesRequest();
            describeInstancesRequest.setFilters(Arrays.asList(hostFilters));
 
            List<Reservation> reservations = amazonEC2Client.describeInstances(describeInstancesRequest).getReservations();    >>>>>>>
            for (Reservation reservation : reservations){
                  Instance instance : reservation.getInstances();
                  // process the instance informations
       }

Any help would be greatly appreciated.

**Comment by varunnvs92** [comment] 2016-08-24 22:46
From [Amazon EC2 docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html), it looks like "association.public-ip" is the filter for Elastic IP address bound to the network interface. Can you try the Elastic IP address with that filter and see if it works.

You can also try [describe-instances with AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) and see if the output differs from Java SDK's output. If both outputs are same, then the problem is related to usage of the API. Please make sure you are using the [Elastic IP address ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#eip-basics)correctly with the instances.

Let me know if this information is helpful in solving the issue.

**Comment by bhadradeka** [comment] 2016-08-25 17:59
Hi Thanks for your reply.
I tried association.public-ip as filter, but got the error: An error occurred (InvalidParameterValue) when calling the DescribeInstances operation: The filter 'association.public-ip' is invalid.

I used this link to attach the EIP: https://www.lisenet.com/2014/create-and-attach-a-second-elastic-network-interface-with-eip-to-ec2-vpc-instance/

Not sure if there is any mistake while associating the EIP.

**Comment by varunnvs92** [comment] 2016-08-26 04:12
I am not familar with EIP setup but will look into it.

Did you try the describeInstances with aws cli? https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html
Is the output same or different from Java SDK output?

**Comment by bhadradeka** [comment] 2016-08-26 04:26
Yes, I tried from CLI also. Got the same error "The filter 'association.public-ip' is invalid"

**Comment by varunnvs92** [comment] 2016-08-26 05:04
What about the original test case in your first message? Was cli output same as Java SDK output?

**Comment by varunnvs92** [comment] 2016-08-26 19:55
After testing the test code you provided, I found the following issues:
1) You are assigning the same value(host) to both "ip-address" and "private-ip-address" filters. The public IP and private IP are different for instances. You can find them by logging into console, select the instance and look at the description.
2) describeInstancesRequest.setFilters(Arrays.asList(hostFilters));
   hostFilters is already a list, so no need to call Arrays.asList on it.

After fixing them, I was able to successfully print the instances by providing the correct public and private IP address. Note that when you assign a EIP to an instance, the existing public IP will be released and EIP will become the public IP. So make sure you provide the right address to the filters. 

The filter for EIP is "ip-address" which is same as public IP address. The filter "association.public-ip" which I mentioned earlier is address of the Elastic IP address bound to the network interface not to an instance. Sorry for not recognizing it.

**Comment by bhadradeka** [comment] 2016-08-30 02:27
Thanks for you time and effort spending on it. I got another work-around to get the information.
1. Described the address with the EIP and got the instance-if from it (describeAddresses())
2. Got the instance-id from the Address
3. Got the reservations from describeInstances() with the instance-id got from step 2.
4. Got the instance information from with getInstances() on reservation.

Thanks again

**Comment by varunnvs92** [comment] 2016-08-30 16:16
I am glad that you are able to get the instance information. Closing the issue. Feel free to re-open if you have more questions. Thank you.

**Closed by varunnvs92** 2016-08-30 16:16 UTC
