### ISSUE TITLE
SQS : Not taking blank string in message body

### ISSUE THREAD

**Issue by mukteshkrmishra** [aws/aws-sdk-java#828] opened 2016-08-27 08:44 UTC
Hi, 
I am trying to use SQS and found out it does not take blank String "" in messageBody inside setMessageBody. If we try to set up empty string then it throws mandatory attribute required validation error.

I want to know the reason about this bug. Is it due to serialization problem ?

Please confirm.

**Comment by dagnir** [comment] 2016-08-29 16:55
Hey @mukteshkrmishra this doesn't look like an issue with serialization as the SDK will send the following in the `POST` body when sending an empty string

```
"Action=SendMessage&Version=2012-11-05&MessageBody="
```
output is from version 1.11.29

You can try this for yourself by enabling Wire logging: http://docs.aws.amazon.com/java-sdk/latest/developer-guide/java-dg-logging.html. Note: you'll need to have the log4j JAR on your classpath as well; it's not included with the SDK JARs.

Do you have a specific use case for sending empty strings?

**Comment by mukteshkrmishra** [comment] 2016-08-29 18:41
I was using 1.11.27

**Comment by dagnir** [comment] 2016-08-29 20:09
Hey sorry I didn't meant to imply that it's fixed with 1.11.29--I'm able to reproduce the exception with 1.11.29; I tested and it also produces the same body for 1.11.27. It looks like SQS does not like an empty `messageBody`.

**Comment by mukteshkrmishra** [comment] 2016-08-29 23:30
Thanks @dagnir !!. Meanwhile I tested it for other versions also and able to replicate it.

**Comment by dagnir** [comment] 2016-09-06 17:52
Closing this as it's not an issue with the SDK.

**Closed by dagnir** 2016-09-06 17:52 UTC
