### ISSUE TITLE
Getting java.net.UnknownHostException while downloading file from s3

### ISSUE THREAD

**Issue by grvshaha** [aws/aws-sdk-java#1273] opened 2017-08-11 08:34 UTC
We are using 
1) Java version : 1.8.0_131
2) aws-sdk version : 1.11.107

Stack trace: 

java.net.UnknownHostException: <bucketname>-bucket.s3.amazonaws.com
at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
at java.net.InetAddress.getAllByName(InetAddress.java:1192)
at java.net.InetAddress.getAllByName(InetAddress.java:1126)
at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
at com.amazonaws.http.conn.$Proxy9.connect(Unknown Source)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4187)
at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:4942)
at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:4916)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4171)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4134)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1385)
at com.amazonaws.services.s3.AmazonS3Client$3.getS3ObjectStream(AmazonS3Client.java:1462)
at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:399)

**Comment by grvshaha** [comment] 2017-08-11 08:37
Above process is not a daemon and we are getting the above error at the time of job start. So I am assuming the issue is not related to Java-DNS-TTL settings. 

On retrial, processing is working as expected.

**Comment by millems** [comment] 2017-08-11 20:29
Which bucket are you attempting to access? By default, the SDK prefixes the host name with the bucket name. In this case it looked like you were trying to access a bucket with the name "-bucket".

**Comment by amishasthana** [comment] 2017-08-14 21:45
We are seeing same issue. We are on:
aws-java-sdk:jar:1.11.65
java version "1.8.0_77"

Do note we read and write from S3 bucket. 
a) We have started seeing this error in our env. in the last 15-20 days. 
b) The issue is intermittent and rare(few times a day). Seem to go away after popping up few times.
c) So far we have seen the issue only on GET.
d) The bucket etc. is properly configured once at start of service. Once started there is no change in bucket.
e) Our service is running on west talking to bucket in west coast.
Our exception stack trace:
com.amazonaws.SdkClientException: Unable to execute HTTP request: <bucket name>.s3-us-west-2.amazonaws.com
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:972)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4137)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1346)
at com.lendingclub.document.store.S3Bucket.doGet(S3Bucket.java:88)

**Comment by shorea** [comment] 2017-08-28 17:01
Going to close this ticket. From what I'm reading this is a transient DNS issue so it's outside of the SDKs control. I suggest following up with the EC2/Networking support if you are running on EC2 or S3 support.

**Closed by shorea** 2017-08-28 17:01 UTC
Labels: Question

**Comment by annahosanna** [comment] 2018-10-30 15:50
Just in case anyone else runs across this, I had the same periodic hostname resolution failures accessing S3 with a hybrid cloud (the vpc is not DNS enabled). I ended up working around the issue by using Unbound as a local DNS cache as documented around page 16: https://d0.awsstatic.com/whitepapers/hybrid-cloud-dns-options-for-vpc.pdf

**Comment by UserProgrammer** [comment] 2019-10-23 02:03
> Which bucket are you attempting to access? By default, the SDK prefixes the host name with the bucket name. In this case it looked like you were trying to access a bucket with the name "-bucket".

Why does the SDK prefix the host name with the bucket name by default?
