### ISSUE TITLE
AWS Step Functions: Support for region ap-southeast-2 not reflected in SDK

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1205] opened 2017-06-20 08:33 UTC
Similar to #1095: The recently added availability of [AWS Step Functions in Asia Pacific (Sydney)](https://aws.amazon.com/about-aws/whats-new/2017/06/aws-step-functions-available-in-asia-pacific-sydney/) is not reflected in the SDK's [`endpoints.json`](https://github.com/aws/aws-sdk-java/blob/1.11.151/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1350) yet. 

This affects UX in terms of e.g. the added region not being returned by `RegionUtils.getRegionsForService()` (actual usage of the region by setting it explicitly to the result of `RegionUtils.getRegion("ap-southeast-2")` does work as expected).

**Comment by varunnvs92** [comment] 2017-06-20 17:11
This seems to be a recurring issue. We have a delay in getting the updated endpoints file during our release process. I will investigate the root cause and make changes so that SDK always includes the updated file. As for step functions, this will be included by tomorrow's release.

**Comment by varunnvs92** [comment] 2017-06-29 23:51
Sorry for the silence on the ticket. This issue has been fixed in [1.11.157](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1329) version. Our internal process has been updated to be in sync with other AWS Sdks and provide latest endpoints data we get from service teams.

**Closed by varunnvs92** 2017-06-29 23:51 UTC
Labels: Will fix
