### ISSUE TITLE
AmazonKinesisFirehoseAsyncClient: Unable to unmarshall exception content

### ISSUE THREAD

**Issue by pushkar-g** [aws/aws-sdk-java#1816] opened 2018-11-26 20:10 UTC
We are sporadically (once a day) NullPointerException the below error in production while calling AWS Firehose Client. 

**SDK Version -** 1.11.455
**JVM Version -** 8u181-jre
**AWS Region-** us-west-2

> java.lang.NullPointerException: null
at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745) ~[jackson-databind-2.9.7.jar:2.9.7]
at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52) ~[aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:108) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:96) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:63) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1677) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) [aws-java-sdk-core-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.doInvoke(AmazonKinesisFirehoseClient.java:1342) [aws-java-sdk-kinesis-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(AmazonKinesisFirehoseClient.java:1309) [aws-java-sdk-kinesis-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(AmazonKinesisFirehoseClient.java:1298) [aws-java-sdk-kinesis-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.executePutRecord(AmazonKinesisFirehoseClient.java:759) [aws-java-sdk-kinesis-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseAsyncClient$6.call(AmazonKinesisFirehoseAsyncClient.java:431) [aws-java-sdk-kinesis-1.11.455.jar:na]
at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseAsyncClient$6.call(AmazonKinesisFirehoseAsyncClient.java:425) [aws-java-sdk-kinesis-1.11.455.jar:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by varunnvs92** [comment] 2018-11-26 21:04
It looks like service is sending error content which SDK is unable to unmarshall. Is it possible to capture the wire log for this error scenario and share it? 
**Note:** please make sure there is no sensitive data posted here

**Comment by pushkar-g** [comment] 2018-12-02 21:52
Hi,
Unfortunately this is happening in prod and it would be difficult for us to enable the wire logs with the large amount of data passing through. Is there any logging we could enable in the sdk itself to get more information out of this ? We have observed this error 6 times in the last 7 days.

**Comment by varunnvs92** [comment] 2018-12-03 17:35
SDK has metrics but I don't think they will be useful to debug this issue. Do you have a scenario that we can use to repo the behavior on our end? This seems to be a edge case, it is difficult to debug the issue without a repo case or wirelogs.

**Comment by debora-ito** [comment] 2018-12-10 23:56
Closing due to inactivity. Please feel free to reopen if you have more info on a scenario we can try to reproduce or if you have more questions.

**Comment by alphafoobar** [comment] 2019-03-27 21:04
@debora-ito We have now have more information on this issue.

We can see from the stacktrace that a NullPointerException is being thrown from `ObjectMapper` because the `JsonNode`  is `null`.

> java.lang.NullPointerException: null
>     at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745) ~[jackson-databind-2.9.7.jar:2.9.7]
>     at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52) ~[aws-java-sdk-core-1.11.455.jar:na]

We have identified that this is because there is no content in this error response to build a `JsonNode` from, which corresponds to a `503` response.

The `NullPointerException` is being caught in the `JsonErrorResponseHandler`, which returns null when it catches any `Exception`. which is then converted to the following `new AmazonServiceException("Unable to unmarshall exception response with the unmarshallers provided")`. This exception will be treated as a retryable exception by the `AmazonHttpClient`, so unless the problem persists there should not be any data lost and why `onError` callback methods are not invoked. 

We have captured headers for a 503 response that caused this problem:

> 2019-03-27 16:03:59.703  INFO 1 --- [ool-7-thread-40] c.a.http.JsonErrorResponseHandler        : No errorCode for [statusCode=503, requestId=null]
> 2019-03-27 16:03:59.703  INFO 1 --- [ool-7-thread-40] c.a.http.JsonErrorResponseHandler        : Header [statusCode=503, x-amz-request-id="2C126B3692AD1B30"]
> 2019-03-27 16:03:59.703  INFO 1 --- [ool-7-thread-40] c.a.http.JsonErrorResponseHandler        : Header [statusCode=503, Connection="close"]
> 2019-03-27 16:03:59.703  INFO 1 --- [ool-7-thread-40] c.a.http.JsonErrorResponseHandler        : Header [statusCode=503, Content-Length="0"]
> 2019-03-27 16:03:59.703  INFO 1 --- [ool-7-thread-40] c.a.http.JsonErrorResponseHandler        : Header [statusCode=503, Date="Wed, 27 Mar 19 16:03:59 GMT"]

I also just noticed there is a difference in the header the SDK is looking for to extract the request ID. The SDK is looking for this `X_AMZN_REQUEST_ID_HEADER = "x-amzn-RequestId"` but at least in this scenario, it appears it should be looking for `x-amz-request-id`.

**Comment by alphafoobar** [comment] 2019-03-27 23:30
I've also just noticed the version of `jackson-databind` in our stack trace is not the same as the defined dependency in the aws-sdk-java. Though hopefully not a significant difference.

**Comment by debora-ito** [comment] 2019-03-28 18:59
Reopening this, analysis is pending.

**Comment by millems** [comment] 2020-03-31 21:46
Closing in favor of tracking in the pull request.

**Closed by millems** 2020-03-31 21:46 UTC
Labels: investigating
