### ISSUE TITLE
SQS - Interrupting long-polling

### ISSUE THREAD

**Issue by tmartins1** [aws/aws-sdk-java#2083] opened 2019-08-21 18:03 UTC
According to #655 the only way to interrupt receiveMessage call is by shutting down the client. I've been testing this and I found a problem, in the SQS side the connection will still be "alive" and the next message will be sent through it. For example, if using an AsyncHandler this will trigger the onError method. But no matter how you are receiving messages, the message needs to wait for the visibility timeout to be resent to another subscriber.
I also found this [comment](https://github.com/aws/aws-sdk-js/issues/2350#issuecomment-438463015) that complains about the same thing.

**Comment by varunnvs92** [comment] 2019-08-30 22:11
The issue is same as the one reported in aws-sdk-java-v2 repo. Closing this and track it aws-sdk-java-v2 repo
https://github.com/aws/aws-sdk-java-v2/issues/1395

**Closed by varunnvs92** 2019-08-30 22:11 UTC
