### ISSUE TITLE
Jhipster

### ISSUE THREAD

**Issue by rajatt07** [aws/aws-sdk-java#1813] opened 2018-11-22 07:51 UTC
I've one application which is running live. Application runs well most of the time but sometime it stops working without showing any error.
Is there anyone who can help me out to find out where I'm doing wrong in my project.

**Comment by rajatt07** [comment] 2018-11-22 07:54
com.amazonaws.services.sns.model.PlatformApplicationDisabledException: Platform application is disabled (Service: AmazonSNS; Status Code: 400; Error Code: PlatformApplicationDisabled; Request ID: 91f17c76-7261-5941-be3f-281921efcadd)

**Comment by srchase** [comment] 2018-11-23 21:00
@rajatt07 

That error is returned when the platform has rejected the token.

The SDK appears to be handling this error correctly.  

For additional guidance, please refer to the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=72).  You may want to also refer to this blog post on [token management with SNS](https://aws.amazon.com/blogs/mobile/mobile-token-management-with-amazon-sns/).

**Comment by rajatt07** [comment] 2018-11-26 09:41
So what I really need to do in my program so that my application will run fine.

**Comment by rajatt07** [comment] 2018-11-26 09:54
Some of the errors I'm listing down which I get in my boxfuse console when I use command in my cli ./boxfuse logs instance-id

**Comment by rajatt07** [comment] 2018-11-26 09:58
com.amazonaws.services.sns.model.PlatformApplicationDisabledException: Platform application is disabled (Service: AmazonSNS; Status Code: 400; Error Code: PlatformApplicationDisabled;
com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse;
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest;
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper;

**Comment by rajatt07** [comment] 2018-11-26 10:01
some errors like this 

1. ERROR 1021 --- [  XNIO-2 task-1] c.u.f.w.rest.errors.ExceptionTranslator  : An unexpected error occurred: null

2. java.util.concurrent.ThreadPoolExecutor.runWorker

**Comment by rajatt07** [comment] 2018-11-26 10:02
Now someone would tell me where I'm doing wrong in my program so that I can fix this major bug in my application.

**Comment by varunnvs92** [comment] 2018-11-26 21:35
As @srchase mentioned, `PlatformApplicationDisabledException` is returned from the service. You need to reach out to service team via AWS Forums to investigate why token is being rejected. As per this [post](https://forums.aws.amazon.com/thread.jspa?threadID=170557), this might be caused by expired credential.

Apart from that if you have any other SDK issues, please post the full stack trace for further debugging. 

>> Now someone would tell me where I'm doing wrong in my program

We have limited bandwidth on the team and we can only help with SDK issues. It would not be possible for us to review you application. For general help, I would suggest you to post in stack-overflow to involve larger developer community. See our [Getting Help](https://github.com/aws/aws-sdk-java#getting-help) section.

**Comment by rajatt07** [comment] 2018-11-27 10:29
I'll try it out and if face another Issue I'll ask.

**Comment by rajatt07** [comment] 2018-12-19 06:20
kindly re-look at this issue again.

Exception while sending pushcom.amazonaws.services.sns.model.EndpointDisabledException: Endpoint is disabled (Service: AmazonSNS; Status Code: 400; Error Code:

**Comment by rajatt07** [comment] 2018-12-20 13:41
2018-12-20 18:41:54.672  INFO 70712 --- [           main] c.u.frother.security.jwt.TokenProvider   : Invalid JWT token.

**Comment by debora-ito** [comment] 2019-01-09 18:36
> Apple rejected your credentials, likely due to them being expired, or for a production application.

If your credentials are expired, you need to get new valid credentials. 

Quoting this [post](https://forums.aws.amazon.com/thread.jspa?threadID=170557) mentioned by @varunnvs92: 

>  The application is set to disabled once Apple notifies us that the credentials are expired/invalid or revoked. Please verify that you can use the certificate with Apple (see step 4 in http://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html#verify-cert-private-key-apns)

This is likely the cause of the EndpointDisabledException you are seeing.
And please check the Potential Pitfalls section of the [blog post](https://aws.amazon.com/blogs/mobile/mobile-token-management-with-amazon-sns/) mentioned by @srchase, as it explains how to re-enable a disabled endpoint.

**Comment by rajatt07** [comment] 2019-01-10 12:10
So this could be  the one of reason why my application shuts down sometime. ? 
Previously it was running fine but from last few months I'm facing this issue.

**Comment by rajatt07** [comment] 2019-01-11 06:52
@debora-ito 
The issue is my application was running absolutely fine from last two years. I'm facing this  issue from past couple of months which makes my application shuts down sometime. So, I tried out finding why my application shuts down then I got these errors on my console.  

PlatformApplicationDisabledException and EndpointDisabledException 

So I wonder by managing these errors will my application run fine as it was running before.

**Comment by rajatt07** [comment] 2019-01-11 06:59
AS mentioned by you, I'm trying to follow this method.

Please verify that you can use the certificate with Apple (see step 4 in http://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html#verify-cert-private-key-apns)

**At a command prompt, type the following command. Replace myapnsappcert.pem and myapnsappprivatekey.pem with the name of your certificate and private key.**

Now the problem is  I forgot where I've stored these files : 
myapnsappcert.pem and myapnsappprivatekey.pem.

**Comment by rajatt07** [comment] 2019-01-11 07:02
Is there any other way to get new valid credentials ?
How could I get a new valid credential from Apple ?

**Comment by debora-ito** [comment] 2019-01-21 22:16
The Amazon SNS [Developer Guide](https://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html) has a section explaining how to obtain an APNS SSL Certificate. You can also reach out to Apple Support.

For further issues using SNS, please refer to the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=72) or StackOverflow.

I'll go ahed and close this since there's no issue with the SDK. Please feel free to reopen if you have further questions.

**Closed by debora-ito** 2019-01-21 22:16 UTC
Labels: service-api
