### ISSUE TITLE
API Gateway: invalid sdk generated when java keywords are used as model names

### ISSUE THREAD

**Issue by nhjk** [aws/aws-sdk-java#1243] opened 2017-07-20 11:22 UTC
If you create some models with names like while and float and generate an sdk you get a bunch of invalid code as it generates methods and classes with those identifiers.

For a quick test you can generate the example PetStore api in api gateway. Add a model named while and a model named float with content-type application/json. Give both this schema
```json
{
    "type": "object",
    "properties": {
        "a": { "type": "string" }
    }
}
```
In the /pets resource change the get method's  "Method Response" model to application/json => float, and the post method's "Method Request" request body model to application/json => while. Then deploy a stage, generate a java sdk, and try compiling it.

**Comment by nhjk** [comment] 2017-07-24 12:38
Are you sure this is a feature request? I think not being able to name models java keywords might be a bug.

**Comment by shorea** [comment] 2017-07-24 17:31
What's the expected behavior? Would you expect the generator to sanitize the names to not clash with Java keywords?

**Comment by shorea** [comment] 2017-07-25 21:26
Just had a chat with the team about this. @millems had the excellent idea to only rename the field names since the getters/setters wouldn't clash. Would this work for you?

**Comment by shorea** [comment] 2017-07-27 19:25
Looks like we actually already do this but our list of keywords is incomplete. This should be an easy fix.

**Comment by shorea** [comment] 2017-09-25 17:31
Sorry for the delay here, forgot about this. This will be included in the next release of the SDK.

**Closed by shorea** 2017-09-25 17:31 UTC
Labels: Feature Request, waiting-reply
