### ISSUE TITLE
doesBucketExist() uses different S3 actions than doesObjectExist()

### ISSUE THREAD

**Issue by marnett** [aws/aws-sdk-java#836] opened 2016-09-06 21:14 UTC
I have an IAM role that allows S3 access for all the following actions:

"Sid": "s3Access",
"Effect": "Allow",
"Action": "s3:*"

doesBucketExist() has no problem given these access rules. However, it seems that doesObjectExist uses different Actions to access s3, actions which my IAM role does not have, thus I get a 403 Forbidden error. 

Is this by design? doesBucketExist and doesObject exist seem similar enough that I'd expect if I can do the former given my role then I could do the latter.

**Comment by zhangzhx** [comment] 2016-09-07 16:29
Hi @marnett,

Thanks for reaching out to us. I'm wondering what resources do you attach to theses Actions. Have you attached all the resources in the policy as `"Resource": ["*"]`?

**Comment by marnett** [comment] 2016-09-07 16:45
so the resource is like the below layout:
"Resource": "arn:aws:s3:::{standard-beginning-of-project-bucketname}-*"

i.e.
I have access to the follow buckets if the standard beginning was "project-one"
project-one-private
project-one-stacks
project-one-jars
etc. 

So I am checking a bucket that follows this naming scheme, and the doesBucketExists() works fine. But if I try to see if an object exists in that same bucket, I get the 403 error. I read somewhere that the doesObjectExists() accesses metadata - I replicated the same error when I implemented my own doesObjectExistOnS3
[doesObjectExistOnS3.txt](https://github.com/aws/aws-sdk-java/files/459755/doesObjectExistOnS3.txt)

(String bucketName, String path), the snippet is attached.

**Comment by zhangzhx** [comment] 2016-09-07 17:44
I don't see any problem with the Resource configuration, but I'm surprised 403 error is returned. I'v tried same configuration, and I don't see 403 error for the object I have access to.

However, the behaviors for `doesBucketExist` and `doesObjectExist` do differ that `doesBucketExist` will return true even it returns 403 forbidden, while `doesObjectExist` will explicitly throw the exception if it is not allowed to access. This is an intended behavior.

Can you double check the policy, and turn on the log4j to see what is returned from the wire when you call `doesBucketExist`?

**Comment by varunnvs92** [comment] 2016-10-14 23:47
@marnett 
If I have a bucket with name "TestBucket",
1) **"Resource": "arn:aws:s3:::TestBucket"** gives access only to the bucket but not its objects. (you can change permissions, settings on bucket like enabling bucketAccelerateConfiguration.)
2) **"Resource": "arn:aws:s3:::TestBucket/\*\*"** gives access to the objects inside the bucket. 
So you need to add **"/\*\*"**  at end of bucket name to get access to the objects.

**Note**
One interesting thing I found with **"Resource": "arn:aws:s3:::TestBucket/\*\*"**  is that you lose permissions to operate on bucket i.e, you can't do the actions you could have done with option 1.
If you need permissions on both bucket and its objects, your resource should look like
**"Resource": ["arn:aws:s3:::TestBucket", "arn:aws:s3:::TestBucket/\*\*"]**

One final thing is even if you only specify option 2, doesBucketExist operation works fine. This is because the SDK catches the exception and returns true if status code is 403.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1191-L1197

Closing the issue. Feel free to re-open if you have more questions. Thank you.

**Closed by varunnvs92** 2016-10-14 23:47 UTC
