### ISSUE TITLE
putObject sometimes throw exception : bad request

### ISSUE THREAD

**Issue by KelinTan** [aws/aws-sdk-java#1925] opened 2019-02-26 08:37 UTC
hi:
  i use sdk 1.11.228
  with method `putObject` to upload img to s3

in the majority of cases, it works well,but sometimes (may be 1 of 15),it would throws exception ：

```
com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4319)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4266)        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1746)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1601)        at com.alo7.student.s3.S3HeplerImpl.uploadObject(S3HeplerImpl.java:53)
```

  this is my code ：

```
String fileName = generateFileName(getExtension(file));
String key = path + fileName;
File tempFile = new File(FILE_TEMP_PATH + fileName);
try {
            file.transferTo(tempFile);
            client.putObject(StringUtils.EMPTY, key, tempFile);
        } catch (AmazonS3Exception e) {
            log.error(new LogMessageBuilder("S3 upload failed")
                    .withParameter("file", key)
                    .withParameter("response", e.getErrorResponseXml())
                    .withParameter("message", e.getMessage())
                    .withParameter("addition", e.getAdditionalDetails())
                    .build());
            throw Alo7Error.SYSTEM_ERROR.toAlo7RuntimeException("s3 upload object error");
        } catch (Exception e) {
            log.error(e);
            throw Alo7Error.SYSTEM_ERROR.toAlo7RuntimeException("s3 upload object error");
        } finally {
            if (tempFile.exists()) {
                FileUtils.deleteQuietly(tempFile);
            }
        }
```
 
any question may cause this exception?

thanks.

**Comment by KelinTan** [comment] 2019-02-26 09:18
create client : 

```
 private AmazonS3 createCdnClient(String cdnEndpoint, Protocol protocol) {
        AWSCredentials awsCredentials = new BasicAWSCredentials(config.getAwsKeyId(), config.getAwsSecretKey());

        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setProtocol(protocol);

        EndpointConfiguration endpointConfiguration =
                new EndpointConfiguration(cdnEndpoint, Regions.CN_NORTH_1.getName());

        return AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .withClientConfiguration(clientConfiguration)
                .withEndpointConfiguration(endpointConfiguration)
                .build();
    }
```

**Comment by debora-ito** [comment] 2019-02-26 21:59
Hi @KelinTan, what region is your client using? My guess is  your client's region and the region you are setting for signing (CN_NORTH_1) are different. 

Is there any particular reason for setting the EndpointConfiguration, instead of using `.withRegion()` ?

Could you [enable wire logging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) to get additional information on the request and provide the logs? Please make sure there is no sensitive data in the logs.

**Comment by KelinTan** [comment] 2019-02-27 02:46
i will try with this?:
```
 EndpointConfiguration endpointConfiguration =
                new EndpointConfiguration(cdnEndpoint, Regions.CN_NORTH_1.getName());

        return AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .withClientConfiguration(clientConfiguration)
                .withEndpointConfiguration(endpointConfiguration)
                .withRegion(Regions.CN_NORTH_1)
                .build();
```
sorry,this excpetion happens in production environment,may not enable logging

thanks.

**Comment by debora-ito** [comment] 2019-02-27 04:16
Can you reproduce the error locally? If it's only occurring in production, the cause may be something else. Without the wire logs it's difficult to analyze, since the request response only says `Bad Request` and doesn't  even include a Request ID.

If you use [`.withRegion(Regions.CN_NORTH_1)`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.html#withRegion-com.amazonaws.regions.Regions-) you don't need to set `.withEndpointConfiguration(endpointConfiguration)` because the SDK will automatically choose an appropriate endpoint for you.

For more info on creating service clients, please check this guide: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/creating-clients.html.

So it would be:

```java
return AmazonS3ClientBuilder.standard()
        .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
        .withClientConfiguration(clientConfiguration)
        .withRegion(Regions.CN_NORTH_1)
        .build();
```

Also, HTTPS is the default protocol, so if you're using HTTPS and setting only the protocol in  clientConfiguration, you don't need to use `.withClientConfiguration()` too.

**Comment by KelinTan** [comment] 2019-02-27 05:32
That is the problem that  I can not reproduce the error locally...

I guess that may occurs because of the network dithering. For this ,I would try to retry 3 times when 

catching Exception like `AmazonS3Exception`

Hope it help.

**Comment by KelinTan** [comment] 2019-02-27 10:39
Retry 3 times is OK. 

Thanks again.

**Comment by debora-ito** [comment] 2019-02-28 22:18
Ok, gonna go ahead and close this. Feel free to reopen if you have further questions.

**Closed by debora-ito** 2019-02-28 22:18 UTC
Labels: guidance

**Comment by KelinTan** [comment] 2019-03-15 12:38
> Retry 3 times is OK.
> 
> Thanks again.

This is not the best solution. 

Finally I remove the `withEndpointConfiguration ` config. That works well .

`private AmazonS3 createClient() {
        AWSCredentials awsCredentials = new BasicAWSCredentials(config.getAwsKeyId(), config.getAwsSecretKey());
        return AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .withRegion(Regions.CN_NORTH_1)
                .build();
    }`
